<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	$customlabel = "";
	
	$style = '1';
	if(!isEmptyString($request->style)){
		$style = $request->style;
		$session->setVar('style', $request->style);
	}
	if(isEmptyString($request->style) && !isEmptyString($session->getVar('style'))){
		$style = $session->getVar('style');
	}
	
	$startdate = $request->startdate;
	$enddate = $request->enddate;
	if(!isEmptyString($startdate)){
		$startdate = changeDateFromPageToMySQLFormat($startdate);
		$allowclear = true;
	}
	$enddate = $request->getParam('enddate');
	if(!isEmptyString($enddate)){
		$enddate = changeDateFromPageToMySQLFormat($enddate);
		$allowclear = true;
	}
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("c.name","c.email","c.phone","c.contactperson"));
	$paginate->setFilterColumns(array());
	$paginate->setItemCountPerPage("25");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE c.id <> '' ";
	$allowclear = false;
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	$status = trim($request->status);
	if(!isEmptyString($status)){
		$where_query .= " AND c.`status` = '".$status."' ";
		$allowclear = true;
	}
	if(!isEmptyString($startdate)){
		$where_query .= " AND (TO_DAYS(c.datecreated) >= TO_DAYS('".$startdate."')) ";
		$allowclear = true;
	}
	if(!isEmptyString($enddate)){
		$where_query .= " AND (TO_DAYS(c.datecreated) <= TO_DAYS('".$enddate."')) ";
		$allowclear = true;
	}
		
	$profilerid = $request->profilerid;
	if(!isEmptyString($profilerid)){
		$where_query .= " AND c.createdby = '".$profilerid."' ";
		$allowclear = true;
	}
	
	$order = trim($request->order);
	$order_query = " ORDER BY c.datecreated DESC, c.id desc ";
	
	$sortcolumn = $request->sortby;
	$sortorder = $request->sortorder;
	if(!isEmptyString($sortcolumn) && !isEmptyString($sortorder)){
		$order_query = " ORDER BY " . $sortcolumn. " " .$sortorder. " ";
	}
	// f.orgname as fundername, concat(c.firstname,' ',c.lastname) as supervisorname
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT c.id as cid, c.name, c.email, c.phone, mc.displayname, concat(mc.firstname, ' ', mc.lastname, ' ', mc.othername) as addedby, c.industrycode, c.status, c.datecreated, c.contactperson, concat(cu.firstname, ' ', cu.lastname, ' ', cu.othername) as defaultuser
	 FROM company c
	 left join useraccount mc on (c.createdby = mc.id)
	 left join useraccount cu on (c.defaultuserid = cu.id)
	 ".$where_query." ".$paginate->getSearchAndFilterSQL()." GROUP BY c.id ".$order_query;
	// debugMessage($all_results_query); // exit;
	
	$paginate->setItemCountFromSQLQuery($all_results_query);
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	$listurl = $this->baseUrl('profile/list');
	$addurl = $this->baseUrl($controller);
	$title = "Companies";
	$listitems = "Companies";
	$moduleitem = "Company";
	$description = '';
	$icon = 'fa fa-bars';
	$resource = 'Company';
	$statuses =  getCompanyStatuses(); 
	$companycategories = getDatavariables('INDUSTRY_CATEGORIES');
	
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
		$('.titlelabel').html('<?php echo $title.$customlabel; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
		
	});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
    <div class="row">
	<div class="col-sm-12">
    	<form class="form-horizontal" action="<?php echo $this->baseUrl($controller."/listsearch"); ?>" method="get" id="listform">
		<div class="box box box-color xbox-bordered">
			<div class="box-title noheader">
                <h3></h3>
            </div>
            <div class="box-content nopadding">
                <div class="row">
                    <div class="col-sm-9">
                        <ul class="resetlist listactions">
                            <?php if ($acl->checkPermission($resource, ACTION_CREATE)) { ?>
                                <li><a title="New <?php echo $moduleitem; ?>" class="btn btn-primary xbtn-sm blockanchor" href="<?php echo $addurl; ?>">New <?php echo $moduleitem; ?></a></li>
                            <?php } ?>
                            <li>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('status',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Statuses'), $statuses),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array("xautofilter", "form-control", 'width150', 'input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($request->getParam('status')); 
                                    echo $dropdown->render();
                                ?>                    
                            </li>
                            <li>
                                <button type="submit" class="btn btn-default btn-sm blockanchor" id="filter"><i class="fa fa-filter"></i></button>
                            </li>
                        </ul>
                    </div>
                    <div class="col-sm-3">
                        <div class="divider5"></div>
                        <div class="col-sm-12 padding0">
                            <div class="input-group">
                                <input name="searchterm" id="searchterm" class="form-control form-search" value="<?php echo $request->searchterm; ?>" type="text" placeholder="Search..." />
                                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            </div>
                        </div>	
                        <input type="hidden" name="letter" id="letter" value="<?php echo $request->getParam('letter'); ?>" />
                        <input type="hidden" name="style" id="style" value="<?php echo $style; ?>" />
                        <input type="hidden" name="exporttrigger" id="exporttrigger" value="<?php echo $request->exporttrigger; ?>" />
                    </div>
                </div>
                <div class="row">
					<div class="col-sm-12">
						<div class="box box-color box-bordered">
							<div class="box-title condensed">
								<h3><i class="glyphicon-list"></i> Manage Companies</h3>
                                <div class="actions">
                                	<a class="btn bluelinks" href="<?php echo $this->baseUrl('report/employeedetails'); ?>">View Detailed Employee Report</a> &nbsp;
                                	<a href="<?php echo $listurl; ?>" title="Reset List and Clear all Filters" rel="tooltip"><i class="fa fa-refresh"></i></a> &nbsp;
                                </div>
							</div>
							<div class="box-content nopadding">
								<div class="row-fluid peoplelist clearfix <?php echo $style == '2' ? 'whitebg' : ''; ?>">
                                    <?php if($has_no_data){ ?>
                                        <div class="alert alert-warning"><?php echo $this->translate("global_list_noentries"); ?></div>
                                    <?php } else { ?>
                                        <div class="divider10"></div>
                                            <?php
                                                foreach($result as $line){
                                                    $viewurl = stripUrl($this->baseUrl($controller.'/view/id/'.encode($line['cid'])));
                                                    $indexurl = stripUrl($this->baseUrl($controller.'/index/id/'.encode($line['cid'])));
                                                    
                                                    $isme = false;
                                                    if($line['cid'] == $companyid){
                                                        $isme = true;
                                                    }
                                                    $allowedit = false;
                                                    if($acl->checkPermission($resource, ACTION_EDIT)){
                                                        $allowedit = true;
                                                    }
                                            ?>
                                                 <div class="col-xs-12 col-sm-6">
                                                    <div class="peoplewrapper makerelative">
                                                        <div class="btn-group gridactions" style="z-index:1000;">
                                                            <button type="button" class="btn btn-default btn-xs dropdown-toggle noround" data-toggle="dropdown">Action <span class="caret"></span></button>
                                                            <ul class="dropdown-menu" role="menu" style="left:-102px;">
                                                                <?php if ($acl->checkPermission($resource, ACTION_VIEW)) { ?>
                                                                    <li><a class="blockanchor" href="<?php echo $viewurl; ?>">View Profile</a></li>
                                                                <?php } ?>
                                                                <?php if ($allowedit) { ?>
                                                                    <li><a class="blockanchor" href="<?php echo $indexurl; ?>">Update</a></li>
                                                                <?php } ?>
                                                            </ul>
                                                        </div>
                                                        <div class="col-sm-2 padding0 centeralign">
                                                            <i class="fa fa-briefcase" style="font-size:60px;"></i>
                                                        </div>
                                                        <div class="peopleinfo col-sm-10">
                                                            <h4><a href="<?php echo $viewurl; ?>" class="blockanchor"><?php echo $line['name']; ?></a></h4>
                                                            <div class="row-fluid margin0">
                                                                <div class="col-sm-7 padding0">
                                                                    <ul class="resetlist">
                                                                        <li><span class="bolded">Category:</span> <span class="nullifempty"><?php echo isArrayKeyAnEmptyString($line['industrycode'], $companycategories) ? '' : $companycategories[$line['industrycode']]; ?></span></li>
                                                                        <li><span class="bolded">Start Date: </span> <span class="nullifempty"><?php echo formatDateAndTime($line['datecreated'], false); ?></span></li>
                                                                        <li><span class="bolded">Status: </span><span class="nullifempty"><?php echo isArrayKeyAnEmptyString($line['status'], $statuses) ? '' :$statuses[$line['status']]; ?></span></li>
                                                                        <li><span class="bolded">Added By: </span> <span class="nullifempty"><?php echo $line['addedby']; ?></span></li>
                                                                    </ul>
                                                                </div>
                                                                <div class="col-sm-5 padding0">
                                                                    <ul class="resetlist">
                                                                        <li><span class="bolded">Contacts</span></li>
                                                                        <li><span class="nullifempty"><?php echo $line['contactperson']; ?></span></li>
                                                                        <li><span class="nullifempty"><?php echo snippet($line['email'], '23','...'); ?></span></li>
                                                                        <li><span class="nullifempty"><?php echo $line['phone']; ?></span></li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                           <?php } ?> 
                                    <?php } ?>
                                    <?php if(!$has_no_data){ ?> 
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="form-actions">
                                                    <div class="col-sm-3 paddingleft5 floatleft"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                                                    <div class="col-sm-6 padding0"><?php echo $paginate->getPaginationLinks(); ?></div>
                                                    <div class="col-sm-3 padding0 rightalign"><?php echo $paginate->getListCountDropDown(); ?></div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php } ?>
								</div>
							</div>
						</div>
					</div>
          		</div>
			</div>
        </div>
        </form>          
	</div>            
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
