<?php
	require_once APPLICATION_PATH.'/includes/header.php';

	$title = "Reports Dashboard"; 
	$description = "";
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	// breadcrumb config
	$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="glyphicon glyphglyphicon glyphicon-signal"></span>');
	
}); 
</script>
<div class="row-fluid margin0 view">
    <div class="col-md-12 padding0">
    	<div class="headerbox">
            <table class="table border0 nohover margin0">                       
                <tr>		                    
                    <td class="padding2">
                    	
                    </td>
                </tr>
            </table>
        </div>
    </div>
    <?php if($sessionhaserror) { ?>
        <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
    <?php } ?>
    <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
        <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
    <?php } ?>
    <div class="row row-bg" style="margin-bottom:10px;">
            <div class="col-md-12">
                <div class="widget box hidden-xs">
                    <div class="widget-header">
                        <h4><i class="glyphicon glyphicon-align-justify"></i> Statistics</h4>
                        <div class="toolbar no-padding">
                            <div class="btn-group">
                                <span class="btn btn-xs widget-collapse" style="padding:11px; margin:0;"><i class="icon-angle-down"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="widget-content no-padding whitebg" style="height:215px;">
                        
                    </div>
                </div>
            </div>
        </div>
    <div class="contentcontainer clearfix">
    	
        <div class="row-fluid">
            <div id="dashboard-left" class="col-md-12 padding0 dashboard">
                <div class="row row-bg margin0 padding0">
                    <div class="divider10"></div>
                    <?php if($acl->checkPermission('Report 2', ACTION_VIEW)) { ?>
                        <div class="col-sm-4 col-md-4">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-content">
                                    <a href="<?php //echo $this->baseUrl('report/memberlocation'); ?>" class="nodecoration clearfix gonowhere xblockanchor">
                                        <div class="visual blue"><i class="icon-large icon-signal white" style="font-size:24px;"></i></div>
                                        <div class="title">Employee Profiles</div>
                                        <div class="value"></div>
                                    </a>
                                    <a href="<?php //echo $this->baseUrl('report/memberlocation'); ?>" class="more gonowhere xblockanchor">View Report <i class="pull-right glyphicon glyphicon-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
					<?php if($acl->checkPermission('Payroll', ACTION_LIST)) { ?>	
                        <div class="col-sm-4 col-md-4">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-content">
                                    <a href="<?php echo $this->baseUrl('payroll/list'); ?>" class="nodecoration clearfix blockanchor">
                                        <div class="visual cyan"><i class="icon-large icon-signal white" style="font-size:24px;"></i></div>
                                        <div class="title">Payroll Processing</span></div>
                                        <div class="value"></div>
                                    </a>
                                    <a href="<?php echo $this->baseUrl('payroll/list'); ?>" class="more">View Reports <i class="pull-right glyphicon glyphicon-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                    <?php if($acl->checkPermission('Report 1', ACTION_VIEW)) { ?>
                        <div class="col-sm-4 col-md-4">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-content">
                                    <a href="<?php //echo $this->baseUrl('report/membertrend'); ?>" class="nodecoration clearfix gonowhere xblockanchor">
                                        <div class="visual red"><i class="icon-large icon-signal white" style="font-size:24px;"></i></div>
                                        <div class="title">Approved Hours Report</span></div>
                                        <div class="value"></div>
                                    </a>
                                    <a href="<?php //echo $this->baseUrl('report/membertrend'); ?>" class="more gonowhere xblockanchor">View Report <i class="pull-right glyphicon glyphicon-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                    <?php if($acl->checkPermission('Report 1', ACTION_VIEW)) { ?>
                        <div class="col-sm-4 col-md-4">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-content">
                                    <a href="<?php //echo $this->baseUrl('report/membertrend'); ?>" class="nodecoration clearfix gonowhere xblockanchor">
                                        <div class="visual red"><i class="icon-large icon-signal white" style="font-size:24px;"></i></div>
                                        <div class="title">Employee Attendance</span></div>
                                        <div class="value"></div>
                                    </a>
                                    <a href="<?php //echo $this->baseUrl('report/membertrend'); ?>" class="more gonowhere xblockanchor">View Report <i class="pull-right glyphicon glyphicon-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                    <?php if($acl->checkPermission('Report 3', ACTION_VIEW)) { ?>
                        <div class="col-sm-4 col-md-4">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-content">
                                    <a href="<?php //echo $this->baseUrl('report/churchstats'); ?>" class="nodecoration clearfix gonowhere xblockanchor">
                                        <div class="visual cyan"><i class="icon-large icon-signal white" style="font-size:24px;"></i></div>
                                        <div class="title">Employee Benefits</div>
                                        <div class="value"></div>
                                    </a>
                                    <a href="<?php //echo $this->baseUrl('report/churchstats'); ?>" class="more gonowhere xblockanchor">View Report <i class="pull-right glyphicon glyphicon-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                    <?php } ?> 
					<?php if($acl->checkPermission('Report 2', ACTION_VIEW)) { ?>
                        <div class="col-sm-4 col-md-4">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-content">
                                    <a href="<?php //echo $this->baseUrl('report/memberlocation'); ?>" class="nodecoration clearfix gonowhere xblockanchor">
                                        <div class="visual blue"><i class="icon-large icon-signal white" style="font-size:24px;"></i></div>
                                        <div class="title">Time Off Accruals</div>
                                        <div class="value"></div>
                                    </a>
                                    <a href="<?php //echo $this->baseUrl('report/memberlocation'); ?>" class="more gonowhere xblockanchor">View Report <i class="pull-right glyphicon glyphicon-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                    <?php if($acl->checkPermission('Audit Trail Report', ACTION_VIEW)) { ?>
                        <div class="col-sm-4 col-md-4">
                            <div class="statbox widget box box-shadow">
                                <div class="widget-content">
                                    <a href="<?php echo $this->baseUrl('report/audittrail'); ?>" class="nodecoration clearfix blockanchor">
                                        <div class="visual red"><i class="icon-large icon-signal white" style="font-size:24px;"></i></div>
                                        <div class="title">Transaction AuditTrail</div>
                                        <div class="value"></div>
                                    </a>
                                    <a href="<?php echo $this->baseUrl('report/audittrail'); ?>" class="more">View Report <i class="pull-right glyphicon glyphicon-angle-right"></i></a>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
   	</div>
</div>          
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
