<?php
	include APPLICATION_PATH.'/includes/header.php';

	$toggled = $session->getVar('toggled');
	$toggledclass = '';
	// $toggled = 1;
	if($toggled == '1'){
		$toggledclass = ' toggled';
	}
	
?>
<div id="navigation" class="<?php echo $topbar == 2 ? 'navbar-fixed-top' : ''; ?>">
    <div class="<?php echo $layout == 1 ? 'container-fluid' : 'container'; ?>" <?php echo $logotype == 1 ? 'style="padding-left:0;"' : ''; ?>>
		<a href="<?php echo $this->baseUrl('dashboard'); ?>" id="brand" class="<?php echo $logotype == 1 ? 'centeralign' : ''; ?>" style="background:none; padding-left:0; padding-right:0;  <?php echo $logotype == 1 ? 'min-width:175px; max-width:180px; margin-top:5px;' : ''; ?>">	
			<?php if($logotype == 0){ ?>
                <img src="<?php echo $logourl; ?>" style="height:22px; width:auto;" /> <?php echo $appname; ?>
            <?php } ?>
            <?php if($logotype == 1){ ?>
                <img src="<?php echo $logourl; ?>" style="height:30px; width:auto;" />
            <?php } ?>
            <?php if($logotype == 2){ ?>
                <?php echo $appname; ?>
            <?php } ?>
        </a>
        <?php if(isLoggedIn()){ ?>
        	<a class="toggle-nav gonowhere <?php echo $showsidebar == 1 ? 'hasbar' : ''; ?>" href="javascript: void(0)" rel="tooltip" data-placement="bottom" title="Toggle navigation"><i class="fa fa-bars"></i></a>
        <?php } else { ?>
        	<a class="gonowhere" href="javascript: void(0)" data-placement="bottom" style="float: left; color: #fff; display: block; padding: 10px; font-size: 14px;
text-decoration: none;"><i class="fa fa-bars"></i></a>
        <?php } ?>
        <ul class='main-nav'>
        	<?php if($isloggedin) { ?>
            	<li class="<?php echo $controller == 'dashboard' ? 'active' : ''; ?>"><a href="<?php echo $this->baseUrl('dashboard'); ?>"><span>Dashboard</span></a></li>
            <?php } ?>
            <?php if($acl->checkPermission('User Account', ACTION_LIST)) { ?>	
                <li class="<?php echo $controller == 'profile' ? 'active' : ''; ?>">
                    <a href="#" data-toggle="dropdown" class='dropdown-toggle'><span>Employees</span><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                    	<?php if($acl->checkPermission('User Account', ACTION_LIST)) { ?>	
                        	<li><a class="blockanchor" href="<?php echo $this->baseUrl('profile/list'); ?>">Manage Employees</a></li>
                        <?php } ?>
                        <?php if ($acl->checkPermission('User Account', ACTION_CREATE)) { ?>	
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('profile'); ?>">New Employee</a></li>
                        <?php } ?>
                        <li class='dropdown-submenu'>
                            <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Reports</a>
                            <ul class="dropdown-menu">
                                <?php if ($acl->checkPermission('Employee Statistics Report', ACTION_VIEW)) { ?>  
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/employeestats'); ?>">Employee Statistics</a></li>
                                <?php } ?>
                                <?php if($acl->checkPermission('Employee Data Report', ACTION_VIEW)) { ?>
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/employeedetails'); ?>">Employee Data Report</a></li>
                                <?php } ?>
                            </ul>
                        </li>
                    </ul>
                </li>
            <?php } ?>
			<?php if($acl->checkPermission('Timesheets', ACTION_LIST)) { ?>
                <li class="<?php echo $controller == 'timesheets' ? 'active' : ''; ?>">
                    <a href="#" data-toggle="dropdown" class='dropdown-toggle'><span>Timesheets</span><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <?php if ($acl->checkPermission('Attendance', ACTION_CREATE) || isADmin() || isCompanyAdmin()) { ?>
							<li><a class="<?php echo $ischeckin ? 'alert-dialog gonowhere disabled' : 'addpopup'; ?>" href="<?php echo $this->baseUrl('timesheets/checkin/userid/'.encode($session->getVar('userid')).'/pgc/true'); ?>"  title="Check In" rel="Check In" id="checkin" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("timesheets/processattendance"); ?>" message="Already In!" submittext="Check-In Now" submiticon="arrow-right">Check In</a>
							</li>
						<?php } ?>
                        <?php if($ischeckin){ ?>
                        	<li><a class="<?php echo $isoverdue ? 'confirm-dialog' : 'addpopup'; ?>" href="<?php echo $this->baseUrl('timesheets/checkin/id/'.encode($checkindetails['id']).'/type/2/userid/'.encode($checkindetails['userid']).'/pgc/true'); ?>"  title="Check Out" rel="Check Out" id="checkout" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("timesheets/processattendance"); ?>" submittext="Check-Out Now" message="Checkout overdue and has been disabled. Contact Admin or a Supervisor.">Check Out</a>
							</li>
                        <?php } ?>
						<?php if ($acl->checkPermission('Timesheets', ACTION_CREATE)) { ?>
                        	<li><a class="addpopup" href="<?php echo $this->baseUrl('timesheets/request/userid/'.encode($session->getVar('userid')).'/pgc/true'); ?>"  title="Request Additional Time" rel="New Timesheet Request" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("timesheets/processattendance"); ?>" submittext="Submit Timesheet">Add Timesheet</a></li>
                        <?php } ?>
						<?php if ($acl->checkPermission('Attendance', ACTION_LIST)) { ?>
							<li><a class="blockanchor" href="<?php echo $this->baseUrl('timesheets/attendance'); ?>">Attendance History</a></li>
						<?php } ?>
						<?php if ($acl->checkPermission('Timesheets', ACTION_APPROVE)) { ?>
							<li><a class="blockanchor" href="<?php echo $this->baseUrl('timesheets/forapproval'); ?>">Timesheets for Approval</a></li>
						<?php } ?>
						<?php if ($acl->checkPermission('Timesheets', ACTION_LIST)) { ?>
							<li><a class="blockanchor" href="<?php echo $this->baseUrl('timesheets/list'); ?>">Timesheets Weekly View</a></li>
							<li><a class="blockanchor" href="<?php echo $this->baseUrl('timesheets/list/view/month'); ?>">Timesheets Monthly View</a></li>
						<?php } ?>
                        <li class='dropdown-submenu'>
                            <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Reports</a>
                            <ul class="dropdown-menu">
                                <?php if ($acl->checkPermission('Attendance Analysis Report', ACTION_VIEW)) { ?>  
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/attendancestats'); ?>"><?php echo $mytext; ?>Attendance Analysis</a></li>
                                <?php } ?>
                                <?php if ($acl->checkPermission('Attendance Detailed Report', ACTION_VIEW)) { ?>  
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/attendancedetails'); ?>"><?php echo $mytext; ?>Attendance Detailed Report</a></li>
                                <?php } ?>
                            </ul>
                        </li>
                    </ul>
                </li>
            <?php } ?>
            <?php if($acl->checkPermission('Benefits', ACTION_LIST)) { ?>
                <li class="<?php echo $controller == 'ledger' ? 'active' : ''; ?>">
                    <a href="#" data-toggle="dropdown" class='dropdown-toggle'><span>Finance</span><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <?php if ($acl->checkPermission('Benefits', ACTION_LIST)) { ?>
                        	<li class='dropdown-submenu'>
                                <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Benefits</a>
                                <ul class="dropdown-menu">
                                	<li><a class="blockanchor" href="<?php echo $this->baseUrl('ledger/list/ledgertype/1'); ?>"><?php echo $istimesheetuser ? 'Benefits History' : 'Manage Benefits'; ?></a></li>
                                    <?php if ($acl->checkPermission('Benefits', ACTION_CREATE) && (isAdmin() || isCompanyAdmin())) { ?>
                                        <li><a class="addpopup" href="<?php echo $this->baseUrl('ledger/index/pgc/true/type/1'); ?>"  title="Add OneTime Benefit" rel="Add OneTime Benefit" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("ledger/create"); ?>" submittext="Save">Add Benefit</a></li>
                                        <li><a class="addpopup" href="<?php echo $this->baseUrl('ledger/index/pgc/true/type/2'); ?>"  title="Add Deduction" rel="Add Deduction" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("ledger/create"); ?>" submittext="Save">Add Deduction</a></li>
                                    <?php } ?>
                                    <?php if($istimesheetuser && !isCompanyAdmin()) { ?>
                                        <li><a class="addpopup" href="<?php echo $this->baseUrl('ledger/request/userid/'.encode($session->getVar('userid')).'/pgc/true'); ?>"  title="Request Additional Benefit" rel="New Benefit Request" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("ledger/processrequest"); ?>" submittext="Submit">Request Benefit</a></li>
                                    <?php } ?>
                                    <?php if ($acl->checkPermission('Benefits', ACTION_APPROVE)) { ?>
                                         <li><a class="blockanchor" href="<?php echo $this->baseUrl('ledger/forapproval'); ?>">Requests for Approval</a></li>
                                    <?php } ?>
                                    <li class='dropdown-submenu'>
                                        <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Reports</a>
                                        <ul class="dropdown-menu">
                                            <?php if ($acl->checkPermission('Benefits Analysis Report', ACTION_VIEW)) { ?>  
                                                <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/benefitstats'); ?>"><?php echo $mytext; ?>Benefits Analysis</a></li>
                                            <?php } ?>
                                            <?php if ($acl->checkPermission('Benefits Detailed Report', ACTION_VIEW)) { ?>  
                                                <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/benefitdetails'); ?>"><?php echo $mytext; ?>Benefits Data Report</a></li>
                                            <?php } ?>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Payroll', ACTION_LIST)) { ?>
                            <li class='dropdown-submenu'>
                                <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Payroll</a>
                                <ul class="dropdown-menu">
									<?php if($acl->checkPermission('Payroll', ACTION_CREATE)) { ?>
                                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('payroll/list'); ?>">Generate New Payroll</a></li>
                                    <?php } ?>
                                    <?php if($acl->checkPermission('Payroll', ACTION_LIST)) { ?>
                                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('payroll/history'); ?>">Payroll History</a></li>
                                        <li><a class="blockanchor" href="<?php echo $currentmonthpayrollurl; ?>"><?php echo date('F Y', strtotime($firstdayofcurrentmonth)); ?> Payroll</a></li>
                                        <li><a class="blockanchor" href="<?php echo $lastmonthpayrollurl; ?>"><?php echo date('F Y', strtotime($firstdayoflastmonth)); ?> Payroll</a></li>
                                    <?php } ?>
                                </ul>
                            </li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Payslips', ACTION_VIEW)) { ?>
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/payslips'); ?>">Payslips</a></li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Bank Credit Instructions', ACTION_VIEW)) { ?>
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/bankadvice'); ?>">Bank Credit Instructions</a></li>
                        <?php } ?>    
                        <?php if($acl->checkPermission('Tax Remittance', ACTION_VIEW)) { ?>
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/paye'); ?>">Tax Remittance</a></li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Insurance Remittance', ACTION_VIEW)) { ?>
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/nssf'); ?>">Insurance Remittance</a></li>
                        <?php } ?>
                    </ul>
                </li>
            <?php } ?>
            <?php if($acl->checkPermission('Leave', ACTION_LIST)) { ?>
                <li class="<?php echo $controller == 'leave' ? 'active' : ''; ?>">
                    <a href="#" data-toggle="dropdown" class='dropdown-toggle'><span>Leave</span><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                    	<?php if ($acl->checkPermission('Leave', ACTION_CREATE) && !$acl->checkPermission('Leave', ACTION_APPROVE) && $loggedinuser->isPermanent()) { ?>
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('leave/index'); ?>">Request Leave</a></li>
                        <?php } ?>
                        <?php if ($acl->checkPermission('Leave', ACTION_APPROVE)) { ?>
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('leave/list/whoisoff/1'); ?>">Who is Off?</a></li>
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('leave/list/forapproval/1'); ?>"> Requests for Approval</a></li>
                        <?php } ?>
                        <?php if ($acl->checkPermission('Leave', ACTION_LIST)) { ?>
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('leave/list'); ?>"><?php echo $istimesheetuser ? 'My Leave' : 'All Leave'; ?> Requests</a></li>
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('ledger/list/ledgertype/2'); ?>"><?php echo $mytext; ?>Leave Accruals</a></li>
                        <?php } ?>
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('calendar/index'); ?>">Calendar</a></li>
                        <li class='dropdown-submenu'>
                            <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Reports</a>
                            <ul class="dropdown-menu">
                                <?php if ($acl->checkPermission('Leave Analysis Report', ACTION_VIEW)) { ?>  
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/leavestats'); ?>"><?php echo $mytext; ?>Analysis Report</a></li>
                                <?php } ?>
                                <?php if ($acl->checkPermission('Leave Accruals Report', ACTION_VIEW)) { ?>  
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/leavedetails'); ?>"><?php echo $mytext; ?>Accruals Report</a></li>
                                <?php } ?>
                            </ul>
                        </li>
                    </ul>
                </li>
            <?php } ?>
            <?php if ($acl->checkPermission('Report Dashboard', ACTION_VIEW)) { ?>
                <li class="<?php echo $controller == 'report' ? 'active' : ''; ?>">
                    <a data-toggle="dropdown" class='dropdown-toggle' href="<?php echo $this->baseUrl('report/dashboard'); ?>"><span>Reports</span> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/dashboard'); ?>">Reports Dashboard</a></li>
                        <?php if($acl->checkPermission('Employee Statistics Report', ACTION_VIEW)) { ?>
                            <li class='dropdown-submenu'>
                                <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Employees</a>
                                <ul class="dropdown-menu">
                                	<?php if($acl->checkPermission('Employee Statistics Report', ACTION_VIEW)) { ?>
                                    	<li><a class="blockanchor" href="<?php echo $this->baseUrl('report/employeestats'); ?>">Statistics</a></li>
                                    <?php } ?>
                                    <?php if($acl->checkPermission('Employee Data Report', ACTION_VIEW)) { ?>
                                    	<li><a class="blockanchor" href="<?php echo $this->baseUrl('report/employeedetails'); ?>">Employee Data</a></li>
                                   	<?php } ?>
                                </ul>
                            </li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Attendance Analysis Report', ACTION_VIEW)) { ?>
                        	<li class='dropdown-submenu'>
                            <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Attendance Analysis</a>
                            <ul class="dropdown-menu">
                            	<?php if($acl->checkPermission('Attendance Analysis Report', ACTION_VIEW)) { ?>
                            		<li><a class="blockanchor" href="<?php echo $this->baseUrl('report/attendancestats'); ?>">Statistics</a></li>
                                <?php } ?>
                                <?php if($acl->checkPermission('Attendance Detailed Report', ACTION_VIEW)) { ?>
                                	<li><a class="blockanchor" href="<?php echo $this->baseUrl('report/attendancedetails'); ?>">Attendance Details</a></li>
                                <?php } ?>
                            </ul>
                       	</li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Benefits Analysis Report', ACTION_VIEW)) { ?>
                        	<li class='dropdown-submenu'>
                            <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Benefits</a>
                            <ul class="dropdown-menu">
                            	<?php if($acl->checkPermission('Benefits Analysis Report', ACTION_VIEW)) { ?>
                                	<li><a class="blockanchor" href="<?php echo $this->baseUrl('report/benefitstats'); ?>">Statistics</a></li>
                                <?php } ?>
                                <?php if($acl->checkPermission('Benefits Detailed Report', ACTION_VIEW)) { ?>
                                	<li><a class="blockanchor" href="<?php echo $this->baseUrl('report/benefitdetails'); ?>">Benefits Report</a></li>
                                <?php } ?>
                            </ul>
                       	</li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Payroll', ACTION_LIST)) { ?>
                            <li class='dropdown-submenu'>
                                <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Payroll</a>
                                <ul class="dropdown-menu">
                                    <?php if($acl->checkPermission('Payroll', ACTION_CREATE)) { ?>
                                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('payroll/list'); ?>">Generate Payroll</a></li>
                                    <?php } ?>
                                    <?php if($acl->checkPermission('Payroll', ACTION_LIST)) { ?>
                                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('payroll/history'); ?>">Payroll History</a></li>
                                    <?php } ?>
                                    <?php if($acl->checkPermission('Payslips', ACTION_VIEW)) { ?>
                                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/payslips'); ?>">Payslips</a></li>
                                    <?php } ?>
                                    <?php if($acl->checkPermission('Bank Credit Instructions', ACTION_VIEW)) { ?>
                                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/bankadvice'); ?>">Bank Credit Instructions</a></li>
                                    <?php } ?>    
                                    <?php if($acl->checkPermission('Tax Remittance', ACTION_VIEW)) { ?>
                                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/paye'); ?>">Tax Remittance</a></li>
                                    <?php } ?>
                                    <?php if($acl->checkPermission('Insurance Remittance', ACTION_VIEW)) { ?>
                                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/nssf'); ?>">Insurance Remittance</a></li>
                                    <?php } ?>
                                </ul>
                            </li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Leave Analysis Report', ACTION_VIEW)) { ?>
                        	<li class='dropdown-submenu'>
                            <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Leave</a>
                            <ul class="dropdown-menu">
                            	<?php if($acl->checkPermission('Leave Analysis Report', ACTION_VIEW)) { ?>
                            		<li><a class="blockanchor" href="<?php echo $this->baseUrl('report/leavestats'); ?>">Statistics</a></li>
                                <?php } ?>
                                <?php if($acl->checkPermission('Leave Accruals Report', ACTION_VIEW)) { ?>
                                	<li><a class="blockanchor" href="<?php echo $this->baseUrl('report/leavedetails'); ?>">Leave Accrual Report</a></li>
                                <?php } ?>
                            </ul>
                       	</li>
                        <?php } ?>
                        <?php if($acl->checkPermission('Audit Trail Report', ACTION_VIEW)) { ?> 
                            <li class='dropdown-submenu'>
                                <a href="#" data-toggle="dropdown" class='dropdown-toggle'>System</a>
                                <ul class="dropdown-menu">
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('report/audittrail'); ?>">Audit Trail</a></li>
                                </ul>
                            </li>
                        <?php } ?>
                   	</ul>
              	</li>
            <?php } ?>
            <?php if(isAdmin() || isCompanyAdmin()) { ?>
                <li class="<?php echo in_array($controller, array('config','role','department')) ? 'active' : ''; ?>">
                    <a href="#" data-toggle="dropdown" class='dropdown-toggle'><span>Administration</span><span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('department/list'); ?>">Departments</a></li>
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/variables/type/7'); ?>">Job Positions</a></li>
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/variables/type/6'); ?>">Contract Types</a></li>
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/shifts'); ?>">Work Shifts</a></li>
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/variables/type/9'); ?>">Benefits Categories</a></li>
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/leave'); ?>">Leave Categories</a></li>
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('document/list'); ?>">Manage Documents</a></li>
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/variables/type/14'); ?>">Document Types</a></li>
                        <?php if(isAdmin()) { ?>
                        <li class='dropdown-submenu'>
                            <a href="#" data-toggle="dropdown" class='dropdown-toggle'>More Categories</a>
                            <ul class="dropdown-menu">
                            	<li><a class="blockanchor" href="<?php echo $this->baseUrl('config/variables/type/3'); ?>">Marital Status Values</a></li>
                                <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/variables/type/5'); ?>">Next of Kin Values</a></li>
                                <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/variables/type/2'); ?>">Salutation Values</a></li>
                                <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/variables/type/2'); ?>">Industry Categories</a></li>
                            </ul>
                       	</li>
                        <?php } ?>
                        <?php if ($acl->checkPermission('User Account', ACTION_LIST)) { ?>
                        	<li><a class="blockanchor" href="<?php echo $this->baseUrl('profile/list'); ?>">System Users</a></li>
                        <?php } ?>
                        <?php if ($acl->checkPermission('Role', ACTION_LIST) && isAdmin()) { ?>
                            <li><a class="blockanchor" href="<?php echo $this->baseUrl('role/list'); ?>">User Roles</a></li>
                        <?php } ?>
                        <?php if ($acl->checkPermission('Company', ACTION_VIEW)) { ?>
                        	<li><a href="<?php echo $this->baseUrl('company/view/id/'.encode($companyid)); ?>">Company Settings</a></li>
                        <?php } ?>
                        <?php if ($acl->checkPermission('Company', ACTION_LIST)) { ?>
                        	<li class='dropdown-submenu'>
                            	<a href="#" data-toggle="dropdown" class='dropdown-toggle'>Manage Companies</a>
                                <ul class="dropdown-menu">
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('company/list'); ?>">All Companies</a></li>
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('company/list/status/2'); ?>">Companies For Approval</a></li>
                                    <?php if ($acl->checkPermission('Company', ACTION_CREATE)) { ?>
                                    	<li><a class="blockanchor" href="<?php echo $this->baseUrl('company/index'); ?>">Setup New Company</a></li>
                                    <?php } ?>
                                </ul>
                          	</li>
                        <?php } ?>
                        <?php if(isAdmin()) { ?>
                            <li class='dropdown-submenu'>
                                <a href="#" data-toggle="dropdown" class='dropdown-toggle'>Global System Settings</a>
                                <ul class="dropdown-menu">
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/globalconfig/section/system/noleft/1'); ?>">Default Application Settings</a></li>
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/globalconfig/section/profile/noleft/1'); ?>">User Profile Settings</a></li>
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/globalconfig/section/uploads/noleft/1'); ?>">File upload Options</a></li>
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/globalconfig/section/notification/noleft/1'); ?>">Notification and Email Options</a></li>
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/globalconfig/section/sms/noleft/1'); ?>">SMS Settings
     </a></li>
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/globalconfig/section/backup/noleft/1'); ?>">Backup Settings</a></li>
                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('config/globalconfig/section/country/noleft/1'); ?>">Country Settings</a></li>
                                </ul>
                            </li>
                        <?php } ?>
                    </ul>
                </li>
            <?php } ?>    
        </ul>
        <div class="user">
            <ul class="icon-nav">
                <?php if(isLoggedIn()){ ?>
                    <li class='dropdown'>
                        <a href="#" class='dropdown-toggle' data-toggle="dropdown">
                            <i class="fa fa-envelope"></i>
                            <span class="label <?php echo $unread_messages == 0 ? 'label-lightgrey' : 'label-lightred'; ?>"><?php echo $unread_messages; ?></span>
                        </a>
                        <ul class="dropdown-menu pull-right message-ul">
                            <?php if($latestmsg->count() == 0){ ?>
                                <li><div class="alert alert-info">No new messages</div></li>
                                <li><a href="<?php echo $this->baseUrl('notifications/list'); ?>" class='more-messages'>Go to Message center<i class="fa fa-arrow-right"></i></a></li>
                            <?php } else { ?>
                                <?php
                                    foreach($latestmsg as $message){ 
                                        // debugMessage($reply_path);
                                       	$readclass = "read";
                                        $read_label = ' &nbsp;<span class="pagedescription" style="font-size:10px; position:absolute; right:12px; top:0; color:green;">(read)</span>';
                                        if(!$message->getMessageDetails()->hasReadMessage()){
                                            $readclass = "unread";
                                            $read_label = ' &nbsp;<span class="pagedescription" style="color:red; font-size:10px; position:absolute; right:12px; top:0;">(unread)</span>';
                                        }
										
                                        $message_title = "View message details";
                                        $reply_path = $this->baseUrl("notifications/view/id/".encode($message->getID()));
                                        
                                ?>
                                    <li class="makerelative <?php echo $readclass; ?>" style="font-weight:normal; padding-top:5px;">
										<?php if($message->getSenderID() == 1){ ?>
                                            <i class="fa fa-flag" style="font-size:32px; float:left; margin-left:5px;"></i>
                                        <?php } else { ?>
                                            <img src="<?php echo getImagePath($message->getSenderID(), $message->getSender()->getProfilephoto(), $message->getSender()->getGender()); ?>" style="width:38px; margin-left:5px; float:left;" />
                                        <?php } ?>
                                        <div class="details" style="margin-left:50px; padding-right:15px; height:auto;">
                                            <a href="<?php echo $reply_path; ?>">
                                                <?php if($message->getSenderID() == 1){ ?>
                                                    <div class="message bolded"><?php echo snippet($message->getSubject(), 30, ' ..'); ?></div>
                                                    <div class="message"><?php echo snippet($message->getContents(), 65, ' ...more'); ?></div>
                                                <?php } else { ?>
                                                    <div class="name bolded"><?php echo $message->getSender()->getName(); ?></div>
                                                    <div class="message"><?php echo snippet($message->getSubject(), 45, ' ...more'); ?></div>
                                                <?php } ?>
                                            </a>
                                        </div>
                                        <?php echo $read_label; ?>
                                    </li>
                                <?php } ?>
                                <li><a href="<?php echo $this->baseUrl('notifications/list'); ?>" class='more-messages'>Go to Message center<i class="fa fa-arrow-right"></i></a></li>
                            <?php } ?>                            
                        </ul>
                    </li>
                <?php } ?>
				<?php if($acl->checkPermission('System Variables', ACTION_EDIT) && !$istimesheetuser) { ?>
                    <li class="dropdown sett">
                        <a href="#" class='dropdown-toggle' data-toggle="dropdown">
                            <i class="fa fa-cog"></i>
                        </a>
                        <ul class="dropdown-menu pull-right theme-settings">
                            <li>
                                <span>Layout Options</span>
                                <div class="version-toggle">
                                    <a href="#" class="<?php echo $layout == 1 ? 'active' : ''; ?> set-fluid themetrigger" rel="1" type="layout">Fluid layout</a>
                                    <a href="#" class='<?php echo $layout == 2 ? 'active' : ''; ?> set-fixed themetrigger' rel="2" type="layout">Fixed layout</a>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <span>Topbar Position</span>
                                <div class="topbar-toggle">
                                    <a href="#" class="<?php echo $topbar == 1 ? 'active' : ''; ?> set-topbar-default themetrigger" rel="1" type="topbar">Default</a>
                                    <a href="#" class='<?php echo $topbar == 2 ? 'active' : ''; ?> set-topbar-fixed themetrigger' rel="2" type="topbar">Fixed</a>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <span>Sidebar Position</span>
                                <div class="sidebar-toggle">
                                    <a href="#" class="<?php echo $sidebar == 1 ? 'active' : ''; ?> set-sidebar-default themetrigger" rel="1" type="sidebar">Default</a>
                                 	<a href="#" class='<?php echo $sidebar == 2 ? 'active' : ''; ?> set-sidebar-fixed themetrigger' rel="2" type="sidebar">Fixed</a>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li class='dropdown colo'>
                        <a href="#" class='dropdown-toggle' data-toggle="dropdown">
                            <i class="fa fa-tint"></i>
                        </a>
                        <ul class="dropdown-menu pull-right theme-colors">
                            <li class="subtitle">Theme Settings</li>
                            <li id="colorswatch">
                                <span class="red" rel="red"></span>
                                <span class="orange" rel="orange"></span>
                                <span class="green" rel="green"></span>
                                <span class="brown" rel="brown"></span>
                                <span class="blue" rel="blue"></span>
                                <span class="lime" rel="lime"></span>
                                <span class="teal" rel="teal"></span>
                                <span class="purple" rel="purple"></span>
                                <span class="pink" rel="pink"></span>
                                <span class="magenta" rel="magenta"></span>
                                <span class="grey" rel="grey"></span>
                                <span class="darkblue" rel="darkblue"></span>
                                <span class="lightred" rel="lightred"></span>
                                <span class="lightgrey" rel="lightgrey"></span>
                                <span class="satblue" rel="satblue"></span>
                                <span class="satgreen" rel="satgreen"></span>
                            </li>
                        </ul>
                    </li>
                <?php } ?>
                <?php if(!isLoggedIn()){ ?>
                	<div class="divider5"></div>
                	<a href="<?php echo $this->baseUrl('user/login'); ?>" class='btn btn-large'><i class="fa fa-login"></i> Login</a>
                <?php } ?>
            </ul>
            <?php if(isLoggedIn()){ ?>
            <div class="dropdown">
                <a href="" class='dropdown-toggle' data-toggle="dropdown" >
                	<span class="hidden-xs" title="Logged in as <?php echo $loggedinuser->getName(); ?>">My Account</span>
                    <img class="hidden-xs" style="width:27px; height:27px;" src="<?php echo $loggedinuser->getMediumPicturePath(); ?>">
                    <button class="btn visible-xs"><i class="fa fa-user"></i></button>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('profile/view/id/'.encode($loggedinuser->getID())); ?>">My Profile</a></li>
                    <li class="divider"></li>
                    <?php if ($acl->checkPermission('User Account', ACTION_EDIT)) { ?>
                        <li><a class="blockanchor" href="<?php echo $this->baseUrl('profile/index/id/'.encode($loggedinuser->getID())); ?>">Update Profile</a></li>
                    <?php } ?>
                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('profile/view/id/'.encode($loggedinuser->getID()).'/tab/account'); ?>">Account Settings</a></li>
                    <li class="divider"></li>
                    <li><a href="<?php echo $this->baseUrl('user/logout'); ?>" class="blockanchor">Log Out</a></li>
                </ul>
            </div>
            <?php } ?>
        </div>
    </div>
</div>
