<div class="modal" id="dialog">
	<div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">title</h4>
        </div>
        <div class="modal-body clearfix" id="dialogbody">
        	<a id="loading" class="hidden"><img style="margin-left:50%;" src="<?php echo $this->baseUrl('images/loader.gif'); ?>" /></a>
        	<div id="dialogcontent"></div>
        </div>
        <div class="modal-footer">
   			<div id="new">
            	<a href="javascript:doNothing();" class="btn modelcancel" data-dismiss="modal" title="<?php echo $this->translate('global_button_cancel'); ?>"><?php echo $this->translate('global_button_cancel'); ?></a>
            	<button type="submit" class="btn btn-success" id="save" onclick="javascript:doNothing();"><?php echo $this->translate('global_button_save'); ?></button>
        	</div>
       		<div id="view" class="hide">
                <a href="javascript:doNothing();" class="btn modelcancel" data-dismiss="modal" title="<?php echo $this->translate('global_button_close'); ?>"><?php echo $this->translate('global_button_close'); ?></a>
                <button type="submit" class="btn btn-success" id="save" onclick="javascript:doNothing();"><?php echo $this->translate('global_button_edit'); ?></button>
            </div>
        </div>
      </div>
    </div>
</div>
<div id="dialog2" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">title</h4>
            </div>
            <div class="modal-body nopadding">
                <a id="loading" class="hidden"><img style="margin-left:50%;" src="<?php echo $this->baseUrl('images/loader.gif'); ?>" /></a>
        		<div id="dialogcontent"></div>
            </div>
            <div class="modal-footer">
                <div id="new">
                    <a href="javascript:doNothing();" class="btn modelcancel" data-dismiss="modal" title="<?php echo $this->translate('global_button_cancel'); ?>"><?php echo $this->translate('global_button_cancel'); ?></a>
                    <button type="submit" class="btn btn-success" id="save" onclick="javascript:doNothing();"><?php echo $this->translate('global_button_save'); ?></button>
                </div>
                <div id="view" class="hide">
                    <a href="javascript:doNothing();" class="btn modelcancel" data-dismiss="modal" title="<?php echo $this->translate('global_button_close'); ?>"><?php echo $this->translate('global_button_close'); ?></a>
                    <button type="submit" class="btn btn-success" id="save" onclick="javascript:doNothing();"><?php echo $this->translate('global_button_edit'); ?></button>
                </div>
            </div>
        </div>
    </div>
</div>
<a id="wait" class="hidden blocked centeralign"><img src="<?php echo $this->baseUrl('images/loader.gif'); ?>" /></a>
<div id="imgareaselectcontainer"></div>