<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$customurl = '';
	
	$toggled = $session->getVar('toggled');
	$toggledclass = '';
	// $toggled = 1;
	if($toggled == '1'){
		$toggledclass = ' toggled';
	}
	
	$istimesheetuser = false;
	if(isTimesheetEmployee()){
		$istimesheetuser = true;
	}
	$mytext = "";
	if($istimesheetuser){
		$mytext = "My ";
	}
?>
<div class="subnav">
    <div class="subnav-title">
        <a href="#" class='toggle-subnav'><i class="fa fa-angle-down"></i><span>Quick Links</span> </a>
    </div>
    <ul class="subnav-menu"> 
        <?php if ($acl->checkPermission('Attendance', ACTION_CREATE)) { ?>
            <li><a class="<?php echo $ischeckin ? 'alert-dialog gonowhere disabled' : 'addpopup'; ?>" href="<?php echo $this->baseUrl('timesheets/checkin/userid/'.encode($session->getVar('userid')).'/pgc/true'); ?>"  title="Check In" rel="Check In" id="checkin" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("timesheets/processattendance"); ?>" message="Already In!" submittext="Check-In Now" submiticon="arrow-right">Check In</a>
            </li>
        <?php } ?>
        <?php if ($acl->checkPermission('Timesheets', ACTION_CREATE)) { ?>
            <li><a class="addpopup" href="<?php echo $this->baseUrl('timesheets/request/userid/'.encode($session->getVar('userid')).'/pgc/true'); ?>"  title="Request Additional Time" rel="New Timesheet Request" formtitle="indexform" successurl="<?php echo $this->baseUrl('timesheets/attendance'); ?>" action="<?php echo $this->baseUrl("timesheets/processattendance"); ?>" submittext="Submit Timesheet">Add Timesheet</a></li>
        <?php } ?>
        <?php if($istimesheetuser) { ?>
            <li><a class="addpopup" href="<?php echo $this->baseUrl('ledger/request/userid/'.encode($session->getVar('userid')).'/pgc/true'); ?>"  title="Request Additional Benefit" rel="New Benefit Request" formtitle="indexform" successurl="<?php echo $this->baseUrl('ledger/list'); ?>" action="<?php echo $this->baseUrl("ledger/processrequest"); ?>" submittext="Submit Request">Request Benefit</a></li>
        <?php } ?>
        <?php if ($acl->checkPermission('Benefits', ACTION_CREATE) && !$istimesheetuser) { ?>
            <li><a class="addpopup" href="<?php echo $this->baseUrl('ledger/index/pgc/true'); ?>"  title="Add OneTime Benefit" rel="Add OneTime Benefit" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("ledger/create"); ?>">Add Benefit</a></li>
        <?php } ?>
        <?php if ($acl->checkPermission('Benefits', ACTION_APPROVE)) { ?>
             <li><a class="blockanchor" href="<?php echo $this->baseUrl('ledger/forapproval'); ?>">Requests for Approval</a></li>
        <?php } ?>
        <?php if ($acl->checkPermission('Leave', ACTION_CREATE) && !$acl->checkPermission('Leave', ACTION_APPROVE) && $loggedinuser->isPermanent()) { ?>
            <li><a class="blockanchor" href="<?php echo $this->baseUrl('leave/index'); ?>">Request Leave</a></li>
        <?php } ?>
        <?php if ($acl->checkPermission('User Account', ACTION_CREATE)) { ?>	
            <li><a class="blockanchor" href="<?php echo $this->baseUrl('profile'); ?>">New Employee</a></li>
        <?php } ?>
        
    </ul>
</div>
<div class="subnav">
	<div class="subnav-title ui-sortable-handle">
		<a class="toggle-subnav" href="#">
			<i class="fa fa-angle-down"></i>
			<span>Leave Taken</span>
		</a>
	</div>
	<div class="subnav-content">
		<div class="pagestats">
			<span class="left"></span>
			<span sparkbarcolor="#ff7f66" sparktype="bar" id="balance" class="spark"></span>
		</div>
	</div>
</div>
<div class="subnav">
	<div class="subnav-title ui-sortable-handle">
		<a class="toggle-subnav" href="#">
			<i class="fa fa-angle-down"></i>
			<span>Leave Available</span>
		</a>
	</div>
	<div class="subnav-content">
		<div class="pagestats">
			<span class="left"></span>
			<span sparkbarcolor="#ff7f66" sparktype="bar" id="balance" class="spark"></span>
		</div>
	</div>
</div>
<div class="subnav">
    <div class="subnav-title">
        <a href="#" class='toggle-subnav'>
            <i class="fa fa-angle-down"></i>
            <span>Today's Summary</span>
        </a>
    </div>
    <!--<ul class="subnav-menu">
    	<li>
            <a href="#">Time In</a>
        </li>
        <li>
            <a href="#">Time Out</a>
        </li>
        <li>
            <a href="#">Hours Worked</a>
        </li>
        <li>
            <a href="#">Benefits Received</a>
        </li>
        <li>
            <a href="#">Leave Accrued</a>
        </li>
    </ul>-->
</div>