        <?php 
			if($request->pdf == '1'){
				$pdf_html = ob_get_clean();
				// echo $pdf_html;
				
				$company = new Company();
				$company->populate(getCompanyID());
				$phone = '';
				if(!isEmptyString($company->getPhone())){
					$phone = '<span style="font-size: 12pt;">&#9742;</span>  Phone: '.$company->getPhone();
				}
				$logo = 'LOGO';
				if($company->hasProfileImage()){
					$logo = '<img id="profileimage" class="imagecontainer retina-ready noround" src="'.$company->getPicturePath().'" style="min-width:100px; max-width:130px;  height:auto; width:auto; max-height:100px;" />';
				}
				$html = '
				<html>
				<head>
					<title>'.$pagetitle.$browserappend.'</title>
					<style type="text/css">
						.fieldsetcontainer {
							border:solid 1px #428BCA;
							-webkit-border-radius: 4px;
							-moz-border-radius: 4px;
							border-radius: 4px;
							margin:0;
							margin-top:10px;
							margin-bottom:10px;
							padding:0; 
							display:inline-block; 
							background:none; 
							width:100%; 
							height:auto;
						}
						.fieldsetcontainer legend {
							margin:0;
							padding:0;
							display:inline-block;
							background:none; 
							line-height:16px; 
							width:auto; 
							font-size:15px; 
							line-height:16px; 
							margin-left:25px;
							padding-right:5px;
							border:none;
							font-weight:bold;
						}
						
						table.items {
							width: 100%;
							font-size: 12px; 
							border-collapse: collapse;
							margin: 10px;
						}
						table.dataitems {
							width: 100%;
							font-size: 12px; 
							border-collapse: collapse;
						}
						table.dataitems tr td {
							padding: 6px;
							font-size: 12px; 
						}
						table.dataitems tr td.firsttd {
							font-weight:bold;
							width:40%;
						}
						table.dataitems tr td.data {
							width:60%;
						}
						table.isbordered {
							border-bottom: 0.1mm solid #000000;
						}
						table.thinborder tbody tr td {
							border-bottom: 0.1mm solid #999999;
						}
						thead td.isbordered { 
							background-color: #EEEEEE;
							border: 0.1mm solid #000000;
							font-weight:bold;
						}
						td.borderedtd {
							border-left: 0.1mm solid #000000;
							border-right: 0.1mm solid #000000;
						}
						.rightalign {
							text-align:right;
						}
						tr.bolded td, .bolded {
							font-weight:bold;
						}
					</style>
				</head>
				<body>
					<!--mpdf
					<htmlpageheader name="myheader">
						<table width="100%">
							<tr>
								<td width="50%" style="text-align: left; vertical-align:top;">
									<span style="font-weight: bold; font-size: 24pt;">
										'.$logo.'
									</span>
								</td>
								<td width="50%" style="color:#000; text-align: right;">
									<span style="font-weight: bold; font-size: 14pt;">'.getCompanyName().'</span><br />
									'.$company->getFullAddress().'<br />'.$company->getCity().'<br />'.$phone.'
								</td>
							</tr>
						</table>
					</htmlpageheader>
					<htmlpagefooter name="myfooter">
						<div style="border-top: 1px solid #000000; font-size: 9pt; text-align: center; padding-top: 3mm; ">
							Page {PAGENO} of {nb}
						</div>
					</htmlpagefooter>
					<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
					<sethtmlpagefooter name="myfooter" value="on" />
					mpdf-->
				
					'.$pdf_html.'
				</body>
				</html>
				';
			}
		?>
        <?php if($request->pdf != '1'){ ?>
        </div>
    </div>
</div>
</body>
</html>
<?php } ?>
<?php 
if($request->pdf == '1' && isEmptyString($request->source)){
	
    # filename          
	$timestamp = time().rand(100, 5000);
	if($showpayslip){
		$timestamp = $payslip_pdfname;
	}
	$temp_file_pdf = ($timestamp).".pdf";
	$temp_file_html = ($timestamp).".html";
	$temp_file_doc = ($timestamp).".doc";
	$temp_file_txt = ($timestamp).".txt";
	
	# path to remote file
	$path = BASE_PATH.DIRECTORY_SEPARATOR."temp".DIRECTORY_SEPARATOR.$temp_file_pdf; // debugMessage('path '.$path);
	$path_html = BASE_PATH.DIRECTORY_SEPARATOR."temp".DIRECTORY_SEPARATOR.$temp_file_html;
	$relativepathtodocument = $this->serverUrl($this->baseUrl('temp/'.$temp_file_pdf));
	# save file to temp folder
	// file_put_contents($path_html, $pdf_html); // file_put_contents($path_doc, $pdf_html);
	
	try {
		$mpdfpath = BASE_PATH.DIRECTORY_SEPARATOR.'application'.DIRECTORY_SEPARATOR.'includes'.DIRECTORY_SEPARATOR.'mpdf'.DIRECTORY_SEPARATOR.'mpdf.php'; // debugMessage('pdf '.$mpdfpath);
		ini_set('memory_limit','128M');
		
		require_once($mpdfpath); 
		ob_get_clean();
		$mpdf = new mPDF('win-1252','A4','','',20,15,40,20,10,10); 
		$mpdf->useOnlyCoreFonts = true;    // false is default
		$mpdf->SetProtection(array('print'));
		$mpdf->SetTitle($title.$browserappend);
		$mpdf->SetAuthor(getAppName());
		$mpdf->SetWatermarkText(getCompanyName());
		$mpdf->showWatermarkText = true;
		$mpdf->watermark_font = 'DejaVuSansCondensed';
		$mpdf->watermarkTextAlpha = 0.1;
		$mpdf->SetDisplayMode('fullpage');
		$mpdf->WriteHTML($html);
		$mpdf->Output($path); 
		if(isEmptyString($request->source)){
			$mpdf->Output($temp_file_pdf, 'I'); 
		}
		/*// $mpdf->Output($path, F);*/
	} catch (Exception $e) {
		debugMessage('error '.$e->getMessage());
	}
	// exit;
} else {
	echo encode($html);
	// echo '<span>Test</span>';
}
?>
