<?php if($request->pdf != '1'){ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
    <title><?php echo $controller == 'profile' && $action ==  'view' ? $pagetitle.$browserappend : $title.$browserappend; ?></title>
    <?php 
		$baseurl_bootstrap = $this->serverUrl($this->baseUrl('stylesheets/bootstrap.min.css'));
		$baseurl_bootstrap_code = file_get_contents($baseurl_bootstrap);
		
		$baseurl_btheme = $this->serverUrl($this->baseUrl('stylesheets/bootstrap-theme.min.css'));
		$baseurl_btheme_code = file_get_contents($baseurl_btheme);
		
		$baseurl_style = $this->serverUrl($this->baseUrl('stylesheets/style.css'));
		$baseurl_style_code = file_get_contents($baseurl_style);
		
		$baseurl_custom = $this->serverUrl($this->baseUrl('stylesheets/custom.css'));
		$baseurl_custom_code = file_get_contents($baseurl_custom);
		
		$baseurl_app = $this->serverUrl($this->baseUrl('stylesheets/app.css'));
		$baseurl_app_code = file_get_contents($baseurl_app);
		// debugMessage($baseurl_bootstrap_code);
	?>
    <style type="text/css">
		<?php echo $baseurl_bootstrap_code.$baseurl_btheme_code.$baseurl_style_code.$baseurl_custom_code.$baseurl_app_code; ?>
		
		.edit, .requiredmark, .save_trigger, .cancel_trigger {
			display:none;
		}
		body.print #headercontainer, body.print #sidebar, body.print .breadcrumbs, body.print .pageheader, body.print #tabs #left, body.print .hideonprint {
			display:none;
		}
		body.print .showonprint {
			display:block;
		}
		body.print div.controls, body.print .nullifempty {
			display:inline-block;
		}
		p.view {
			display:inline-block;
			margin-top:0;
		}
		/* Based on The MailChimp Reset INLINE: Yes. */  
		/* Client-specific Styles */
		#outlook a {padding:0;} /* Force Outlook to provide a "view in browser" menu link. */
		body{width:100% !important; -webkit-text-size-adjust:100%; -ms-text-size-adjust:100%; margin:0; padding:0; font-size: 12px !important;} 
		/* Prevent Webkit and Windows Mobile platforms from changing default font sizes.*/ 
		.ExternalClass {width:100%;} /* Force Hotmail to display emails at full width */  
		.ExternalClass, .ExternalClass p, .ExternalClass span, .ExternalClass font, .ExternalClass td, .ExternalClass div {line-height: 100%;}
		/* Forces Hotmail to display normal line spacing.  More on that: http://www.emailonacid.com/forum/viewthread/43/ */ 
		#backgroundTable {margin:0; padding:0; width:100% !important; line-height: 100% !important;}
		/* End reset */

		/* Some sensible defaults for images
		Bring inline: Yes. */
		img {outline:none; text-decoration:none; -ms-interpolation-mode: bicubic;} 
		a img {border:none;} 
		.image_fix {display:block;}

		/* Yahoo paragraph fix
		Bring inline: Yes. */
		p {margin: 1em 0;}
		p.view {
			margin-top:0;
		}

		/* Hotmail header color reset
		Bring inline: Yes. */
		h1, h2, h3, h4, h5, h6 {color: black !important;}

		h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {color: blue !important;}

		h1 a:active, h2 a:active,  h3 a:active, h4 a:active, h5 a:active, h6 a:active {
		color: red !important; /* Preferably not the same color as the normal header link color.  There is limited support for psuedo classes in email clients, this was added just for good measure. */
		}

		h1 a:visited, h2 a:visited,  h3 a:visited, h4 a:visited, h5 a:visited, h6 a:visited {
		color: purple !important; /* Preferably not the same color as the normal header link color. There is limited support for psuedo classes in email clients, this was added just for good measure. */
		}

		/* Outlook 07, 10 Padding issue fix
		Bring inline: No.*/
		table td {border-collapse: collapse;}

		/* Remove spacing around Outlook 07, 10 tables
		Bring inline: Yes */
		table { border-collapse:collapse; }

		.tab-content.printscreen, .box.box-bordered.box-color .box-content.printscreen {
			border:none;
			font-family: Arial, Verdana, sans-serif;
		}
		
    </style>
</head>    
<body class="print DTTT_Print">
    <div id="container-fluid" style="max-width:800px; margin:0 auto !important;">
        <div id="contentcontainer" class="container-fluid">
            <div id="centercolumn" class="container-fluid padding0">
                <div id="print_page_action_buttons" class="showonprint centeralign">
					<?php if($request->pdf != 1){ ?>
                        <a title="Close Window" onClick="window.close()" href="javascript: void(0)">Close</a> &nbsp;
                        <a title="Print" onClick="window.print()" href="javascript: void(0)" class="print" >Print</a> &nbsp; 
                    <?php } ?>
                    <?php if($request->pdf != 1){ ?>
                        <a title="PDF" href="<?php echo stripUrl($this->viewurl).'/pdf/1'; ?>" target="_blank" class="pdf">PDF</a> &nbsp; 
                    <?php } ?>
                </div>
                <?php } ?>
                <?php 
					if($request->pdf == '1'){
						ob_start();
					}
				?>
            	