<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/datepicker/bootstrap-datepicker.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/timepicker/bootstrap-timepicker.min.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/chosen/chosen.jquery.min.js')); ?>"></script>
<script type="text/javascript">
$(document).ready(function() {
	$('.ordinary').datepicker({
		format: 'M dd, yyyy',
		autoclose: true
	});
	
	// global styles independent of any jquery plugins come at the top followed by plugin styles 
	$(".readonly").each(function(){
		$(this).attr('readonly','readonly');
	});
	$(".disabledfield").each(function(){
		$(this).attr('readonly', true).attr('disabled', true);
	});
	
	$('.timepicker').timepicker({
		minuteStep: 5
	});
	
	$(".chosen-select").chosen();
	// default search text on chosen dropdown
	$(".chosen-container .chosen-search input").attr('placeholder', 'Type to search');
});
</script>
<style>
.datepicker, .bootstrap-timepicker-widget.open {
    z-index:5051 !important;
}
</style>