<link href='<?php echo $this->baseUrl('stylesheets/plugins/datepicker/datepicker.css'); ?>' rel='stylesheet' type='text/css'>
<link href='<?php echo $this->baseUrl('stylesheets/plugins/timepicker/bootstrap-timepicker.min.css'); ?>' rel='stylesheet' type='text/css'>
<link href='<?php echo $this->baseUrl('stylesheets/plugins/chosen/chosen.css'); ?>' rel='stylesheet' type='text/css'>
<link href='<?php echo $this->baseUrl('stylesheets/custom.css'); ?>' rel='stylesheet' type='text/css'>
<link href='<?php echo $this->baseUrl('stylesheets/app.css'); ?>' rel='stylesheet' type='text/css'>

<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/bootstrap.min.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/datepicker/bootstrap-datepicker.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/timepicker/bootstrap-timepicker.min.js')); ?>"></script>
