<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$message = new Message();
	
	$defaultusers = "";
	if(!isEmptyString($request->userid)){
		$user = new UserAccount();
		$user->populate(decode($request->userid));
		$defaultusers = array($user->getID());
	}
	
	$posturl = $this->baseUrl("notifications/processnotification");
	$type = $request->type;
	$ismail = true; $issms = false;
	if(isEmptyString($type)){
		$type = 1;
	}
	if($type == 2){
		$issms = true; $ismail = false;
	}
	
	if($ismail){
		$subtitle = "Compose Message";
		$button_title = "Send Message";
		$emailusers = getUsersWithEmail();
	}
	if($issms){
		$subtitle = "Compose SMS";
		$button_title = "Send SMS";
		$phoneusers = getUsersWithPhone();
	}
	
	$subject = ''; $message = '';
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$formvalues = $session->getVar(FORM_VALUES);		
		$subject = isArrayKeyAnEmptyString('subject', $formvalues) ? '' : $formvalues['subject'];
		$message = isArrayKeyAnEmptyString('message', $formvalues) ? '' : $formvalues['message'];
	}
	
	$listurl = $this->baseUrl('notifications/list'); 
	$title = "Message Center";
	$pageid = "notification_index_".$type;
	$description = '';	
	$icon = 'glyphicon glyphicon-envelope';
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'Messaging / Compose'; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
	
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			subject: "required",
			contents: "required",
			memberids: "required"
		}, 
		// the messages for each of the fields being validated
		messages: {				
			subject: "<?php echo $this->translate("message_subject_error"); ?>",
			contents: "<?php echo $this->translate("message_contents_error"); ?>",
			memberids: "Atleast one receipient required"
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					if(element.hasClass("useid_error")){
						error.appendTo("#"+element.attr("id")+"_error");
					} else {
						error.appendTo("#"+element.attr("name")+"_error");
					}
					break;
			}			
		},
		ignore: ":hidden:not(select)"
	});
	
	<?php if($issms){ ?>
		var characters = 159;
		$("#balance").append(characters);
		$("#contents").keyup(function(){
			if($(this).val().length > characters){
				$(this).val($(this).val().substr(0, characters));
			}
			var remaining = characters -  $(this).val().length;
			$("#balance").html(remaining);
			if(remaining <= 10){
				$("#balance").css("color","red");
			} else {
				$("#balance").css("color","black");
			}
		});
	<?php } ?>
	$("#contents").trigger("keyup");
	
	multipleDisableContainerByID('allusers_list');
	enableContainerByID('selectuser_list');
	$('#selectuser').click(function(){
		enableContainerByID('selectuser_list');
		multipleDisableContainerByID('allusers_list');
	});
	$('#allusers').click(function(){
		enableContainerByID('allusers_list');
		multipleDisableContainerByID('selectuser_list');
	});
	
});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div id="<?php echo $pageid; ?>">
	<div class="row">
		<div class="col-sm-8">
        	<div class="box box-color box-bordered box-condensed">
                <div class="box-title">
                    <h3><i class="fa fa-th-list"></i> <?php echo $subtitle; ?></h3>
                    <div class="actions" style="margin-top:5px;">
                        <a class="btn-sm " title="Message Center" href="<?php echo $listurl; ?>">Back to Inbox</a> &nbsp;
                    </div>
                </div>
                <div class="box-content nopadding"> 
                	<form id="indexform" class="form-horizontal row-border" action="<?php echo $posturl; ?>" method="post">
                    	<div class="row-fluid">
                            <div class="col-sm-12" style="padding:20px;">
                                <input type="hidden" id="senderemail" name="senderemail" value="<?php echo $loggedinuser->getEmail(); ?>" />
                                <input type="hidden" id="sendername" name="sendername" value="<?php echo $loggedinuser->getName(); ?>" />
                                <div class="form-group">
                                    <label class="col-sm-3 control-label">Recipient(s): <?php echo $this->translate("required_field_marker"); ?></label>
                                    <div class="col-sm-6">
                                   		<div class="blocked" style="margin-left:0;">
                                            <label class="radio radio-inline"><input type="radio" class="" name="selecttype" id="selectuser" value="2" checked="checked" /> Select User(s)</label>
                                            <label class="radio radio-inline"><input type="radio" class="" name="selecttype" id="allusers" value="4" /> All Users</label>
                                        </div>
                                    </div>
                                    <div class="divider10"></div>
                                    <div class="col-sm-12">
                                        <div id="selectuser_list">
										<?php if($ismail){ ?>
                                            <?php
                                                  $listdropdown = new Zend_Form_Element_Multiselect('userids',
                                                          array(
                                                                  'multiOptions' => $emailusers,
                                                                  'view' => new Zend_View(),
                                                                  'decorators' => array(array('ViewHelper')),
                                                                  'class' => array('chosen-select','multipleselect','col-sm-6'),
                                                                  'style' => 'width:100%;'
                                                          )
                                                  );
                                                  
                                                  $listdropdown->setValue($defaultusers);
                                                  $listdropdown->setAttrib("data-placeholder", "Start typing user(s) in category");
                                                  echo $listdropdown->render();
                                              ?>
                                          <?php } ?>
                                          <?php if($issms){ ?>
                                              <?php
                                                  $listdropdown = new Zend_Form_Element_Multiselect('userids',
                                                          array(
                                                                  'multiOptions' => $phoneusers,
                                                                  'view' => new Zend_View(),
                                                                  'decorators' => array(array('ViewHelper')),
                                                                  'class' => array('chosen-select','multipleselect','col-sm-6'),
                                                                  'style' => 'width:100%;'
                                                          )
                                                  );
                                                  
                                                  $listdropdown->setValue('');
                                                  $listdropdown->setAttrib("data-placeholder", "Start typing user(s) in category");
                                                  echo $listdropdown->render();
                                              ?>
                                          <?php } ?>
                                        </div>
                                        <div id="allusers_list" class="xbolded">
                                            All users with <?php echo $issms === true ? 'Phone' : 'Email'; ?> (<?php echo $issms == true ? count($phoneusers) : count($emailusers); ?>) will be notified
                                        </div>
                                  	</div>
                            	</div>
                                <?php if($ismail){ ?>
                                    <div class="form-group">
                                        <label class="col-md-12 control-label"><?php echo $this->translate("message_subject_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></label>
                                        <div class="col-md-12">
                                            <input type="text" name="subject" id="subject" class="form-control" placeholder="<?php echo $this->translate("message_subject_label"); ?>" value="<?php echo $subject; ?>" />
                                            <input type="hidden" name="subject_prefill" id="" value="<?php echo $subject; ?>" />
                                            <div id="subject_error"></div>
                                        </div>
                                    </div>
                                <?php } ?>
                                <div class="form-group">
                                    <label class="col-md-12 control-label"><?php echo $this->translate("message_contents_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></label>
                                    <div class="col-md-12">
                                        <?php if($ismail){ ?>
                                            <textarea class="expanding form-control elastic" name="contents" id="contents" style="min-height:240px;" placeholder="Type message here"><?php echo $message; ?></textarea>
                                        <?php } ?>
                                        <?php if($issms){ ?>
                                            <textarea class="expanding form-control elastic" name="contents" id="contents" style="min-height:150px; width:300px;" placeholder="Type message here. Maximum 159 Characters"><?php echo $message; ?></textarea>
                                            <input type="text" style="display:none;" id="spamcheck" name="spamcheck" value="" />
                                            <span class="blocked">Chars Left: &nbsp;<label id="balance"></label></span>
                                        <?php } ?>
                                        <div id="contents_error" class="clearfix blocked"></div>
                                    </div>
                                </div>
                                <div class="form-group">
                                	<div class="col-md-12">
                                        <button type="submit" class="btn btn-success button-submit save savebutton" name="save" id="send"><?php echo $button_title; ?></button>
                                        <input type="hidden" id="senderid" name="senderid" value="<?php echo $loggedinuser->getID(); ?>" />
                                        <input type="hidden" id="type" name="type" value="<?php echo $type; ?>" />
                                        <input type="hidden" id="successurl" name="successurl" value="<?php echo encode($this->baseUrl('notifications/index/type/'.$type)); ?>" />
                                    </div>
                                </div>
                                <div class="form-group" style="padding:20px;">
                                    <div class="col-md-12 padding0"><?php echo $session->getVar('sentlist'); ?></div>
                                </div>
                          	</div>
                      	</div>
                    </form>
                </div>
          	</div>
    	</div>
   	</div>
</div>    
<?php
	$session->setVar('sentlist', '');
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
