<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$user = new UserAccount();
	$user->populate($userid);
	
	$message = new MessageRecipient();
	$message->populate(decode($request->id)); // debugMessage($message->toArray()); exit;	
	$reply_recepient = $message->getMessage()->getSenderID();
	
	# check if message has not been marked as read/seen
	if(!$message->hasReadMessage() && $userid == $message->getRecipientID()){
		$message->markAsRead(array($message->getID()), 1);
	}
	
	$listurl = $this->baseUrl('notifications/list'); 
	$title = "Message Center";
	$description = '';	
	$icon = 'glyphicon glyphicon-envelope';
	$pageid = "notification_view";
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'Message Center / View Message'; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
	
});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div id="<?php echo $pageid; ?>">
	<div class="row">
		<div class="col-sm-8">
        	<div class="box box-color box-bordered box-condensed">
                <div class="box-title">
                    <h3><i class="fa fa-th-list"></i> Subject: <?php echo $message->getMessage()->getSubject(); ?></h3>
                    <div class="actions" style="margin-top:5px;">
                        <a class="btn-sm " title="Message Center" href="<?php echo $listurl; ?>">Back to Inbox</a> &nbsp;
                        <?php if ($acl->checkPermission('Message', ACTION_DELETE)) { ?>
                        	<a class="btn-sm deleteline gonowhere" action="<?php echo $this->baseUrl('index/delete/id/'.encode($message->getID())."/entityname/MessageRecipient/successurl/".encode($listurl)); ?>" message="<?php echo $this->translate('global_delete_confirm_message_nonote'); ?>" title="Delete Entry">Delete</a>&nbsp;
                        <?php } ?>
                    </div>
                </div>
                <div class="box-content nopadding">    
                	<div class="panel-body well-sm">
                        <div class="row-fluid marginleft5">
                            <div class="col-sm-2 centeralign">
                                <div class="divider10"></div>
                                <?php if($message->getMessage()->getSenderID() == 1 && $message->getMessage()->getType() != 'notification'){ ?>
                                    <i class="fa fa-flag" style="font-size:80px; float:left; margin-left:5px;"></i>
                                <?php } else { ?>
                                    <img style="width:120px;" class="imagecontainer" src="<?php echo $message->getMessage()->getSender()->getMediumPicturePath(); ?>" />
                                    <div class="divider10"></div>
                                	<span style="font-size:11px;"><?php echo $message->getMessage()->getSender()->getName(); ?></span>	
                                <?php } ?>
                            </div>
                            <div class="col-sm-10" style="padding-right:50px; padding-left:50px;">
                                <div class="divider15"></div>
                                <div class="col-sm-12 padding0"><p style="margin-bottom:10px;">
									<?php echo nl2br($message->getMessage()->getContents()); ?>
                                    <?php //echo $message->getMessage()->getHTML(); ?>
                                </div>
                                <div class="divider10"></div>
                                <div class="col-sm-12 padding0" style="font-size:10px;">Sent on <?php echo date('m/d/Y - g:i A', strtotime($message->getMessage()->getDateCreated())); ?></div>
                            </div>
                        </div>
                    </div>
                </div>
          	</div>
        </div>
	</div>
</div>            
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
