<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$leave = new Leave();
	$id = decode($request->id);
	$resource = "Leave";
	$description = '';
	$icon = "fa fa-clock";
	
	if(isEmptyString($request->id)){
		$pagetitle = 'Request Leave';
		$button_title = "Submit for Approval"; 
		$successmessage = "Successfully submitted for approval";
		$posturl = $this->baseUrl("leave/create");
		$leave->setStatus('0');
		$leave->setDuration('');
		$leave->setDurationType('2');
		$leave->setUserID($loggedinuser->getID());
		if(isAdmin() || $acl->checkPermission($resource, ACTION_APPROVE)){
			$leave->setUserID('');
			$button_title = "Save"; 
		}
		if(!isEmptyString($request->userid)){
			$leave->setUserID($request->userid);
		}
		$leave->setTypeID('1');
		if(!isEmptyString($request->typeid)){
			$leave->setTypeID($request->typeid);
		}
		$leave->setStartTime('08:00');
		$leave->setEndTime('17:00');
		$leave->setReturnTime('08:00');
	} else {
		$leave->populate(decode($request->id));
		$pagetitle = 'Update Request';
		$button_title = "Update and Request Approval";
		$successmessage = "Successfully updated";
		$posturl = $this->baseUrl("leave/create");
		if($leave->getUserID() == $loggedinuser->getID()){
			$leave->setStatus('0');
			$successmessage = "Successfully updated and pending approval";
		}
		if(isAdmin() || $acl->checkPermission($resource, ACTION_APPROVE)){
			$button_title = "Save Changes"; 
		}
	}
	
	$successurl = $this->baseUrl('leave/view');
	$addnewsuccessurl = $this->baseUrl('leave/index');
	$failureurl = $this->viewurl;
	
	// $hoursavailable = '16';
	$hoursavailable = getHoursAvailable($leave->getUserID(), $leave->getTypeID(), getYearStart(), getYearEnd()); //debugMessage($hoursavailable);
	$daysavailable = $hoursavailable == 0 ? 0 : formatNumber($hoursavailable/getHoursInDay()); // debugMessage($daysavailable);
		
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$leave->processPost($session->getVar(FORM_VALUES));	
	}
	
	$pageid = "leave_index";
	$leaves = getLeaveTypes();
	$title = 'Leave Requests';
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.$title.' / '.$pagetitle; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
	
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			typeid: "required",
			userid: "required",
			startdate: "required",
			starttime: "required",
			enddate: "required",
			endtime: "required",
			returndate: "required",
			returntime: "required",
			duration: {
				required: true,
				notime_validation: true,
				min_validation: true,
				duration_validation: true,
				wholenumber_validation: true
			},
			status: "required"
		}, 
		// the messages for each of the fields being validated
		messages: {		
			typeid: "Please select a Type",
			userid: "Please select an Employee",
			startdate: "Please select a Date",
			starttime: "Please select Time",
			enddate: "Please select a Date",
			endtime: "Please select Time",
			returndate: "Please select a Date",
			returntime: "Please select Time",
			duration: {
				required: "Please enter Hours",
			},
			status: "Please select current Status"
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					if(element.hasClass("useid_error")){
						error.appendTo("#"+element.attr("id")+"_error");
					} else {
						error.appendTo("#"+element.attr("name")+"_error");
					}
					break;
			}			
		},
		ignore: ":hidden:not(select)"
	});
	
	// validate that hours are available
	$.validator.addMethod("notime_validation", function(value, element) {            
		var duration = value; 
		var durationtype = $('[name=durationtype]:checked').val();  // alert(durationtype);
		var availablehrs = '<?php echo $hoursavailable; ?>';  
		var availabledays = '<?php echo $daysavailable; ?>';  
		if(durationtype == 1 && parseFloat(availablehrs) == 0){
			return false;
		}
		if(durationtype == 2 && parseFloat(availabledays) == 0){
			return false;
		}
		return true;        
	}, "No accrued time available");
	
	// validate minimum
	$.validator.addMethod("min_validation", function(value, element) {            
		var duration = value; 
		var durationtype = $('[name=durationtype]:checked').val();  // alert(durationtype);
		var availablehrs = '<?php echo $hoursavailable; ?>';  
		var availabledays = '<?php echo $daysavailable; ?>';  
		if(durationtype == 1 && parseInt(duration) == 0){
			return false;
		}
		if(durationtype == 2 && parseInt(duration) == 0){
			return false;
		}
		return true;        
	}, "Minimum allowed is <?php echo getHoursInDay(); ?> Hours (1 Day) ");
	
	// validate that user can not request more than is available
	$.validator.addMethod("duration_validation", function(value, element) {            
		var duration = value; 
		var durationtype = $('[name=durationtype]:checked').val();  // alert(durationtype);
		var availablehrs = '<?php echo $hoursavailable; ?>';  
		var availabledays = '<?php echo $daysavailable; ?>';  
		if(durationtype == 1 && parseInt(duration) > parseInt(availablehrs)){
			return false;
		}
		if(durationtype == 2 && parseInt(duration) > parseInt(availabledays)){
			return false;
		}
		return true;        
	}, "Should be less than <?php echo $hoursavailable.' Hours ('.$daysavailable.' Days)'; ?>");
	
	// validate that a whole number is being requested
	$.validator.addMethod("wholenumber_validation", function(value, element) {            
		var duration = value; 
		var durationtype = $('[name=durationtype]:checked').val();  // alert(durationtype);
		var availablehrs = '<?php echo $hoursavailable; ?>';  
		var availabledays = '<?php echo $daysavailable; ?>';  
		var hoursinday = '<?php echo getHoursInDay(); ?>'; // alert(parseInt(duration) % parseInt(hoursinday))
		if(durationtype == 1 && parseInt(duration) % parseInt(hoursinday) != 0){
			return false;
		}
		return true;        
	}, "Should be multiple of <?php echo getHoursInDay(); ?> Hours or 1 Day");
	
	$("#typeid").change(function(){
		var url = '<?php echo stripURL($this->viewurl); ?>'; //alert(url);
		var currenttypeid = '<?php echo $leave->getTypeID(); ?>';
		
		var typeid = $(this).val();
		var newurl = '<?php echo stripURL($this->viewurl).'/typeid/'; ?>'+typeid; //alert(newurl);
		var striptxt = '/typeid/'+currenttypeid;
		var replacetxt = '/typeid/'+typeid;
		if(typeid != currenttypeid){
			newurl = newurl.replace(striptxt, ''); // alert(newurl);
			window.location.href = newurl
		}
	});
	
	$("#userid").change(function(){
		var url = '<?php echo stripURL($this->viewurl); ?>'; //alert(url);
		var currentuserid = '<?php echo $leave->getUserID(); ?>';
		
		var userid = $(this).val();
		var newurl = '<?php echo stripURL($this->viewurl).'/userid/'; ?>'+userid; //alert(newurl);
		var striptxt = '/userid/'+currentuserid;
		var replacetxt = '/userid/'+userid;
		if(isEmptyString(currentuserid)){
			window.location.href = newurl
		} else {
			if(userid != currentuserid){
				newurl = newurl.replace(striptxt, ''); // alert(newurl);
				window.location.href = newurl
			}
		}
	});
	
	<?php if($leave->getdurationtype() == 2){ ?>
		$("#durationtype_2").attr('checked', true);
		$("#durationtype_1").attr('checked', false);
	<?php } ?>
	<?php if($leave->getdurationtype() == 1){ ?>
		$("#durationtype_1").attr('checked', true);
		$("#durationtype_2").attr('checked', false);
	<?php } ?>
});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div id="<?php echo $pageid; ?>">
	<div class="row">
		<div class="col-sm-8">
        	<div class="box box-color box-bordered">
                <div class="box-title">
                    <h3><i class="fa fa-th-list"></i> <?php echo $pagetitle; ?></h3>
                </div>
                <div class="box-content nopadding">
                    <form class="form-horizontal form-bordered" action="<?php echo $posturl; ?>" method="post" id="indexform">
                        <input name="entityname" id="entityname" type="hidden" value="Leave" />
                        <input type="hidden" id="id" name="id" value="<?php echo encode($leave->getID()); ?>" />
                        <input type="hidden" id="status_old" name="status_old" value="<?php echo $leave->getStatus(); ?>" />
                        <input name="successmessage" id="successmessage" type="hidden" value="<?php echo $successmessage; ?>" />  
                        <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" /> 
                        <input type="hidden" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($successurl); ?>" /> 
                        <input type="hidden" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($failureurl); ?>" /> 
                        <?php if(isAdmin() || $acl->checkPermission($resource, ACTION_APPROVE)){ ?>
                            <div class="form-group">
                                <label class="col-sm-3 control-label"><?php echo $this->translate('leave_user_label'); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="col-sm-9">
                                    <?php if(isEmptyString($leave->getID())){ ?>
                                        <?php
                                            $allvalues = getUsers();
                                            $dropdown = new Zend_Form_Element_Select('userid',
                                                                array(
                                                                    'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
                                                                    'view' => new Zend_View(),
                                                                    'decorators' => array('ViewHelper'),
                                                                    'class' => array('form-control','input-sm','width200')
                                                                )
                                            );  
                                            $dropdown->setValue($leave->getUserID()); 
                                            echo $dropdown->render();
                                        ?>
                                    <?php } else { ?>
                                        <?php echo $leave->getUser()->getName(); ?>
                                        <input type="hidden" id="userid" name="userid" value="<?php echo $leave->getUserID(); ?>" />
                                    <?php } ?>
                                    <div id="userid_error"></div>
                                </div>
                            </div>
                        <?php } else { ?>
                            <input type="hidden" id="userid" name="userid" value="<?php echo $leave->getUserID(); ?>" />
                        <?php } ?>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('leave_typeid_label'); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-9">
                                <?php if(isEmptyString($leave->getID())){ ?>
                                    <?php
                                        $dropdown = new Zend_Form_Element_Select('typeid',
                                                            array(
                                                                'multiOptions' => $leaves,
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('form-control','input-sm','width200')
                                                            )
                                        );  
                                        $dropdown->setValue($leave->getTypeID()); 
                                        echo $dropdown->render();
                                    ?>
                                <?php } else { ?>
                                    <?php echo $leave->getType()->getName(); ?>
                                    <input type="hidden" id="typeid" name="typeid" value="<?php echo $leave->getTypeID(); ?>" />
                                <?php } ?>
                                </span>
                                <div id="typeid_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('leave_description_label'); ?>:</label>
                            <div class="col-sm-9">
                                <textarea class="form-control expanding" id="remarks" name="remarks"><?php echo $leave->getRemarks(); ?></textarea>
                                <div id="remarks_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"></label>
                            <div class="col-sm-9"></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Start Date: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control input-sm datefield readonly width100 ordinary" name="startdate" id="startdate" value="<?php echo changeMySQLDateToPageFormat($leave->getstartdate()); ?>" />
                                <div id="startdate_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Time Available:</label>
                            <div class="col-sm-9"><span class="width175 blocked bolded"><?php echo $hoursavailable.' Hours ('.$daysavailable.' Days) '; ?></span></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Time Requested: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-9">
                                <input type="text" name="duration" id="duration" class="form-control input-sm centeralign isdecimal bolded width100 inline floatleft" value="<?php echo $leave->getDuration(); ?>" /> &nbsp;
                                <label class="radio radio-inline"><input type="radio" name="durationtype" id="durationtype_2" class="" value="2" <?php echo $leave->getdurationtype() == '2' ? 'checked="checked"' : ''; ?> /> Days</label>
                                <label class="radio radio-inline" style="margin-left:20px;"><input type="radio" name="durationtype" id="durationtype_1" checked="checked" class="" value="1" <?php echo $leave->getdurationtype() == '1' ? 'checked="checked"' : ''; ?> /> Hours &nbsp;</label>
                                <div class="divider5"></div>
                                <span class="pagedescription bolded">Enter time in multiples of 1 day (<?php echo getHoursInDay(); ?> Hours)</span>
                                <div id="duration_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">End Date: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control input-sm datefield readonly width100 ordinary" name="enddate" id="enddate" value="<?php echo changeMySQLDateToPageFormat($leave->getenddate()); ?>" />
                                <span style="font-size:11px;color:#999;"></span>
                                <div class="divider5"></div>
                                <div id="enddate_error"></div><div id="endtime_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Return Date: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control input-sm datefield readonly width100 ordinary" name="returndate" id="returndate" value="<?php echo changeMySQLDateToPageFormat($leave->getreturndate()); ?>" />
                                <div id="returndate_error"></div>
                            </div>
                        </div>
                        <?php if(isAdmin() || $acl->checkPermission($resource, ACTION_APPROVE)){ ?>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Status: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="col-sm-9">
                                    <?php
										$leavestatuses = getLeaveStatuses();
										$dropdown = new Zend_Form_Element_Select('status',
															array(
																'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $leavestatuses),
																'view' => new Zend_View(),
																'decorators' => array('ViewHelper'),
																'class' => array('form-control','input-sm','width200')
															)
										);  
										$dropdown->setValue($leave->getStatus()); 
										echo $dropdown->render();
									?><div id="status_error"></div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-3 control-label">Leave Taken</label>
                                <div class="col-sm-9">
                                    <label class="checkbox check-inline" for="istaken"><input type="checkbox" id="istaken" name="istaken" <?php echo $leave->getStatus() == 5 ? 'checked="checked"' : ''; ?> class="form-control inline" value="1" title="Mark as Taken" style="width:auto; margin:0; margin-right:15px; height:18px;" /> &nbsp;&nbsp; &nbsp; Mark Leave as Taken</label>
                                </div>
                            </div>
                       	<?php } else { ?>
                        	<input type="hidden" id="status" name="status" value="<?php echo $leave->getStatus(); ?>" />
                        <?php } ?>
                        <div class="form-actions">
                            <a class="btn cancel gonowhere" type="button"><?php echo $this->translate('global_button_cancel'); ?></a>
                            <button class="btn btn-primary btn-green changesuccessurl savebutton" type="submit" successurl="<?php echo encode($successurl); ?>"><?php echo $button_title; ?></button>
                        </div>
                    </form>
               	</div>
         	</div>
      	</div>
 	</div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
