<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	$istimesheetuser = false;
	if(isTimesheetEmployee()){
		$istimesheetuser = true;
	}
	
	$title = "Leave Requests"; 
	
	$style = '2';
	if(!isEmptyString($request->style)){
		$style = $request->style;
		$session->setVar('style', $request->style);
	}
	if(isEmptyString($request->style) && !isEmptyString($session->getVar('style'))){
		$style = $session->getVar('style');
	}
	
	$leavetypes = getLeaveTypes();
	$leavestatuses = getLeaveStatuses();
	$leaveoptions = getHoursDaysDropdown();
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array());
	$paginate->setFilterColumns(array());	
	$paginate->setItemCountPerPage("50");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE t.id <> '' AND u.companyid = '".$companyid."' ";
	$allowclear = false;
	
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	if($istimesheetuser){
		$where_query .= " AND t.`userid` = '".$loggedinuser->getID()."' ";
	}
	$userid = $request->userid;
	if(!isEmptyString($userid)){
		$where_query .= " AND t.`userid` = '".$userid."' ";
		$allowclear = true;
		if($istimesheetuser){
			$allowclear = false;
		}
	}
	
	$typeid = $request->typeid;
	if(!isEmptyString($typeid)){
		$where_query .= " AND t.`typeid` = '".$typeid."' ";
		$allowclear = true;
	}
	
	if($request->forapproval == '1'){
		$request->setParam('status', 0);
	}
	if($request->whoisoff == '1'){
		$request->setParam('status', 3);
	}
	$status = trim($request->status);
	if(!isEmptyString($status)){
		
		if(!isArrayKeyAnEmptyString($status, $leavestatuses)){
			switch($status){
				case '0':
					$title = "Leave Requests for Approval";
					$where_query .= " AND t.`status` = '".$status."' ";
					break;
				case '1':
					$title = "Approved Requests";
					$where_query .= " AND t.`status` = '".$status."' ";
					break;
				case '2':
					$title = "Rejected Requests";
					$where_query .= " AND t.`status` = '".$status."' ";
					break;
				case '3':
					$title = "Currently Off";
					$where_query .= " AND (t.`status` = '".$status."' OR TO_DAYS('".date('Y-m-d')."') BETWEEN TO_DAYS(t.startdate) AND TO_DAYS(t.enddate)) ";
					break;
				case '4':
					$title = "Leave Taken";
					break;
				default:
					$where_query .= " AND t.`status` = '".$status."' ";
					break;
			}
		}
		$allowclear = true;
	}
	
	$order = trim($request->order);
	$order_query = " ORDER BY t.datecreated DESC, t.id desc ";
	
	$sortcolumn = $request->sortby;
	$sortorder = $request->sortorder;
	if(!isEmptyString($sortcolumn) && !isEmptyString($sortorder)){
		$order_query = " ORDER BY " . $sortcolumn. " " .$sortorder. " ";
	}
	
	$paginate->processPost($request->getParams());
	$all_results_query = "
		select t.id, t.userid, t.companyid, 
		IF(isnull(u.othername), concat(u.firstname,' ',u.lastname), concat(u.firstname,' ',u.lastname,' ',u.othername)) as `User`,
		IF(isnull(mc.othername), concat(mc.firstname,' ',mc.lastname), concat(mc.firstname,' ',mc.lastname,' ',mc.othername)) as addedby,
		IF(p.displayname <> '', p.displayname, concat(p.firstname, ' ', p.lastname, ' ', p.othername)) as approver,
		t.startdate, t.enddate, t.starttime, t.endtime, t.returndate, t.returntime, t.createdby AS createdby, t.datecreated AS datecreated, t.dateapproved,
		t.typeid, t.`status`, t.duration, t.durationtype, t.remarks, t.reason 
		from `leave` t 
		inner join leavetype x on t.typeid = x.id 
		inner join useraccount u on t.userid = u.id
        left join useraccount mc on (t.createdby = mc.id)
		left join useraccount p on (t.approvedbyid = p.id)
		".$where_query."  ".$paginate->getSearchAndFilterSQL()." GROUP BY t.id ".$order_query;
	
	// debugMessage($all_results_query); // exit;
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	$listurl = $this->baseUrl('leave/list');
	$addurl = $this->baseUrl('leave/index');
	$resource = "Leave"; // $resource = "Department";
	$icon = "glyphicon glyphicon-time";
	$description = '';
	$isdatatable = true;
	
	$this->headTitle($title.$browserappend);
?>

<script>
$(document).ready(function() {
	// breadcrumb config
	$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
	
}); 
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div class="row">
	<div class="col-sm-12">
    	<form class="form margin0 listform makerelative" action="<?php echo $this->baseUrl("leave/listsearch"); ?>" orginalaction="<?php echo $this->baseUrl("leave/listsearch"); ?>"  method="get" id="listform">
		<div class="box box box-color">
			<div class="box-title noheader">
                <h3></h3>
            </div>
            <div class="box-content" style="padding: 5px 0px;">
                <div class="row">
                    <div class="col-sm-9">
                        <ul class="resetlist listactions">
                        	<?php if($acl->checkPermission($resource, ACTION_APPROVE) || $loggedinuser->isPermanent()) { ?>
                                <li><a class="btn btn-primary blockanchor" href="<?php echo $addurl; ?>"  title="Request Leave">Request Leave</a></li>
                            <?php } ?>
                            <li><input type="text" name="startdate" id="startdate" class="form-control input-sm datefield ordinary readonly width100" value="<?php echo $request->startdate; ?>" placeholder="From:" /></li>
                    		<li><input name="enddate" id="enddate" type="text" class="form-control input-sm datefield ordinary readonly width100" placeholder="To:" value="<?php echo $request->enddate; ?>" /></li>
                            <?php if($acl->checkPermission($resource, ACTION_APPROVE)){ ?>
                                <li>
                                    <?php
                                        $allusers = getUsers();
                                        $dropdown = new Zend_Form_Element_Select('userid',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => 'All Employees'), $allusers),
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array("form-control", 'width150', 'chosen-select', 'input-sm')
                                                            )
                                        );  
                                        $dropdown->setValue($request->getParam('userid')); 
                                        echo $dropdown->render();
                                    ?>
                                </li>
                            <?php } ?>
                            <li>
								<?php
                                    $dropdown = new Zend_Form_Element_Select('typeid',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Types'), $leavetypes),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array("form-control", 'width150', 'input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($request->getParam('typeid')); 
                                    echo $dropdown->render();
                                ?>
                            </li>
                            <li>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('status',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Statuses'), $leavestatuses),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array("form-control", 'width125', 'input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($request->getParam('status')); 
                                    echo $dropdown->render();
                                ?>
                            </li>
                            <li>
                                <button type="submit" class="btn btn-primary blockanchor" id="filter"><i class="fa fa-filter"></i> Filter</button>
                            </li>
                       	</ul>
                  	</div>
                    <div class="col-sm-3">
                        <div class="input-group">
                            <input name="searchterm" id="searchterm" class="form-control form-search" value="<?php echo $request->searchterm; ?>" type="text" placeholder="Search..." />
                            <span class="input-group-addon"><i class="fa fa-search"></i></span>
                        </div>
                        <input type="hidden" name="style" id="style" value="<?php echo $style; ?>" />
                        <input type="hidden" name="exporttrigger" id="exporttrigger" value="<?php echo $request->exporttrigger; ?>" />
                    </div>
              	</div>
                <div class="row">
					<div class="col-sm-12">
						<div class="box box-color box-bordered">
							<div class="box-title condensed">
								<h3><i class="fa fa-calendar"></i> Requests</h3>
                                <div class="actions">
                                	<a href="<?php echo $listurl; ?>" title="Reset List and Clear all Filters" rel="tooltip"><i class="fa fa-refresh"></i></a> &nbsp;
                                	<?php //if ($acl->checkPermission($resource, ACTION_EXPORT)) { ?>
                                        <button type="button" class="btn btn-default btn-xs noround submitexcel" title="Export to CSV" rel="tooltip"><i class='glyphicon-download_alt'></i> Export</button>
                                        <input type="hidden" name="csv_text" id="csv_text" value="" />
                                    <?php //} ?>
                                </div>
							</div>
							<div class="box-content nopadding">
                            	<?php if($has_no_data) { ?>
                                    <div class="alert alert-warning">There are no entries to display</div>
                                <?php } else { ?>    
                                    <table class="table table-hover table-nomargin table-bordered dataTable dataTable-fixedcolumn dataTable-scroll-x dataTable-scroll-y" id="datatable" data-nosearch data-noinfo data-nopagination>
                                        <thead>
                                            <th>Actions</th>
                                            <?php if($acl->checkPermission($resource, ACTION_APPROVE)){ ?>
                                                <th>Employee</th>
                                            <?php } ?>
                                            <th>Start Date</th>
                                            <th>End Date</th>
                                            <th>Return Date</th>
                                            <th>Duration</th>
                                            <th>Leave Type</th>
                                            <th>Status</th>
                                            <th>Date Submitted</th>
                                            <th>Approved By</th>
                                            <th>Date Approved</th>
                                            <th>Remarks / Comments</th>
                                        </thead>
                                        <tbody>
                                            <?php
                                                foreach($result as $line){
                                                    $viewurl = $this->baseUrl('leave/view/id/'.encode($line['id']));
                                                    $indexurl = $this->baseUrl('leave/index/id/'.encode($line['id']));
                                                    
                                                    $style = ''; $customclass = '';
                                                    $status = isArrayKeyAnEmptyString($line['status'], $leavestatuses) ? '' : $leavestatuses[$line['status']];
                                                    if($line['status'] == 0){ // requested
                                                        $customclass = ' alert-warning bolded';
                                                    }
                                                    if($line['status'] == 1){ // approved
                                                        $customclass = ' alert-success';
                                                    }
                                                    if($line['status'] == 2){ // rejected
                                                        $customclass = ' alert-danger';
                                                    }
                                                    if($line['status'] == 3){ // on leave
                                                        $style = 'style="background-color:#2d6ca2; color:#fff;"';
                                                    }
                                                    if($line['status'] == 4){ // taken
                                                        $style = 'style="background-color:#f8ea07; color:#000;"';
                                                    }
                                                    // check permission to edit
                                                    $allowedit = false;
                                                    if($acl->checkPermission($resource, ACTION_EDIT)){
                                                        if($loggedinuser->getID() == $line['userid'] && $line['status'] == 0){
                                                            $allowedit = true;
                                                        }
                                                        if($loggedinuser->getID() == $line['userid'] && $line['status'] == 2){
                                                            $allowedit = true;
                                                        }
                                                        if($acl->checkPermission($resource, ACTION_APPROVE)){
                                                            $allowedit = true;
                                                        }
                                                    }
                                                    $allowdelete = false;
                                                    if($acl->checkPermission($resource, ACTION_DELETE)){
                                                        if($loggedinuser->getID() == $line['userid'] && $line['status'] == 0){
                                                            $allowdelete = true;
                                                        }
                                                    }
                                                    if($acl->checkPermission($resource, ACTION_APPROVE) && $line['status'] == 2){
                                                        $allowdelete = true;
                                                    }
                                                    
                                                    $allowapprove = false;
                                                    if($acl->checkPermission($resource, ACTION_APPROVE) && ($line['status'] == '0')){
                                                        $allowapprove = true;
                                                    }
                                                    
                                                    $allowreject = false;
                                                    if($acl->checkPermission($resource, ACTION_APPROVE) && ($line['status'] == '0')){
                                                        $allowreject = true;
                                                    }
                                                    
                                                    $unit = '';
                                                    if(!isArrayKeyAnEmptyString($line['durationtype'], $leaveoptions)){
                                                        $unit = ' ('.$leaveoptions[$line['durationtype']].')';
                                                    }
                                                    
                                            ?>
                                                <tr style="font-size:13px;">
                                                    <?php ob_start(); ?>
                                                        <a class="btn btn-default btn-xs confirm-prompt noimgbutton inline" title="Reject Request" style="padding-top: 2px; padding-bottom:4px;" action="<?php echo $this->baseUrl('leave/updatestatus/id/'.$line['id'].'/status/2/successurl/'.encode($this->viewurl).'/successmessage/leave_rejected_success'); ?>" message="Reject <?php echo $line['duration'].$unit; ?> requested by <?php echo $line['User']; ?>. <br>Please specify Reason/Comment to continue"><i class="fa fa-times"></i></a>
                                                    <?php $rejecthtml = ob_get_clean(); ?>
                                                    <?php ob_start(); ?>
                                                        <a class="btn btn-success btn-xs confirm-dialog noimgbutton inline" style="padding-top: 2px; padding-bottom:4px;" title="Approve Request" action="<?php echo $this->baseUrl('leave/updatestatus/id/'.$line['id'].'/status/1/successurl/'.encode($this->viewurl).'/successmessage/leave_approve_success'); ?>" message="Are you sure you want to Approve <?php echo $line['duration'].$unit; ?> requested by <br><?php echo $line['User']; ?> from <?php echo changeMySQLDateToPageFormat($line['startdate']); ?> to <?php echo changeMySQLDateToPageFormat($line['enddate']); ?>"><i class="fa fa-check"></i></a>
                                                    <?php $approvehtml = ob_get_clean(); ?>
                                                    <td>
                                                        <a class="btn btn-default btn-xs noimgbutton blockanchor inline" title="View Request Details" style="padding-top: 2px; padding-bottom:4px;" href="<?php echo $viewurl; ?>"><i class="fa fa-list"></i></a>
                                                        <?php if ($allowdelete) { ?>
                                                            <a class="btn btn-default btn-xs noimgbutton deleteline gonowhere inline" style="padding-top: 2px; padding-bottom:4px;" action="<?php echo $this->baseUrl('leave/delete/id/'.encode($line['id'])."/entityname/Leave/successurl/".encode($this->viewurl)); ?>" message="<?php echo $this->translate('global_delete_confirm_message'); ?>" title="Delete Entry"><i class="fa fa-times"></i></a>
                                                        <?php } ?>  
                                                        <?php if ($allowedit) { ?>
                                                            <a class="inline blockanchor btn btn-primary btn-sm noimgbutton inline" style="padding-top: 2px; padding-bottom:4px;" href="<?php echo $indexurl; ?>" title="Update"><i class="fa fa-edit"></i></a>
                                                        <?php } ?>
                                                        <?php if($allowapprove){ ?>
                                                            <?php echo $approvehtml; ?>    
                                                        <?php } ?>
                                                        <?php if($allowreject){ ?>
                                                            <?php echo $rejecthtml; ?>                   
                                                        <?php } ?>
                                                    </td>
                                                    <?php if($acl->checkPermission($resource, ACTION_APPROVE)){ ?>
                                                        <td class="nullifempty"><a href="<?php echo $this->baseUrl('profile/view/id/'.encode($line['userid'])); ?>"><?php echo $line['User']; ?></a></td>
                                                    <?php } ?>    
                                                    <td class="nullifempty"><?php echo changeMySQLDateToPageFormat($line['startdate']); ?></td>
                                                    <td class="nullifempty"><?php echo changeMySQLDateToPageFormat($line['enddate']); ?></td>
                                                    <td class="nullifempty"><?php echo changeMySQLDateToPageFormat($line['returndate']); ?></td>
                                                    <td class="nullifempty"><?php echo $line['duration'].$unit; ?></td>
                                                    <td class="nullifempty"><?php echo isArrayKeyAnEmptyString($line['typeid'], $leavetypes) ? '' : $leavetypes[$line['typeid']]; ?></td>
                                                    <td class="nullifempty <?php echo $customclass; ?>" <?php echo $style; ?>><?php echo $status; ?></td>
                                                    <td class="nullifempty"><?php echo changeMySQLDateToPageFormat($line['datecreated']); ?></td>
                                                    <td class="nullifempty"><?php echo $line['approver']; ?></td>
                                                    <td class="nullifempty"><?php echo changeMySQLDateToPageFormat($line['dateapproved']); ?></td>
                                                    <td class="nullifempty">
                                                        <span class="blocked"><?php echo isEmptyString($line['remarks']) ? '' : nl2br($line['remarks']); ?></span>
                                                        <span class="blocked bolded"><?php echo isEmptyString($line['reason']) ? '' : nl2br($line['reason']); ?></span>
                                                    </td>
                                                </tr>
                                            <?php } ?>
                                        </tbody>
                                    </table>
                              	<?php } ?>    
                            </div>
                      	</div>
                   	</div>
              	</div>
                <?php if(!$has_no_data) { ?>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-actions">
                                <div class="col-sm-3 paddingleft5 floatleft"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                                <div class="col-sm-6 padding0"><?php echo $paginate->getPaginationLinks(); ?></div>
                                <div class="col-sm-3 padding0 rightalign"><?php echo $paginate->getListCountDropDown(); ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="divider5"></div>
            	<?php } ?>    
          	</div>
      	</div>
        </form>
   	</div>
</div>            
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
