<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	
	$leave = new Leave();
	$leave->populate(decode($request->id)); // debugMessage($role->toArray());
	
	$resource = 'Leave';
	$description = '';
	$listurl = $this->baseUrl("leave/list");
	$listitems  = "Leave Requests";
	$pagetitle = "Request Details";
	$title = 'Leave Request';
	$icon = 'glyphicon glyphicon-time';
	
	$allowedit = false;
	if($acl->checkPermission($resource, ACTION_EDIT)){
		if($leave->isPending() || $acl->checkPermission($resource, ACTION_APPROVE)){
			$allowedit = true;
		}
	}
	
	$allowdelete = false;
	if($acl->checkPermission($resource, ACTION_DELETE)){
		if($leave->isPending()){
			$allowdelete = true;
		}
	}
	$allowapprove = false;
	if($acl->checkPermission($resource, ACTION_APPROVE) && ($leave->isPending())){
		$allowapprove = true;
	}
	
	$allowreject = false;
	if($acl->checkPermission($resource, ACTION_APPROVE) && ($leave->isPending() || $leave->isApproved())){
		$allowreject = true;
	}
	
	$leavetypes = getLeaveTypes();
	$leavestatuses = getLeaveStatuses();
	$leaveoptions = getHoursDaysDropdown();
	$unit = '';
	if(!isArrayKeyAnEmptyString($leave->getdurationtype(), $leaveoptions)){
		$unit = ' '.$leaveoptions[$leave->getdurationtype()].' ';
	}
	
	$pageid = "leave_index";
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.$title.' / '.$pagetitle; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
	
});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div id="<?php echo $pageid; ?>">
	<div class="row">
		<div class="col-sm-8">
        	<div class="box box-color box-bordered">
                <div class="box-title">
                    <h3><i class="fa fa-th-list"></i> <?php echo $pagetitle; ?></h3>
                    <div class="actions">
                        <?php if($allowapprove) { ?>
                            <a class="xbtn confirm-dialog gonowhere inline" title="Approve Request" rel="tooltip" action="<?php echo $this->baseUrl('leave/updatestatus/id/'.$leave->getID().'/status/1/successurl/'.encode($this->viewurl).'/successmessage/leave_approve_success'); ?>" message="Are you sure you want to Approve <?php echo $leave->getDuration().$unit; ?> requested by <br><?php echo $leave->getUser()->getName(); ?> from <?php echo changeMySQLDateToPageFormat($leave->getstartdate()); ?> to <?php echo changeMySQLDateToPageFormat($leave->getenddate()); ?>"><i class="fa fa-check"></i> Approve</a> &nbsp;
                        <?php } ?>
                        <?php if($allowreject) { ?>
                            <a class="xbtn confirm-prompt gonowhere inline" title="Reject Request" action="<?php echo $this->baseUrl('leave/updatestatus/id/'.$leave->getID().'/status/2/successurl/'.encode($this->viewurl).'/successmessage/leave_rejected_success'); ?>" rel="tooltip" message="Reject <?php echo $leave->getDuration().$unit; ?> requested by <?php echo $leave->getUser()->getName(); ?>. <br>Please specify Reason/Comment to continue"><i class="fa fa-remove"></i> Reject</a> &nbsp;
                        <?php } ?>
                        <?php if($allowedit) { ?>	
                            <a class="xxbtn" title="Update" rel="tooltip" href="<?php echo $this->baseUrl('leave/index/id/'.encode($leave->getID())); ?>" id="update"><i class="fa fa-edit"></i>&nbsp; Update</a> &nbsp;
                        <?php } ?>
                        <?php if($allowdelete) { ?>	
                            <a class="xbtn deleteline gonowhere" action="<?php echo $this->baseUrl('leave/delete/id/'.encode($leave->getID())."/entityname/Leave/successurl/".encode($listurl)); ?>" message="<?php echo $this->translate('global_delete_confirm_message'); ?>" title="Delete Entry"><i class="fa fa-times"></i></a> &nbsp;
                        <?php } ?>
                        <?php if($acl->checkPermission($resource, ACTION_LIST)) { ?>
                            <a class="xbtn" title="Leave History" rel="tooltip" href="<?php echo $listurl; ?>"><i class="fa fa-list"></i></a> &nbsp;
                        <?php } ?>
                    </div>
                </div>
                <div class="box-content nopadding">
                    <form class="form-horizontal form-bordered">
                        <?php if(isAdmin() || $acl->checkPermission($resource, ACTION_APPROVE)){ ?>
                      		<div class="form-group">
                                <label class="col-sm-3 control-label">Employee: </label>
                                <div class="col-sm-9"><?php echo $leave->getUser()->getName(); ?></div>
                            </div>
                        <?php } ?>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('leave_typeid_label'); ?>: </label>
                            <div class="col-sm-9"><?php echo $leave->getType()->getName(); ?></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('leave_description_label'); ?>:</label>
                            <div class="col-sm-9"><?php echo nl2br($leave->getRemarks()); ?>&nbsp; </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Start Date/Time:</label>
                            <div class="col-sm-9"><?php echo changeMySQLDateToPageFormat($leave->getstartdate()); ?></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Time Requested: </label>
                            <div class="col-sm-9">
                                <?php echo $leave->getDuration().$unit. ' ('.$leave->getDuration()/getHoursInDay().' Days)'; ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">End Date/Time: </label>
                            <div class="col-sm-9"><?php echo changeMySQLDateToPageFormat($leave->getenddate()); ?></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Return Date/Time: </label>
                            <div class="col-sm-9"><?php echo changeMySQLDateToPageFormat($leave->getreturndate()); ?></div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Date Submitted: </label>
                            <div class="col-sm-9">
                                <?php echo formatDateAndTime($leave->getdatecreated()); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Current Status: </label>
                            <div class="col-sm-9">
                                <?php echo isArrayKeyAnEmptyString($leave->getstatus(), $leavestatuses) ? '' : $leavestatuses[$leave->getstatus()]; ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Date <?php echo $leave->isRejected() ? 'Rejected' : 'Approved'; ?>:</label>
                            <div class="col-sm-9">
                                <?php echo isEmptyString($leave->getdateapproved()) ? '--' : formatDateAndTime($leave->getdateapproved()); ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $leave->isRejected() ? 'Rejected' : 'Approved'; ?> By:</label>
                            <div class="col-sm-9">
                                <?php echo isEmptyString($leave->getApprovedByID()) ? '--' : $leave->getApprover()->getName(); ?>
                            </div>
                        </div>
                    </form>
               	</div>
         	</div>
      	</div>
 	</div>
</div> 
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>