<?php
	require_once APPLICATION_PATH.'/includes/header.php';

	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	$customlabel = "";
	
	$title = "Attendance History"; 
	$listitems = "Records";
	$description = "";
	
	$style = '2';
	/*if($istimesheetuser){
		$style = '1';
	}*/
	if(!isEmptyString($request->style)){
		$style = $request->style;
		$session->setVar('style', $request->style);
	}
	if(isEmptyString($request->style) && !isEmptyString($session->getVar('style'))){
		$style = $session->getVar('style');
	}
	
	
	$startdate = $request->startdate;
	$enddate = $request->enddate;
	if(!isEmptyString($startdate)){
		$startdate = changeDateFromPageToMySQLFormat($startdate);
		$allowclear = true;
	}
	$enddate = $request->getParam('enddate');
	if(!isEmptyString($enddate)){
		$enddate = changeDateFromPageToMySQLFormat($enddate);
		$allowclear = true;
	}
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array());
	$paginate->setFilterColumns(array());
	$paginate->setItemCountPerPage("25");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE t.id <> '' AND u.companyid = '".$companyid."' ";
	$allowclear = false;
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	// check if user is a time based user or is not among approvers
	if($istimesheetuser || !$acl->checkPermission("Timesheets", ACTION_APPROVE)){
		$where_query .= " AND t.`userid` = '".$loggedinuser->getID()."' ";
	}
	
	$status = trim($request->status);
	if(!isEmptyString($status)){
		$where_query .= " AND t.`status` = '".$status."' ";
		$allowclear = true;
	}
	
	$isapproval = false;
	if($action == 'forapproval'){
		$isapproval = true;
		$where_query .= " AND t.`status` = '2' ";
		$title = "Timesheets For Approval"; 
		$listitems = "Timesheets";
		$description = "Attendance records pending approval";
		$style = 2;
		$session->setVar('style', $style);
	}
	
	if(!isEmptyString($startdate)){
		$where_query .= " AND (TO_DAYS(t.datein) >= TO_DAYS('".$startdate."')) ";
		$allowclear = true;
	}
	if(!isEmptyString($enddate)){
		$where_query .= " AND (TO_DAYS(t.datein) <= TO_DAYS('".$enddate."')) ";
		$allowclear = true;
	}
		
	$order = trim($request->order);
	$order_query = " ORDER BY t.timesheetdate DESC, t.id desc ";
	
	$sortcolumn = $request->sortby;
	$sortorder = $request->sortorder;
	if(!isEmptyString($sortcolumn) && !isEmptyString($sortorder)){
		$order_query = " ORDER BY " . $sortcolumn. " " .$sortorder. " ";
	}
	// f.orgname as fundername, concat(t.firstname,' ',t.lastname) as supervisorname
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT 
	t.id as aid, t.userid, t.timesheetdate, t.payrollid, t.isrequest, t.datein, t.timein, t.dateout, t.timeout, t.inremarks, t.outremarks, t.comments, t.payrollid, t.notes, t.hours, IF(u.displayname <> '', u.displayname, concat(u.firstname, ' ', u.lastname, ' ', u.othername)) as `Name`, t.status
	FROM timesheet t
	inner join useraccount u on t.userid = u.id 
	 ".$where_query." ".$paginate->getSearchAndFilterSQL()." GROUP BY t.id ".$order_query;
	// debugMessage($all_results_query); // exit;
	
	// determine total number of records found
	$conn = Doctrine_Manager::connection(); 
	$count_query = "SELECT count(t.id) as total FROM timesheet t inner join useraccount u on t.userid = u.id 
	".$where_query." ".$paginate->getSearchAndFilterSQL(); // debugMessage($count_query); exit;
	$total = $conn->fetchOne($count_query);
	$paginate->setItemCount($total); //debugMessage('>> '.$total);	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false;
	
	$resource = "Attendance";
	$listurl = $this->baseUrl('timesheets/attendance');
	$addurl = $this->baseUrl('timesheets/checkin');
	$description = '';
	$icon = 'glyphicon glyphicon-time';
	$ischeckin = isCheckedIn($loggedinuser->getID(), date('Y-m-d')) ? true : false; // debugMessage($ischeckin);
		
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	// breadcrumb config
	$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
	
	$(".submitexcel").click(function(e){
		e.preventDefault();
		var csv_value = $('#datatable').table2CSV({delivery:'value'});
		var decoded_value = base64_encode(csv_value);
		$("#csv_text").val(decoded_value);
		$("#listform").attr('action', '<?php echo $this->baseUrl('download/excel'); ?>').attr('method', 'post').submit();
		// on submit reset the form parameters to previous definition
		$("#listform").attr('action', '<?php echo $this->baseUrl("timesheet/attendancesearch"); ?>').attr('method', 'get');
		$("#csv_text").val('');
		return true;
	});
	
	$(".filter, #filter").click(function(e){
		return true;
	});
	
	$(".isclicked, #selectall").attr('checked', false);
	$("#actions").val('');
	
	// select or unselect all checkboxes on click all
	$("#selectall").click(function(){		
		if(this.checked == true) {
			$(".linechecker").trigger('click');
		} else {			
			$(".linechecker").attr('checked', false);
		} 
	});
	
	// if user clicks any of the check boxes for multiple actions, force markmessagesasread select value to empty string 
	$(".isclicked, #selectall").click(function(){
		$("#actions").val('');
	});
}); 
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div class="row">
	<div class="col-sm-12">
    	<form class="form margin0 listform makerelative" action="<?php echo $this->baseUrl("timesheets/attendancesearch"); ?>" method="get" id="listform">
		<div class="box box box-color xbox-bordered">
			<div class="box-title noheader">
                <h3></h3>
            </div>
            <div class="box-content nopadding">
                <div class="row">
                    <div class="col-sm-12">
                        <ul class="resetlist listactions">
                        	<?php if ($acl->checkPermission("Attendance", ACTION_CREATE)) { ?>
                                <li><a class="btn btn-primary btn-sm <?php echo $ischeckin ? 'alert-dialog gonowhere disabled' : 'addpopup'; ?>" href="<?php echo $this->baseUrl('timesheets/checkin/userid/'.encode($loggedinuser->getID()).'/pgc/true'); ?>"  title="Check In" rel="Check In" id="checkin" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("timesheets/processattendance"); ?>" message="Already In!" submittext="Check-In Now">Check In</a></li>
                                <li><a class="btn btn-primary btn-sm addpopup" href="<?php echo $this->baseUrl('timesheets/request/userid/'.encode($loggedinuser->getID()).'/pgc/true'); ?>"  title="Add Timesheet Request" rel="Add Timesheet Request" formtitle="indexform" successurl="<?php echo $this->baseUrl('timesheets/attendance'); ?>" action="<?php echo $this->baseUrl("timesheets/processattendance"); ?>" submittext="Submit Timesheet">Add Timesheet</a>
                                </li>
                            <?php } ?>
                            <li><input type="text" name="startdate" id="startdate" class="form-control input-sm datefield ordinary readonly width100" value="<?php echo $request->startdate; ?>" placeholder="From:" /></li>
                    		<li><input name="enddate" id="enddate" type="text" class="form-control input-sm datefield ordinary readonly width100" placeholder="To:" value="<?php echo $request->enddate; ?>" /></li>
                            <?php if ($acl->checkPermission("Attendance", ACTION_APPROVE)) { ?>
                                <li>
                                    <?php
                                        $values = getUsers();
                                        $dropdown = new Zend_Form_Element_Select('userid',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => 'All Users'), $values),
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array("xautofilter", "form-control",'width150', 'input-sm')
                                                            )
                                        );  
                                        $dropdown->setValue($request->getParam('userid')); 
                                        echo $dropdown->render();
                                    ?>
                                </li>
                            <?php } ?>
                            <li>
                                <?php
                                    $allstatuses = getTimesheetStatuses();
                                    $dropdown = new Zend_Form_Element_Select('status',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Statuses'), $allstatuses),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array("xautofilter", "form-control",'width150', 'input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($request->getParam('status')); 
                                    echo $dropdown->render();
                                ?>                    
                            </li>
                            <li>
                                <button type="submit" class="btn btn-primary btn-sm blockanchor" id="filter"><i class="fa fa-filter"></i> Filter</button>
                            </li>
                        </ul>
                  	</div>
              	</div>
                <div class="row">
					<div class="col-sm-12">
						<div class="box box-color box-bordered">
							<div class="box-title condensed">
								<h3><i class="fa fa-calendar"></i> Timesheets</h3>
                                <div class="actions">
                                	<a href="<?php echo $listurl; ?>" title="Reset List and Clear all Filters" rel="tooltip"><i class="fa fa-refresh"></i></a> &nbsp;
                                	<?php if ($acl->checkPermission($resource, ACTION_EXPORT)) { ?>
                                        <button type="button" class="btn btn-default btn-xs noround submitexcel" title="Export to CSV" rel="tooltip"><i class='glyphicon-download_alt'></i> Export</button>
                                        <input type="hidden" name="csv_text" id="csv_text" value="" />
                                    <?php } ?>
                                	 <?php
										$data = array("" => "<Batch Actions>");
										if($acl->checkPermission("Attendance", ACTION_CREATE)){
											$data[1] = "Submit All Selected";
										}
										if ($acl->checkPermission("Timesheets", ACTION_APPROVE)){
											$data[3] = "Approve All Selected";
										}
										if ($acl->checkPermission("Timesheets", ACTION_APPROVE)){
											$data[4] = "Reject All Selected";
										}
										/*if ($acl->checkPermission("Attendance", ACTION_DELETE)){
											$data[5] = "Delete All Selected"; 
										}*/
										$read = new Zend_Form_Element_Select('actions',
													array(
														'multiOptions' => $data, 
														'view' => new Zend_View(),
														'decorators' => array('ViewHelper'),
														'class' => array("removesorttitle","form-control","input-sm","inline"),
														'style' => 'width:130px;'
													)
										);
										$read->setValue(''); 
										echo $read->render();	
									?>
                                </div>
							</div>
							<div class="box-content nopadding">
                            	<?php if($has_no_data) { ?>
                                    <div class="alert alert-warning">There are no entries to display</div>
                                <?php } else { ?>
                                    <table class="table table-hover table-nomargin" id="datatable">
                                        <thead>
                                            <tr>
                                                <?php if($acl->checkPermission("Attendance", ACTION_APPROVE)){ ?>
                                                    <th class="nowrapping valigntop"><?php echo $paginate->getSortLinkForColumn('',  'Employeee'); ?></th>
                                                <?php } ?>    
                                                <th class="nowrapping valigntop"><?php echo $paginate->getSortLinkForColumn('', 'Date In'); ?> <img style="width:40px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                <th class="nowrapping valigntop"><?php echo $paginate->getSortLinkForColumn('', 'Time In'); ?> <img style="width:30px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                <th class="nowrapping valigntop"><?php echo $paginate->getSortLinkForColumn('', 'Date Out'); ?> <img style="width:40px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                <th class="nowrapping valigntop"><?php echo $paginate->getSortLinkForColumn('', 'Time Out'); ?> <img style="width:30px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                <th class="nowrapping valigntop"><?php echo $paginate->getSortLinkForColumn('', 'Hours'); ?> <img style="width:30px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                <th class="nowrapping valigntop" style="width:120px;"><?php echo $paginate->getSortLinkForColumn('', 'Remarks'); ?></th>
                                                <th class="nowrapping valigntop"><?php echo $paginate->getSortLinkForColumn('', 'Status'); ?> <img style="width:60px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>
                                                <th class="nowrapping" style="padding-left:5px; width: <?php echo $acl->checkPermission("Attendance", ACTION_CREATE) ? '130px' : '110px'; ?> !important;">
                                                    <span class="floatleft">Actions</span> <input type="checkbox" id="selectall" name="selectall" value="" class="floatright" />
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                                foreach($result as $line){
                                                    $viewurl = stripUrl($this->baseUrl('profile/view/id/'.encode($line['userid'])));
                                                    $outstr = '';
                                                    if($line['datein'] != $line['dateout'] && !isEmptyString($line['dateout'])){
                                                        $outstr = ' <b>['.changeMySQLDateToPageFormat($line['dateout']).']</b>';
                                                    }
                                                    $hours = ''; $fulldatein = ''; $fulldateout = ''; 
                                                    if(!isEmptyString($line['timein']) && !isEmptyString($line['timeout'])){
                                                        $fulldatein = strtotime($line['datein'].' '.$line['timein']);
                                                        $fulldateout = strtotime($line['dateout'].' '.$line['timeout']);
                                                        $hours = $fulldateout - $fulldatein;
                                                        $hours = formatNumber($hours/3600);
                                                    }
                                                    if(!isEmptyString($line['hours'])){
                                                        $hours = $line['hours'];
                                                    }
                                                    
                                                    $style = ''; $customclass = '';
                                                    $status = isArrayKeyAnEmptyString($line['status'], $allstatuses) ? '' : $allstatuses[$line['status']]; 
                                                    if($line['status'] == 0 && isEmptyString($line['timeout'])){ 
                                                        $style = 'style="background-color:#2d6ca2; color:#fff;"';
                                                    }
                                                    if($line['status'] == 1 && !isEmptyString($line['timeout'])){
                                                        $style = 'style="background-color:#d4d6fc; color:#000;"';
                                                    }
                                                    if($line['status'] == 2){
                                                        $customclass = ' alert-warning';
                                                    }
                                                    if($line['status'] == 3){
                                                        $customclass = ' alert-success';
                                                    }
                                                    if($line['status'] == 4){
                                                        $customclass = ' alert-danger';
                                                    }
                                                    $isoverdue = false;
                                                    if(!isEmptyString($line['datein']) && isEmptyString($line['dateout']) && (strtotime(date('Y-m-d')) > strtotime($line['datein']))) {
                                                        $line['status'] = 5;
                                                        $status = $allstatuses[$line['status']]; 
                                                        $style = 'style="background-color:#f8ea07; color:#000;"';
                                                        $isoverdue = true;
                                                    }
                                                    
                                                    $viewnotes = '';
                                                    if(!isEmptyString($line['inremarks'])){
                                                        $viewnotes = '<b>In:</b> '.nl2br($line['inremarks']);
                                                    }
                                                    if(!isEmptyString($line['outremarks'])){
                                                        $viewnotes = '<b>Out:</b> '.nl2br($line['outremarks']);
                                                    }
                                                    if(!isEmptyString($line['comments'])){
                                                        $viewnotes = '<b>Remarks:</b> '.nl2br($line['comments']);
                                                    }
                                                    
                                                    $cancheckout = false; $cansubmit = false; $canupdate = false; $candelete = false; $canapprove = false; $canreject = false;  $canselect = false;
                                                    $isonpayroll = false;
                                                    if(!isEmptyString($line['payrollid'])){
                                                        $isonpayroll = true;
                                                    }
                                                    if(!isEmptyString($line['timein']) && isEmptyString($line['timeout']) &&  !$isoverdue && ($acl->checkPermission("Attendance", ACTION_APPROVE))){
                                                        $cancheckout = true;
                                                    }
                                                    if(!isEmptyString($line['timein']) && $line['userid'] != $loggedinuser->getID() && !$isonpayroll && $acl->checkPermission("Attendance", ACTION_APPROVE)){
                                                        $canupdate = true;
                                                    }
                                                    if(!isEmptyString($line['timein']) && !isEmptyString($line['timeout']) &&  $line['userid'] == $loggedinuser->getID() && $line['status'] == '1'){
                                                        $cansubmit = true;
                                                    }
                                                    if(($line['status'] == '2' || $line['status'] == '4') && $acl->checkPermission("Timesheets", ACTION_APPROVE) && !$isonpayroll){
                                                        $canapprove = true;
                                                    }
                                                    if(($line['status'] == '2' || $line['status'] == '3') && $acl->checkPermission("Timesheets", ACTION_APPROVE) && !$isonpayroll){
                                                        $canreject = true; 
                                                    }
                                                    if(!isEmptyString($line['timein']) && !isEmptyString($line['timeout']) && !$isonpayroll){
                                                        $canselect = true;
                                                    }
                                                ?>
                                                    <tr id="line_<?php echo $line['aid']; ?>">
                                                        <?php if($acl->checkPermission("Attendance", ACTION_APPROVE)){ ?>
                                                            <td class="nullifempty"><a href="<?php echo $viewurl; ?>" class="blanklink"><?php echo $line['Name']; ?></a></td>
                                                        <?php } ?>     
                                                        <td class="nullifempty"><?php echo changeMySQLDateToPageFormat($line['timesheetdate']); ?></td>
                                                        <td class="nullifempty"><?php echo isEmptyString($line['timein']) ? '' : formatTimeCustom($line['timein']); ?></td>
                                                        <td class="nullifempty"><?php echo isEmptyString($line['dateout']) ? '' : changeMySQLDateToPageFormat($line['dateout']); ?></td>
                                                        <td class="nullifempty"><?php echo isEmptyString($line['timeout']) ? '' : formatTimeCustom($line['timeout']); ?></td>
                                                        <td class="nullifempty"><?php echo $hours == 0 || isEmptyString($hours) ? '' : $hours; ?></td>
                                                        <td><?php if(!isEmptyString($viewnotes)){ ?>
                                                                <span class="floatleft"><a title="Click to view Details" class="alert-dialog gonowhere" containerstyle="text-align:left;"message="<?php echo $viewnotes; ?>" style="margin-left:10px;">View</a></span>
                                                            <?php } ?>
                                                        </td>
                                                        <td class="nullifempty <?php echo $customclass; ?>" <?php echo $style; ?>><?php echo $status; ?></td>
                                                        <td style="padding-left:5px;">
                                                            <?php if($cancheckout){ ?>
                                                                <a class="btn btn-sm btn-primary inline <?php echo $isoverdue ? 'confirm-dialog' : 'addpopup'; ?>" href="<?php echo $this->baseUrl('timesheets/checkin/id/'.encode($line['aid']).'/type/2/userid/'.encode($line['userid']).'/pgc/true'); ?>"  title="Check Out" rel="Check Out" id="checkout" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("timesheets/processattendance"); ?>" submittext="Check-Out Now" message="Checkout  overdue and has been disabled. Contact Admin or a Supervisor.">Check out</a>
                                                            <?php } ?>
                                                            <?php if($canupdate){ ?>
                                                                <a class="btn btn-primary addpopup inline" href="<?php echo $this->baseUrl('timesheets/checkin/id/'.encode($line['aid']).'/type/3/userid/'.encode($line['userid']).'/pgc/true'); ?>"  title="Update Attendance" rel="Update Attendance" id="update" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("timesheets/processattendance"); ?>" submittext="Save Changes"><i class="fa fa-pencil"></i></a>
                                                            <?php } ?>
                                                            <?php if($cansubmit){ ?>
                                                                <a class="btn btn-success btn-xs confirm-dialog" title="Submit for Approval" action="<?php echo $this->baseUrl('timesheets/submit/id/'.encode($line['aid']).'/successurl/'.encode($this->viewurl)); ?>" message="Are you sure you want to Submit <?php echo $hours; ?> Hours for <?php echo changeMySQLDateToPageFormat($line['datein']); ?> for Approval">Submit for Approval</a>
                                                            <?php } ?>
                                                            <?php if($canapprove){ ?>
                                                                <a class="btn btn-success btn-xs confirm-dialog" title="Approve" rel="tooltip" action="<?php echo $this->baseUrl('timesheets/approve/id/'.encode($line['aid']).'/status/3/successurl/'.encode($this->viewurl)); ?>" message="Are you sure you want to Approve <?php echo $hours; ?> Hours for <?php echo $line['Name']; ?> [<?php echo changeMySQLDateToPageFormat($line['datein']); ?>]"><i class="fa fa-check"></i></a> 
                                                            <?php } ?>    
                                                            <?php if($canreject){ ?>
                                                                <a class="btn btn-default confirm-dialog" title="Reject" rel="tooltip" action="<?php echo $this->baseUrl('timesheets/approve/id/'.encode($line['aid']).'/status/4/successurl/'.encode($this->viewurl)); ?>" message="Are you sure you want to Reject <?php echo $hours; ?> Hours for <?php echo $line['Name']; ?> [<?php echo changeMySQLDateToPageFormat($line['datein']); ?>]"><i class="fa fa-times"></i></a>
                                                            <?php } ?>
                                                            <?php if($canselect){ ?>
                                                                <input type="checkbox" class="isclicked linechecker floatright" id="record_<?php echo $line['aid']; ?>" name="selector" value="<?php echo $line['aid']; ?>" />
                                                            <?php } ?>
                                                        </td>
                                                    </tr>
                                                <?php } ?>
                                        </tbody>
                                    </table>	
                                <?php } ?>
                            </div>
                      	</div>
                   	</div>
              	</div>
                <?php if(!$has_no_data) { ?>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-actions">
                            <div class="col-sm-3 paddingleft5 floatleft"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                            <div class="col-sm-6 padding0"><?php echo $paginate->getPaginationLinks(); ?></div>
                            <div class="col-sm-3 padding0 rightalign"><?php echo $paginate->getListCountDropDown(); ?></div>
                        </div>
                    </div>
                </div>
                <div class="divider5"></div>
                <?php } ?>
          	</div>
      	</div>
        </form>
   	</div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
