<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$user = new UserAccount();	
	$user->populate($userid);
	$currentuserid = '';
	/*if(isTimesheetEmployee()){
		$currentuserid = $user->getID();
	}*/
	$title = 'Calendar';
	$description = '';
	$pageid = "calendar_index";
	$this->headTitle($title.$browserappend);
	
?>
<link rel="stylesheet" href="<?php echo $this->serverUrl($this->baseUrl('stylesheets/plugins/fullcalendar/fullcalendar.css')); ?>">
<link rel="stylesheet" href="<?php echo $this->serverUrl($this->baseUrl('stylesheets/plugins/fullcalendar/fullcalendar.print.css')); ?>" media="print">
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/fullcalendar/moment.min.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/fullcalendar/fullcalendar.min.js')); ?>"></script>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="glyphicon glyphicon-time"></span>');
	
	// Calendar
	if ($(".calendar").length > 0 && !$(".calendar").parent().hasClass("daterangepicker")) {
		var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();

		$('.calendar').fullCalendar(
			'addEventSource', "<?php echo $this->baseUrl('calendar/events/id/'.$currentuserid); ?>"
		);
	}
});
</script>
<style>
#calendar_index .fc-day-grid-event {
	padding:5px 2px;
}
</style>
<div id="<?php echo $pageid; ?>">
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-color">
                <div class="box-title">
                    <h3><i class="fa fa-calendar"></i><?php echo getCompanyName(); ?> Calendar</h3>
                </div>
                <div class="box-content nopadding">
                    <div class="calendar"></div>
                </div>
            </div>
        </div>
    </div>          
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
