<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$user = new UserAccount();
	$id = decode($request->id);
	
	$user->populate($id);
	// debugMessage($user->toArray());	
	
	$hasid = false;
	$mobileactivate = false;
	if(!isEmptyString($id)){
		$hasid = true;
		if ($this->result) {
			$title = $this->translate("useraccount_pagetitle_activation_success"); 
			$this->headTitle($title);
		} else {
			$title = $this->translate("useraccount_pagetitle_activation_failure"); 
			$this->headTitle($title);
		}
	} else {
		if(!isEmptyString($request->act_byphone)){
			$mobileactivate = true;
			$title = "Activate Account"; 
			$this->headTitle($title);
		}
	}
	// $this->result = true;

?>
<script>
$(document).ready(function() {
	
});
</script>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>