<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$title = "Signup Confirmation"; 
	
	$user = new UserAccount();
	$user->populate(decode($request->id));
	
	
	$this->headTitle($title.$browserappend); 
	
?>
<script>
$(document).ready(function() {			
	
	
});	
</script>
<style>
.breadcrumbs li, .pageheader, #headercontainer #headermenu, #headercontainer #headerright {
	display:none;
}
</style>
<div id="publiccontainer" class="col-sm-6 col-sm-offset-3 index">
    <form id="indexform" class="form-horizontal" role="form">
    	<fieldset class="fieldsetcontainer">
            <legend><h4><?php echo $title; ?></h4></legend>
            <div class="panel-body well-sm">
            	<table class="table border0">
                	<tr>
                        <td colspan="2">
                            <div class="alert alert-success fade in"><i class="icon-remove close" data-dismiss="alert"></i> Signup completed</div>
							<?php if($user->isCompanyAdmin()){ ?>
								<?php if($user->getCompany()->isPendingApproval()){ ?>
                                    <blockquote class="basic">
                                        <p>
                                            Your company <b><?php echo $user->getCompany()->getName(); ?></b> has been successfully setup for a <b><?php echo getTrialDays(); ?></b> day free Trial. <br /><br />
                                            However, before you can get started, approval from Admin is required. We shall get back to you shortly with a confirmation email so that you can activate your account.
                                        </p>
                                    </blockquote>
                                <?php } ?>
                                <?php if($user->getCompany()->isActive()){ ?>
                                	<blockquote class="basic">
                                        <p>
                                            Your company <b><?php echo $user->getCompany()->getName(); ?></b> has been successfully setup for a <b><?php echo getTrialDays(); ?></b> day free Trial. <br /><br />
    
    										To activate your account, click on the activation link that has been sent to your email <b><?php echo $user->getEmail(); ?></b><br /><br />
                                            If you do not find the email in your inbox, please check the spam or junk folder.
                                        </p>
                                    </blockquote>
                                <?php } ?>
                        	<?php } ?>
                        </td>  
                    </tr>
                </table>
          	</div>
       	</fieldset>
    </form>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
