<?php
	require_once APPLICATION_PATH.'/includes/header.php';

	$user = new UserAccount(); 
	
	$title = $this->translate("profile_pagetitle_signup"); 
	$pagetitle = "Sign up for a 30 Day Risk Free Trial of ".getAppName();
	$button_title = "SIGN UP NOW";
	$posturl = $this->baseUrl("signup/create"); 
	$failureurl = $this->baseUrl('signup'); 
	$successurl = $this->baseUrl('signup/confirm'); 
	
	// set all fields to empty string as default
	$id = decode($request->id);	 // $id = 74;
	$useractivate = false;
	if(!isEmptyString($id)){
		$user->populate($id);
		$button_title = $this->translate("profile_button_activate");
		$posturl = $this->baseUrl("signup/processinvite");
		$failureurl = $this->baseUrl('signup/index/id/'.$request->id); 
		$successurl = $this->baseUrl('signup/inviteconfirmation/id/'.$request->id);
		$title = "Account Activation";
		$pagetitle = $title;
		$user->setselfregistered(0);
	} else {
		$user->setType(DEFAULT_USER_GROUP);
		$user->setselfregistered(1);
	}
	
	// debugMessage('> '.$this->domain);
	
	// any errors occured in processing
	if ($sessionhaserror) {
	    $user->processPost($session->getVar(FORM_VALUES)); 
	}
	
	$this->headTitle($title.$browserappend); 
?>
<script>
$(document).ready(function() {			
	$(".navonlogin, #sidebar, .breadcrumbs li").remove();
	
	// define the validation rules
	$("#signupform").validate({		
		rules: {
			companyname: "required",
			gender: "required",
			firstname: "required",
			lastname: "required",
			username: {
				required: true, 
				minlength: <?php echo $config->profile->usernameminlength; ?>,
				maxlength: <?php echo $config->profile->usernamemaxlength; ?>
			},
			email: {
				required: true, 
				email: true
			},
			password: {
				required: true,
				minlength: <?php echo $config->profile->passwordminlength; ?>,
				maxlength: <?php echo $config->profile->passwordmaxlength; ?>
			},			
			confirmpassword: {
				required: true,
				equalTo: "#password"
			},
			agreedtoterms: "required",
			code: {
				required: true,
				validatecode: true					
			}
		}, 
		// the messages for each of the fields being validated
		messages: {
			companyname: "Please enter Company Name",
			gender: "<?php echo $this->translate("profile_gender_error"); ?>", 
			firstname: "<?php echo $this->translate("profile_firstname_error"); ?>",
			lastname: "<?php echo $this->translate("profile_lastname_error"); ?>",
			username: {
				required: "<?php echo $this->translate("profile_username_error"); ?>",
				minlength: "<?php echo sprintf($this->translate("profile_username_error_minlength"), $config->profile->usernameminlength); ?>",
				maxlength: "<?php echo sprintf($this->translate("profile_username_error_maxlength"), $config->profile->usernamemaxlength); ?>"
			},
			email: {
				required: "<?php echo $this->translate("profile_email_error"); ?>", 
				email: "<?php echo $this->translate("profile_email_invalid_error"); ?>"
			},
			password: {
				required: "<?php echo $this->translate("profile_password_error"); ?>",
				maxlength: "<?php echo sprintf($this->translate("profile_password_error_maxlength"), $config->profile->passwordmaxlength); ?>",
				minlength: "<?php echo sprintf($this->translate("profile_password_error_minlength"), $config->profile->passwordminlength); ?>"
			},
			confirmpassword: {
				required: "<?php echo $this->translate("profile_confirmpassword_error"); ?>",
				equalTo: "<?php echo $this->translate("profile_confirmpassword_error_equalto"); ?>"
			},
			agreedtoterms: "<?php echo $this->translate("profile_agreetoterms_error"); ?>",
			code: {
				required: "<?php echo $this->translate("profile_captcha_error"); ?>"
			}
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					error.appendTo("#"+element.attr("name")+"_error")
					break;
			}			
		}
	});
	
	// validate captcha
	$.validator.addMethod("validatecode", function(value, element, params) {
		//alert('code is '+value); //alert('valid is '+$("#validcode").val());
		if ($("#code").val().toLowerCase() == $("#validcode").val().toLowerCase()) {
			return true; 
		}
		return false;        
	}, "Captcha Invalid! <br />Re-enter code or refresh for a new one");
	
	$(".hastooltip").change();
	
	// prevent copy and paste in password fields
	$('input.password').bind('copy paste', function (e) {
	   e.preventDefault();
	});
	
	//when button is clicked  
	$('#check_c_username_availability').click(function(){ 
		check2_user_availability();  
	});
	$('#c_username').change(function(){ 
		check2_user_availability();  
	});  
	$('#c_username').keyup(function(){
		this.value = this.value.toLowerCase();
	});
	
	//function to check c_username availability  
	function check2_user_availability(){  
		//get the c_username
		var checking_html = 'Checking availability...';   
		var c_username = $('#c_username').val();  
		if(!isEmptyString(c_username) && c_username.length >= 3 && c_username.length <= 15 && isAlpha(c_username)){
			// alert('passed');
			$('#c_username_availability_result').html(checking_html); 
			//use ajax to run the check  
			$.post("<?php echo $this->baseUrl('signup/checkcompanyusername'); ?>", { username: c_username},  
				function(result){  
					//if the result is 1  
					// alert(result); // return false;
					if(result == 'exists'){  
						//show that the c_username is available
						$('#c_username_availability_result').html(c_username + ' is NOT available!').addClass('alert').addClass('alert-danger').removeClass('alert-success'); 
					} else {  
						//show that the c_username is NOT available  
						$('#c_username_availability_result').html(c_username + ' is available').addClass('alert').addClass('alert-success').removeClass('alert-danger');
					}  
			});   
		}
	}
		
	//when button is clicked  
	$('#check_username_availability').click(function(){ 
		check_user_availability();  
	});
	$('#username').change(function(){ 
		check_user_availability();  
	});  
	$('#username').keyup(function(){
		this.value = this.value.toLowerCase();
	});
	
	//function to check username availability  
	function check_user_availability(){  
		//get the username
		var checking_html = 'Checking availability...';   
		var username = $('#username').val();  
		if(!isEmptyString(username) && username.length >= 4 && username.length <= 15 && isAlpha(username)){
			// alert('passed');
			$('#username_availability_result').html(checking_html); 
			var userid = '<?php echo $user->getID(); ?>';
			//use ajax to run the check  
			$.post("<?php echo $this->baseUrl('signup/checkusername'); ?>", { username: username, userid: userid },  
				function(result){  
					//if the result is 1  
					// alert(result); // return false;
					if(result == 1){  
						//show that the username is available
						$('#username_availability_result').html(username + ' is NOT available!').addClass('alert').addClass('alert-danger').removeClass('alert-success'); 
					} else {  
						//show that the username is NOT available  
						$('#username_availability_result').html(username + ' is available').addClass('alert').addClass('alert-success').removeClass('alert-danger');
					}  
			});   
		}
	}
	
	//when button is clicked  
	$('#check_email_availability').click(function(){ 
		check_email_availability();  
	});
	$('#email').change(function(){ 
		check_email_availability();  
	});  
	
	//function to check email availability  
	function check_email_availability(){  
		//get the username
		var checking_html = 'Checking availability...';   
		var email = $('#email').val();  
		if(!isEmptyString(email) && validateEmail(email)){
			$('#email_availability_result').html(checking_html);  
			var userid = '<?php echo $user->getID(); ?>';
			//use ajax to run the check  
			$.post("<?php echo $this->baseUrl('signup/checkemail'); ?>", { email: email, userid: userid},  
				function(result){  
					//if the result is 1  
					// alert(result); // return false;
					if(result == 1){  
						//show that the email is available
						$('#email_availability_result').html(email + ' is NOT available!').addClass('alert').addClass('alert-danger').removeClass('alert-success fade in'); 
					} else {  
						//show that the email is NOT available  
						$('#email_availability_result').html(email + ' is available').addClass('alert').addClass('alert-success').removeClass('alert-danger fade in');
					}  
			});  
		}
	}
	
});	
</script>
<style>
.breadcrumbs li, .pageheader, #headercontainer #headermenu, #headercontainer #headerright {
	display:none;
}
</style>
<div id="publiccontainer" class="col-sm-7 col-sm-offset-3 index">
	<!--<h3 class="centeralign">Account Activation</h3>-->
	<?php if($sessionhaserror) { ?>
    	<div class="alert alert-danger clear"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
    <?php } ?>
    <?php if(!isEmptyString($session->getVar(SUCCESS_MESSAGE)) ){ ?>
    	<div class="alert alert-success clear"><?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
    <?php } ?>
    <form id="signupform" class="form-horizontal" role="form" action="<?php echo $posturl; ?>" method="post">
        <fieldset class="fieldsetcontainer">
            <legend><h4><?php echo $pagetitle; ?></h4></legend>
            <div class="panel-body well-sm">
                <div class="col-sm-12">
                	<?php if($user->isCompanyAdmin() && $user->getCompany()->isInActive()){ ?>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">Company Name: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control width300" id="companyname" name="companyname" value="<?php echo $user->getCompany()->getName(); ?>" /><div id="companyname_error"></div>
                            </div>
                        </div>
                        <?php if($this->domain == 'hrmagic.ug'){ ?>
                            <div class="form-group">
                                <label class="col-sm-4 control-label">Url/<?php echo $this->translate("profile_username_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                <div class="col-sm-8">
                                    <div class="input-group lineblocked">
                                        <input type="text" class="form-control width150 inline" placeholder="" id="c_username" name="c_username" value="<?php echo $user->getCompany()->getUserName(); ?>" />
                                        <div class="input-group-btn floatleft">
                                            <button type="button" class="btn">.hrmagic.ug</button>
                                        </div>
                                    </div>
                                    <a class="btn btn-primary btn-sm gonowhere inline" id='check_c_username_availability' style="margin-top:-30px; display:inline-block;" title="Check Availability">Check</a>
                                    
                                    <div id="c_username_availability_result" style="margin-top:4px"></div>
                                    <div id="c_username_error"></div>
                                </div>
                            </div>
                        <?php } ?>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">Industry Sector:</label>
                            <div class="col-sm-6">
                               <?php 
							   		$codes = getDatavariables('INDUSTRY_CATEGORIES');
                                    $dropdown = new Zend_Form_Element_Select('industrycode',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $codes),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','width300')
                                                        )
                                    );  
                                    $dropdown->setValue($user->getCompany()->getindustrycode()); 
                                    echo $dropdown->render();
							   ?>
                            </div>
                        </div>
                    	<div class="form-group">
                            <label class="col-sm-4 control-label">Contact Person: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-8">
                            	<div class="col-sm-6 paddingleft0">
                                	<input type="text" class="form-control" id="firstname" name="firstname" placeholder="First Name" value="<?php echo $user->getFirstName(); ?>" />
                                </div>
                                <div class="col-sm-6 paddingleft0">
                                	<input type="text" class="form-control" id="lastname" name="lastname" placeholder="Last Name" value="<?php echo $user->getLastName(); ?>" />
                                </div>
                                <div id="firstname_error"></div><div id="lastname_error"></div>
                            </div>
                        </div>
                    <?php } else { ?>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate("profile_firstname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="firstname" name="firstname" value="<?php echo $user->getFirstName(); ?>" /><div id="firstname_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate("profile_lastname_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-8">
                                <input type="text" class="form-control" id="lastname" name="lastname" value="<?php echo $user->getLastName() == '.' ? '' : $user->getLastName(); ?>" /><div id="lastname_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate("profile_gender_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-8">
                                <label class="radio-inline"><input type="radio" name="gender" id="male" value="1" class="xform-control <?php echo $user->isMale() ? 1 : 0; ?>"> Male</label>
                                <label class="radio-inline"><input type="radio" name="gender" id="female" value="2" class="xform-control <?php echo $user->isFemale() ? 1 : 0; ?>"> Female</label>
                                <div id="gender_error"></div>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("global_email_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control inline width225" id="email" name="email" value="<?php echo $user->getEmail(); ?>" />
                            <a class="btn btn-xs btn-default gonowhere inline" id='check_email_availability' style="margin-top:2px;" title="Check Availability">Check</a>
                            <div id="email_availability_result" style="margin-top:4px"></div>
                            <div id="email_error"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Login <?php echo $this->translate("profile_username_label"); ?>: <?php echo isEmptyString($user->getID()) ? '' : $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control width225 inline" id="username" name="username" value="<?php echo $user->getUserName(); ?>" /> <a class="btn btn-default gonowhere inline" id='check_username_availability' style="margin-top:2px;" title="Check Availability">Check</a>
                            
                            <div id="username_availability_result" style="margin-top:4px"></div>
                            <div id="username_error"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label"><?php echo $this->translate("profile_password_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></label>
                        <div class="col-sm-8 paddingright0">
                             <input type="password" name="password" id="password" class="form-control password width225" autocomplete="off" onkeyup="passwordStrength(this.value)" />
                            <p style="display:inline-block; float:right;">
                                <label for="passwordStrength" class="hidden">Password strength</label>
                                <div id="passwordDescription" style="width:100px;">strength</div>
                                <div id="passwordStrength" class="strength0"></div>
                            </p>
                            <div id="password_error"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label blocked"><?php echo $this->translate("profile_password_confirm_label"); ?>: <?php echo $this->translate("required_field_marker"); ?></label>
                        <div class="col-sm-8 paddingright0">
                            <input type="password" name="confirmpassword" id="confirmpassword" class="form-control password width225" /><div id="confirmpassword_error"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <button type="submit" class="btn btn-primary btn-large floatright"><?php echo $button_title; ?></button>
                <input type="hidden" name="usecustomsave" id="usecustomsave" value="true" />
                <input type="hidden" name="id" id="id" value="<?php echo encode($user->getID()); ?>" />
                <input type="hidden" name="createdby" id="createdby" value="<?php echo $user->getCreatedBy(); ?>" />
                <input type="hidden" name="type" id="type" value="<?php echo $user->getType(); ?>" />
                <input type="hidden" id="selfregistered" name="selfregistered" value="<?php echo $user->getselfregistered(); ?>" />
                <input type="hidden" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($successurl); ?>" />
                <input type="hidden" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($failureurl); ?>" /> 
                <?php if(!isEmptyString($user->getCompanyID())){ ?>
                	<input type="hidden" name="companyid" id="companyid" value="<?php echo $user->getCompanyID(); ?>" />
               	<?php } ?>
        	</div>
            <div class="divider15"></div>
        </fieldset> 
    </form>
</div>             
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
