<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	
	$timeoff = new Timeoff();
	$id = decode($request->id);
	$resource = "Time off";
	$description = '';
	$icon = "glyphicon glyphicon-time";
	
	if(isEmptyString($request->id)){
		$title = 'Request Time-off';
		$button_title = "Submit for Approval"; 
		$successmessage = "Successfully submitted for approval";
		$posturl = $this->baseUrl("timeoff/create");
		$timeoff->setStatus('0');
		$timeoff->setDuration('');
		$timeoff->setUserID($loggedinuser->getID());
		if(isAdmin() || $acl->checkPermission($resource, ACTION_APPROVE)){
			$timeoff->setUserID('');
		}
		if(!isEmptyString($request->userid)){
			$timeoff->setUserID($request->userid);
		}
		$timeoff->setTypeID('1');
		if(!isEmptyString($request->typeid)){
			$timeoff->setTypeID($request->typeid);
		}
		$timeoff->setStartTime('08:00:00');
		$timeoff->setEndTime('17:00:00');
		$timeoff->setReturnTime('08:00:00');
	} else {
		$timeoff->populate(decode($request->id));
		$title = 'Update Request';
		$button_title = "Update and Request Approval";
		$successmessage = "Successfully updated";
		$posturl = $this->baseUrl("timeoff/create");
		if($timeoff->getUserID() == $loggedinuser->getID()){
			$timeoff->setStatus('0');
			$successmessage = "Successfully updated and pending approval";
		}
	}
	
	// $hoursavailable = '16';
	$hoursavailable = getHoursAvailable($timeoff->getUserID(), $timeoff->getTypeID(), $config->system->yearstart, $config->system->yearend); //debugMessage($hoursavailable);
	$daysavailable = $hoursavailable == 0 ? 0 : number_format($hoursavailable/8,2); // debugMessage($daysavailable);
		
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$timeoff->processPost($session->getVar(FORM_VALUES));	
	}
	
	$timeoffs = getTimeoffTypes();
	
	$this->headTitle($title.$browserappend);
?>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/pickadate/picker.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/pickadate/picker.date.js')); ?>"></script>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/pickadate/picker.time.js')); ?>"></script>
<link href='<?php echo $this->baseUrl('stylesheets/pickadate.css'); ?>' rel='stylesheet' type='text/css'>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'Time-off / '.$title; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
	
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			typeid: "required",
			userid: "required",
			startdate: "required",
			starttime: "required",
			enddate: "required",
			endtime: "required",
			returndate: "required",
			returntime: "required",
			duration: {
				required: true,
				duration_validation: true,
				min:0.1
			}
		}, 
		// the messages for each of the fields being validated
		messages: {		
			typeid: "Please select a Type",
			userid: "Please select an Employee",
			startdate: "Please select a Date",
			starttime: "Please select Time",
			enddate: "Please select a Date",
			endtime: "Please select Time",
			returndate: "Please select a Date",
			returntime: "Please select Time",
			duration: {
				required: "Please enter Hours",
				min: "Value should be greater than 0"
			}
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					if(element.hasClass("useid_error")){
						error.appendTo("#"+element.attr("id")+"_error");
					} else {
						error.appendTo("#"+element.attr("name")+"_error");
					}
					break;
			}			
		},
		ignore: ":hidden:not(select)"
	});
	
	// function to validate the enddate being greater than the start date
	$.validator.addMethod("duration_validation", function(value, element) {            
		var duration = value; 
		var durationtype = $('[name=durationtype]:checked').val();  // alert(durationtype);
		var availablehrs = '<?php echo $hoursavailable; ?>';  
		var availabledays = '<?php echo $daysavailable; ?>';  
		if(durationtype == 1 && duration > availablehrs){
			return false;
		}
		if(durationtype == 2 && duration > availabledays){
			return false;
		}
		return true;        
	}, "Should be less than <?php echo $hoursavailable.' Hours ('.$daysavailable.' Days)'; ?>");
	
	$('.timepicker').pickatime({
	   interval: 30
	});
	
	$("#typeid").change(function(){
		var url = '<?php echo stripURL($this->viewurl); ?>'; //alert(url);
		var currenttypeid = '<?php echo $timeoff->getTypeID(); ?>';
		
		var typeid = $(this).val();
		var newurl = '<?php echo stripURL($this->viewurl).'/typeid/'; ?>'+typeid; //alert(newurl);
		var striptxt = '/typeid/'+currenttypeid;
		var replacetxt = '/typeid/'+typeid;
		if(typeid != currenttypeid){
			newurl = newurl.replace(striptxt, ''); // alert(newurl);
			$.blockUI({ message: '<?php echo $blockcontent; ?>' });
			window.location.href = newurl
		}
	});
	
	$("#userid").change(function(){
		var url = '<?php echo stripURL($this->viewurl); ?>'; //alert(url);
		var currentuserid = '<?php echo $timeoff->getUserID(); ?>';
		
		var userid = $(this).val();
		var newurl = '<?php echo stripURL($this->viewurl).'/userid/'; ?>'+userid; //alert(newurl);
		var striptxt = '/userid/'+currentuserid;
		var replacetxt = '/userid/'+userid;
		if(isEmptyString(currentuserid)){
			$.blockUI({ message: '<?php echo $blockcontent; ?>' });
			window.location.href = newurl
		} else {
			if(userid != currentuserid){
				newurl = newurl.replace(striptxt, ''); // alert(newurl);
				$.blockUI({ message: '<?php echo $blockcontent; ?>' });
				window.location.href = newurl
			}
		}
	});
});
</script>
<div class="row-fluid margin0 index">
    <form id="indexform" class="form-horizontal" role="form" action="<?php echo $posturl; ?>" method="post">
        <div class="col-md-12 padding0">
            <div class="headerbox">
                <table class="table border0 nohover margin0">                       
                    <tr>		                    
                        <td class="padding2">
                            <button type="submit" class="btn btn-primary btn-success savethenview save"><i class="glyphicon glyphicon-ok icon-white"></i> <?php echo $button_title; ?></button>
                            <a class="btn btn-default cancel gonowhere"><i class="glyphicon glyphicon-remove"></i> <?php echo $this->translate('global_button_cancel'); ?></a>
                            <input name="entityname" id="entityname" type="hidden" value="Timeoff" />
        					<input type="hidden" id="id" name="id" value="<?php echo encode($timeoff->getID()); ?>" />
                            <input type="hidden" id="status" name="status" value="<?php echo $timeoff->getStatus(); ?>" />
                            <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" /> 
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <?php if ($sessionhaserror) { ?>
            <div class="alert alert-danger"><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
        <?php } ?>
        <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
            <div class="alert alert-success alert-dismissable"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button> <?php echo $session->getVar(SUCCESS_MESSAGE); ?></div>
        <?php } ?>
        <div class="contentcontainer clearfix">
        	<div class="row-fluid marginleft5">
            	<div class="col-md-12">
                    <fieldset class="fieldsetcontainer">
                        <legend>Summary</legend>
                        <div class="panel-body well-sm">
                            <div class="col-md-12">
                            	<div class="row-fluid margin">
                                	<div class="col-md-12 paddingleft0">
                                    	<?php if(isAdmin() || $acl->checkPermission($resource, ACTION_APPROVE)){ ?>
                                            <div class="form-group">
                                                <label class="col-sm-2 control-label"><?php echo $this->translate('leave_user_label'); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                                <div class="col-sm-10">
                                                    <?php if(isEmptyString($timeoff->getID())){ ?>
                                                    	<?php
															$allvalues = getUsers();
															$dropdown = new Zend_Form_Element_Select('userid',
																				array(
																					'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
																					'view' => new Zend_View(),
																					'decorators' => array('ViewHelper'),
																					'class' => array('form-control','input-sm','width200')
																				)
															);  
															$dropdown->setValue($timeoff->getUserID()); 
															echo $dropdown->render();
														?>
                                                    <?php } else { ?>
                                                        <?php echo $timeoff->getUser()->getName(); ?>
                                                        <input type="hidden" id="userid" name="userid" value="<?php echo $timeoff->getUserID(); ?>" />
                                                    <?php } ?>
                                                    <div id="userid_error"></div>
                                                </div>
                                            </div>
                                        <?php } else { ?>
                                        	<input type="hidden" id="userid" name="userid" value="<?php echo $timeoff->getUserID(); ?>" />
                                        <?php } ?>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label"><?php echo $this->translate('leave_typeid_label'); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                            <div class="col-sm-10">
                                            	<?php if(isEmptyString($timeoff->getID())){ ?>
													<?php
                                                        $dropdown = new Zend_Form_Element_Select('typeid',
                                                                            array(
                                                                                'multiOptions' => $timeoffs,
                                                                                'view' => new Zend_View(),
                                                                                'decorators' => array('ViewHelper'),
                                                                                'class' => array('form-control','input-sm','width200')
                                                                            )
                                                        );  
                                                        $dropdown->setValue($timeoff->getTypeID()); 
                                                        echo $dropdown->render();
                                                    ?>
                                                <?php } else { ?>
                                                	<?php echo $timeoff->getType()->getName(); ?>
                                                	<input type="hidden" id="typeid" name="typeid" value="<?php echo $timeoff->getTypeID(); ?>" />
                                                <?php } ?>
												</span>
                                                <div id="typeid_error"></div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-2 control-label"><?php echo $this->translate('leave_description_label'); ?>:</label>
                                            <div class="col-md-6">
                                                <textarea class="form-control expanding" id="remarks" name="remarks"><?php echo $timeoff->getRemarks(); ?></textarea>
                                                <div id="remarks_error"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                    <fieldset class="fieldsetcontainer">
                        <legend>Duration</legend>
                        <div class="panel-body well-sm">
                            <div class="col-md-12">
                            	<div class="row-fluid margin">
                                	<div class="col-md-12 paddingleft0">
                                    	<div class="form-group">
                                            <label class="col-sm-2 control-label">Start Date/Time: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                            <div class="col-sm-10">
                                            	<input type="text" class="form-control input-sm datefield readonly width100 ordinary" name="startdate" id="startdate" value="<?php echo changeMySQLDateToPageFormat($timeoff->getstartdate()); ?>" />
                                				<input type="text" name="starttime" id="starttime" class="form-control input-sm timepicker inline width100" value="<?php echo date("h:i A", strtotime($timeoff->getstarttime())); ?>" />
                                                <div id="startdate_error"></div><div id="starttime_error"></div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Time Available:</label>
                                            <div class="col-sm-10"><span class="width175 blocked bolded"><?php echo $hoursavailable.' Hours ('.$daysavailable.' Days) '; ?></span></div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Time Requested: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                            <div class="col-sm-10">
                                            	<input type="text" name="duration" id="duration" class="form-control input-sm centeralign isdecimal bolded width100 inline floatleft" value="<?php echo $timeoff->getDuration(); ?>" /> &nbsp;
                                                <label class="radio radio-inline" style="margin-left:20px;"><input type="radio" name="durationtype" id="durationtype_1" checked="checked" class="<?php echo $timeoff->getdurationtype() == '1' ? 1 : 0; ?>" value="1" <?php echo $timeoff->getdurationtype() == '1' ? 'checked="checked"' : ''; ?> /> Hours &nbsp;</label>
                                				<label class="radio radio-inline"><input type="radio" name="durationtype" id="durationtype_2" class="<?php echo $timeoff->getdurationtype() == '2' ? 1 : 0; ?>" value="2" <?php echo $timeoff->getdurationtype() == '2' ? 'checked="checked"' : ''; ?> /> Days</label>
                                                
                                                <div id="duration_error"></div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">End Date/Time: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                            <div class="col-sm-10">
                                            	<input type="text" class="form-control input-sm datefield readonly width100 ordinary" name="enddate" id="enddate" value="<?php echo changeMySQLDateToPageFormat($timeoff->getenddate()); ?>" />
                                				<input type="text" name="endtime" id="endtime" class="form-control input-sm timepicker readonly inline width100" value="<?php echo date("h:i A", strtotime($timeoff->getendtime())); ?>" style="xmargin-left:25px;" />
                                                <span style="font-size:11px;color:#999;"> (Auto-generated from Startdate)</span>
                                                <div class="divider5"></div>
                                                <div id="enddate_error"></div><div id="endtime_error"></div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-sm-2 control-label">Return Date/Time: <?php echo $this->translate("global_required_field_marker"); ?></label>
                                            <div class="col-sm-10">
                                            	<input type="text" class="form-control input-sm datefield readonly width100 ordinary" name="returndate" id="returndate" value="<?php echo changeMySQLDateToPageFormat($timeoff->getreturndate()); ?>" />
                                				<input type="text" name="returntime" id="returntime" class="form-control input-sm timepicker inline width100" value="<?php echo date("h:i A", strtotime($timeoff->getreturntime())); ?>" />
                                                <div id="returndate_error"></div><div id="returntime_error"></div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
   		</div>
 	</form>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
