
<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$role = new AclGroup();
	$id = decode($request->id);
	
	$resourcearray = getResources();
	$definedactions = ACL::getActions();
	
	if(isEmptyString($request->id)){
		$pagetitle = 'New User Role';
		$button_title = $this->translate('global_button_save'); 
		$successmessage = 'global_save_success'; 
		$posturl = $this->baseUrl("role/processroles");
	} else {
		$role->populate(decode($request->id));
		$pagetitle = 'Update Permissions';
		$button_title = $this->translate('global_button_save_changes'); 
		$successmessage = 'global_update_success'; 
		$posturl = $this->baseUrl("role/processroles");
	}
	
	$successurl = $this->baseUrl('role/view');
	$failureurl = $this->viewurl;
	
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$role->processPost($session->getVar(FORM_VALUES));	
	}
	
	$icon = "";
	$description = "";
	$pageid = "role_index";
	$title = "User Roles";
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.$title.' / '.$pagetitle; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="glyphicon glyphicon-cog"></span>');
	
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			name: "required",
			description: "required"
		}, 
		// the messages for each of the fields being validated
		messages: {		
			name: "<?php echo $this->translate("role_name_error"); ?>",
			description: "<?php echo $this->translate("role_description_error"); ?>"
		}
	});
	
	// handling of checkbox selections for the permissions
	// bind the function for updating hidden fields when the respective checkboxes are selected
	$("#permissions :checkbox").change(updatePermissionHiddenField); 
													 
	// function to update the value of hidden field when a permission checkbox is selected or unselected
	function updatePermissionHiddenField() {
		if (this.checked) {
			$("#" + this.value).val("1");
		} else {
			$("#" + this.value).val("0");
		}
	} 
	
	// functionality for the all permissions checkboxes
	// change the odd rows to odd
	$("input[name='allpermissionscheckbox']").click(function() {
		 var id = $(this).attr('id');
		 if(this.checked) {
			 $("."+this.value).attr('checked', true);
			 $("input."+id).val('1');
		 } else {				 
			$("."+this.value).attr('checked', false);
			$("input."+id).val('0');
		 }
		 // trigger a change action on the checkboxes representing the permissions
		 $("." + this.value).trigger("change");
	});
	
	$("#permissions :checkbox").trigger("change");
	$(".resourcetrigger").click(function() {
		var id = $(this).attr('id');
		// alert(id);
		if(this.checked) {
			$("input."+id).val('1');
		} else {				 
			$("input."+id).val('0');
		}
	});
	
});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div id="<?php echo $pageid; ?>">
	<form class="form-horizontal form-bordered" action="<?php echo $posturl; ?>" method="post" id="indexform">
    	<input name="entityname" id="entityname" type="hidden" value="Role" />
        <input type="hidden" id="id" name="id" value="<?php echo encode($role->getID()); ?>" />
        <input name="successmessage" id="successmessage" type="hidden" value="<?php echo $successmessage; ?>" />  
        <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" /> 
        <input type="hidden" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($successurl); ?>" /> 
        <input type="hidden" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($failureurl); ?>" /> 
        <div class="row">
            <div class="col-sm-12">
            	<div class="form-actions testborder clearfix">
                	<a class="btn cancel gonowhere" type="button"><?php echo $this->translate('global_button_cancel'); ?></a>
                    <button class="btn btn-primary btn-green savebutton changesuccessurl" type="submit"><?php echo $button_title; ?></button>
                </div>
                <div class="box box-color box-bordered">
                    <div class="box-title">
                        <h3><i class="fa fa-th-list"></i> <?php echo $pagetitle; ?></h3>
                    </div>
                    <div class="box-content nopadding">
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate("global_name_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control input-sm width300" id="name" name="name" value="<?php echo $role->getName(); ?>" /><div id="name_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('global_description_label'); ?>:</label>
                            <div class="col-sm-9">
                                <textarea class="form-control expanding" id="description" name="description"><?php echo $role->getDescription(); ?></textarea>
                                <div id="description_error"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="box">
                    <div class="box-title">
                        <h3><i class="fa fa-cog"></i>Permissions Matrix</h3>
                    </div>
                    <div class="box-content nopadding">
                    	<table class="table margin0 table-bordered table-striped table-colored-header">
                        	<thead style="font-size:12px !important;">
                                <tr>
                                    <th class="nowrapping">Resources <img style="width:80px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>                    	
                                    <th class="nowrapping" style="width:7%;">All</th>
                                    <?php foreach($definedactions as $value){ ?>
                                    <th style="width:9%; text-align:center;"><?php echo $value == 'flag' ? 'Yes/No' : ucfirst($value); ?></th>
                                    <?php  }  ?> 
                                </tr>
                            </thead>
                            <tbody>
								<?php 
                                    $counter = 0;
									foreach($resourcearray as $resourceid => $resourceName) {
									// load the permission instance for the specified resource, since for each group and resource there is only one permission instance
									$theresource = new AclResource();
									$theresource->populate($resourceid);
									// debugMessage($theresource->toArray());
									$permission = $role->getPermissionForResource($resourceid); 
									// debugMessage($permission->toArray());
									
									if(!isEmptyString($permission->getID())){
										 $resource_ref = $counter;
									} else {
										$resource_ref = md5($resourceid); 
									} 
                                ?>
                                    <tr>
                                        <td class="xlabel"><?php echo $resourceName; ?>
                                            <input type="hidden" name="permissions[<?php echo $resource_ref; ?>][resourceid]" id="permissions_<?php echo $resource_ref; ?>_resourceid" value="<?php echo $resourceid; ?>" />
                                            <input type="hidden" name="permissions[<?php echo $resource_ref; ?>][id]" id="permissions_<?php echo $resource_ref; ?>_id" value="<?php echo $permission->getID(); ?>" />
                                            <input type="hidden" name="permissions[<?php echo $resource_ref; ?>][groupid]" id="permissions_<?php echo $resource_ref; ?>_groupid" value="<?php echo $role->getID(); ?>" /></td>
                                        <td><input name="allpermissionscheckbox" id="checkall_<?php echo $resourceid; ?>" type="checkbox" value="resource_<?php echo $resourceid; ?>" /></td>                     
                                        <?php 
                                            foreach($definedactions as $theaction) {
                                        ?>
                                            <td align="center">
                                            <?php if ($theresource->get($theaction) == 1) { ?>
                                                <input type="checkbox" name="chk<?php echo $theaction; ?>[]" id="chk<?php echo $theaction; ?>_<?php echo $resourceid; ?>" value="1" class="resource_<?php echo $resourceid; ?> resourcetrigger" <?php echo $permission->getCheckedStatus($theaction); ?>  />
                                                <input type="hidden" name="permissions[<?php echo $resource_ref; ?>][<?php echo $theaction; ?>]" id="<?php echo $theaction; ?>_<?php echo $resourceid; ?>" class="chk<?php echo $theaction; ?>_<?php echo $resourceid; ?> checkall_<?php echo $resourceid; ?>" value="<?php echo $permission->checkPermissionForAction($theaction); ?> " />
                                            <?php } ?>	
                                            </td>	
                                        <?php } ?>  
                                    </tr>
                            	<?php $counter++; } ?> 
                            </tbody>
                        </table>
                        <div class="divider10"></div>
                        <div class="form-actions testborder clearfix">
                        	<a class="btn cancel gonowhere" type="button"><?php echo $this->translate('global_button_cancel'); ?></a>
                    		<button class="btn btn-primary btn-green changesuccessurl savebutton" type="submit"><?php echo $button_title; ?></button>
                        </div>
                    </div>
               	</div>
          	</div>
       	</div>
	</form>
</div>    
                
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
