<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = "User Roles";
	$plural = $title;
	
	$style = '1';
	if(!isEmptyString($request->style)){
		$style = $request->style;
		$session->setVar('style', $request->style);
	}
	if(isEmptyString($request->style) && !isEmptyString($session->getVar('style'))){
		$style = $session->getVar('style');
	}
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("name","description"));
	$paginate->setDefaultSortBy("name");
	$paginate->setItemCountPerPage("ALL");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE d.id <> '' ";
	$allowclear = false;
	
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	$paginate->processPost($request->getParams());
	$all_results_query = "select r.id AS id, aug.groupid AS `groupid`, aug.userid AS `userid`, r.name AS `Name`, r.name AS `Group`, r.description AS Description from `aclgroup` `r` left join `aclusergroup` `aug` on(`r`.`id` = `aug`.`groupid`) WHERE name <> '' ".$paginate->getSearchAndFilterSQL()." GROUP BY id ".$paginate->getSortSQL();
	
	# debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	$listurl = $this->baseUrl('role/list');
	$addurl = $this->baseUrl('role');
	$listitems = $this->translate("role_list_items");
	$moduleitem = "Role";
	$resource = "Role";
	
	$description = '';
	$showsearch = true;
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
		$('.titlelabel').html('<?php echo $title; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="glyphicon glyphicon-cog"></span>');
		
	});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div class="row">
	<div class="col-sm-8">
		<div class="box box box-color box-bordered">
			<div class="box-title noheader">
                <h3></h3>
            </div>
            <div class="box-content nopadding">
                <div class="divider5"></div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="col-sm-8">
                            <ul class="resetlist listactions">
                                <?php if ($acl->checkPermission($resource, ACTION_CREATE)) { ?>
                                    <li><a class="btn btn-primary btn-sm" href="<?php echo $addurl; ?>"> New <?php echo $moduleitem; ?></a></li>
                                <?php } ?>
                            </ul>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                </div>
                <div class="divider5"></div>
                <table class="table table-nomargin table-bordered table-striped table-hover" id="datatable">
                	<thead>
                        <tr>
                            <th style="width:30%;">Name</th>
                            <th class="hidden-xs">Description</th>
                            <th class="hidden-xs" style="width:20%;">Actions</th>
                        </tr>
					</thead>
					<tbody>
                    	<?php
							foreach($result as $line){
								$viewurl = $this->baseUrl('role/view/id/'.encode($line['id']));
								$indexurl = $this->baseUrl('role/index/id/'.encode($line['id']));	
						?>
							<tr>
								<td class="nullifempty"><a href="<?php echo $viewurl; ?>" class="blockanchor"><?php echo $line['Name']; ?></a></td>
								<td class="hidden-xs nullifempty"><?php echo nl2br(snippet($line['Description'],250,'<a href="'.$viewurl.'">...more</a>')); ?></td>
								<td class="hidden-xs">
									<?php if ($acl->checkPermission($resource, ACTION_VIEW)) { ?>
                                        <a class="blockanchor btn" href="<?php echo $viewurl; ?>" title="View" rel="tooltip"><i class="fa fa-bars"></i></a>
                                    <?php } ?>
                                    <?php if ($acl->checkPermission($resource, ACTION_EDIT)) { ?>
                                        <a class="blockanchor btn" href="<?php echo $indexurl; ?>" title="Update" rel="tooltip"><i class="fa fa-edit"></i></a>
                                    <?php } ?>
								</td>
							</tr>
						<?php } ?>
                    </tbody>
                </table>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-actions">
                            <div class="col-sm-3 paddingleft5 floatleft"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                            <div class="col-sm-6 padding0"><?php echo $paginate->getPaginationLinks(); ?></div>
                            <div class="col-sm-3 padding0 rightalign"><?php echo $paginate->getListCountDropDown(); ?></div>
                        </div>
                    </div>
                </div>
                <div class="divider5"></div>
			</div>
		</div>
	</div>
</div>                                        
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
