<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$role = new AclGroup();
	#Populate or retrive the entry using the above id. 
	$role->populate(decode($request->id)); // debugMessage($role->toArray());
	
    $resourcearray = getResources();
	$definedactions = ACL::getActions();
	
	$pageid = "row_view";
	$description = "Permissions Matrix - ".$role->getName();
	$listurl = $this->baseUrl("role/list");
	$listitems  = "Roles";
	$title = 'User Permissions';
	$this->headTitle($role->getName().$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'User Role / '.$role->getName(); ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="glyphicon glyphicon-cog"></span>');
	
});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div id="<?php echo $pageid; ?>">
    <form id="indexform" name="viewform" class="form-horizontal">
        <div class="row">
            <div class="col-sm-12">
                <div class="box">
                    <div class="box-title">
                        <h3><i class="fa fa-cog"></i><?php echo $description; ?></h3>
                        <div class="actions">
                        	<?php if ($acl->checkPermission('Role', ACTION_EDIT)) { ?>	
                            	<a class="btn btn-primary" href="<?php echo $this->baseUrl('role/index/id/'.encode($role->getID())); ?>" title="Update" rel="tooltip"><i class="fa fa-edit"></i></a>
                            <?php } ?>
                            <?php if ($acl->checkPermission('Role', ACTION_DELETE)) { ?>	
                                <a class="deleteline btn btn-default" action="<?php echo $this->baseUrl('role/delete/id/'.encode($role->getID())."/entityname/AclGroup/successurl/".encode($listurl)); ?>" message="<?php echo $this->translate('global_delete_confirm_message'); ?>" title="Remove Entry" rel="tooltip"><i class="fa fa-trash"></i></a>
                            <?php } ?>
                            <?php if ($acl->checkPermission('Role', ACTION_LIST)) { ?>
                            	<a class="btn btn-default" href="<?php echo $listurl; ?>" title="All Roles" rel="tooltip"><i class="fa fa-arrow-right"></i></a>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="box-content nopadding">
                        <div class="divider5"></div>
                        <div class="row">
                            <div class="col-sm-12">
                                
                            </div>
                        </div>
                        <div class="divider5"></div>
                        <table class="table margin0 table-bordered table-striped table-colored-header">
                        	<thead style="font-size:12px !important;">
                                <tr>
                                    <th class="xlabel nowrapping">Resources <img style="width:80px; height:2px;" src="<?php echo $this->baseUrl('images/spacer.gif'); ?>" /></th>                    	
                                    <?php
                                        foreach($definedactions as $value) {
                                    ?>
                                    <th class="hidden-xs" style="width:9%; text-align:center;"><?php echo $value == 'flag' ? 'Yes/No' : ucfirst($value); ?></th>
                                    <?php 
                                        } // end creating the header column for each action
                                    ?> 
                                </tr>
                            </thead>
                            <tbody>
								<?php 
                                    foreach($resourcearray as $resourceid => $resourceName) {
                                    // load the permission instance for the specified resource, since for each group and resource there is only one permission instance
                                    $theresource = new AclResource();
                                    $theresource->populate($resourceid);
                                    //debugMessage($resource->toArray());
                                    $permission = $role->getPermissionForResource($resourceid); 
                                ?>
                                    <tr>
                                        <td class="xlabel"><?php echo $resourceName; ?></td>                            
                                        <?php foreach($definedactions as $theaction) { ?>
                                            <?php if($theresource->get($theaction) == 1) { ?>
                                                <td align="center hidden-xs">
                                                    <?php echo ($permission->checkPermissionForAction($theaction) ? 
                                                    '<i class="fa fa-check btn btn-green" title="Granted" rel="tooltip"></i>' : 
                                                    '<i class="fa fa-remove btn" title="Denied" rel="tooltip"></i>');  
                                                    ?>
                                                </td>                        
                                            <?php } else { ?>
                                                <td align="center hidden-xs">&nbsp;</td>     
                                            <?php } ?>
                                        <?php } ?>  
                                    </tr>
								<?php } ?> 
                            </tbody>
                        </table>
                        <div class="divider10"></div>
                        <div class="form-actions testborder clearfix">
                        	<?php if ($acl->checkPermission('Role', ACTION_EDIT)) { ?>	
                            	<a class="btn btn-primary pull-right" href="<?php echo $this->baseUrl('role/index/id/'.encode($role->getID())); ?>" title="Update" rel="tooltip">Update Settings</a>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>  
    </form>
</div>                                                  
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>