<?php
	require_once APPLICATION_PATH.'/includes/commonfunctions.php';
?>
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<!-- Apple devices fullscreen -->
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<!-- Apple devices fullscreen -->
	<meta names="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headMeta(); ?>
    <?php
		# <!-- Include stylesheets that failed minification  -->		
		$this->headLink()->appendStylesheet($this->baseUrl('stylesheets/bootstrap.min.css')); 
		echo $this->headLink();
		
		$cssfiles = getStyleIncludes();
		foreach ($cssfiles as $css) {
			// use baseURL() to output the full URL of the cached file and use it as normal with headLink()
			$this->minifyHeadLink()->appendStylesheet($css);
		}
		echo $this->minifyHeadLink(); 
		
		# <!-- Include application javascript and minify -->
		$jsfiles = getJsIncludes();
		foreach ($jsfiles as $js) {
			// use baseURL() to output the full URL of the cached file and use it as normal with headLink(). also use setFile so that each file is added
			$this->minifyHeadScript()->appendFile($js);
		}  
		// echo $this->minifyHeadScript();
		
		$jsfiles = getJsIncludes2();
		foreach ($jsfiles as $js) {
			// use baseURL() to output the full URL of the cached file and use it as normal with headLink(). also use setFile so that each file is added
			$this->minifyHeadScript()->appendFile($js);
		}  
		echo $this->minifyHeadScript();
		
		$request = Zend_Controller_Front::getInstance()->getRequest();
		$controller = $request->getControllerName();
		$action = $request->getActionName();

		$session = SessionWrapper::getInstance();		
		$companyid = isEmptyString($session->getVar('companyid')) ? DEFAULT_COMPANYID :  $session->getVar("companyid");
		
		$bodyclasses = "";
		$fulltemplate = true;
		if($controller == 'user' && $action == 'login'){
			$fulltemplate = false;
			$bodyclasses .= "login ";
		}
		$isprint = false;
		if($request->print == '1' || $request->fullscreen == '1'){
			$fulltemplate = false; $isprint = true;
			$bodyclasses .= "print ";
		}
		
		$default_theme_data = getDefaultThemeOptions(DEFAULT_COMPANYID); // debugMessage($default_theme_data);
		$current_theme_data = getDefaultThemeOptions($companyid, $default_theme_data); // debugMessage($current_theme_data);
		// theme layout options
		$layout_options = array(1=>'fluid', 2=>'fixed'); $layout = $current_theme_data['layout'];
		if(!isEmptyString($request->layout)){
			$layout = $request->layout;
			$session->setVar('layout', $request->layout);
		}
		
		$topbar_options = array(1=>'default',2=>'fixed'); $topbar = $current_theme_data['topbar'];
		if(!isEmptyString($request->topbar)){
			$topbar = $request->topbar;
			$session->setVar('topbar', $request->topbar);
		}
		
		$sidebar_options = array(1=>'default', 2=>'fixed'); $sidebar = $current_theme_data['sidebar'];
		if(!isEmptyString($request->sidebar)){
			$sidebar = $request->sidebar;
			$session->setVar('sidebar', $request->sidebar);
		}
		
		// show or hide sidebar
		$showsidebar = $current_theme_data['showsidebar'];
		if(!isEmptyString($request->showsidebar)){
			$show_sidebar = $request->showsidebar;
			$session->setVar('showsidebar', $request->showsidebar);
		}
		
		$colortheme = $current_theme_data['colortheme']; $attr = "";
		if(!isEmptyString($request->colortheme)){
			$colortheme = $request->colortheme;
			$session->setVar('colortheme', $request->colortheme);
		}
		if(!isEmptyString($colortheme)){
			$bodyclasses .= "theme-".$colortheme." ";
			$attr = ' data-theme="theme-'.$colortheme.'"';
		}
	?>
   
	<!--[if lte IE 9]>
		<script src="javascript/plugins/placeholder/jquery.placeholder.min.js"></script>
		<script>
			$(document).ready(function() {
				$('input, textarea').placeholder();
			});
		</script>
	<![endif]-->
    
    <!-- Favicon -->
    <link href="<?php echo $this->baseUrl('favicon.ico'); ?>" rel="shortcut icon" type="image/x-icon" />
	<!-- Apple devices Homescreen icon -->
	<link rel="apple-touch-icon-precomposed" href="<?php echo $this->baseUrl('images/apple-touch-icon-precomposed.png'); ?>" />
    
    <?php require_once APPLICATION_PATH.'/views/scripts/index/layoutjs.phtml'; ?>
</head>    
<body class="<?php echo $bodyclasses; ?>" <?php echo $attr; ?>>
	<?php if($isprint){ ?> 
    	<a onClick="window.close()"><i class="fa fa-times"></i></a>&nbsp; 
        <a onClick="window.print()"><i class="fa fa-print"></i></a>
    <?php } ?>
	<?php if($fulltemplate){ ?>
		<?php require_once APPLICATION_PATH.'/views/scripts/index/header.phtml'; ?> <!-- Include header -->
        <div class="<?php echo $layout == 1 ? 'container-fluid' : 'container'; ?> <?php echo $topbar == 2 ? 'nav-fixed' : ''; ?>" id="content">
            <div id="left" class="<?php echo $sidebar == 2 ? 'sidebar-fixed hasScrol ' : ' '; ?> <?php echo $showsidebar == 0 ? 'forced-hide ' : ' '; ?>" style="display:<?php echo $showsidebar == 0 ? 'none;' : 'block'; ?>">
                <?php require_once APPLICATION_PATH.'/views/scripts/index/leftcolumn.phtml'; ?>
            </div>
            <div id="main" style="margin-left:<?php echo $showsidebar == 0 ? '0;' : '200px;'; ?>">
                <div class="container-fluid">
                    <?php require_once APPLICATION_PATH.'/views/scripts/index/breadcrumb.phtml'; ?> <!-- Breadcrumbs line -->
                    <?php echo $this->layout()->content; ?>
                </div>
            </div>
        </div>
    <?php } else { ?>
    	<?php echo $this->layout()->content; ?>
    <?php } ?>
    <?php require_once APPLICATION_PATH.'/views/scripts/index/hiddenbydefault.phtml'; ?> <!-- hidden by default -->
</body>
</html>    