<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>

<p>Dear <?php echo $this->firstname; ?>,</p>

<p>This email confirms that your account on <?php echo $this->appname; ?> has been deactivated.</p>

<p>We're sorry you will no longer be using <?php echo $this->appname; ?>.</p>

<p>If you need any further assistance or have any question, please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a></p>

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>