<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>

<p>Dear <?php echo $this->firstname; ?>,</p>

<p>You recently requested to change your <b><?php echo $this->appname; ?></b> Email Address to <b><?php echo $this->toemail; ?></b>.</p>

<p>To confirm this request, click on the activation link below:<br />
<?php echo $this->activationurl; ?></p>

<p>If the page fails to open, copy the activation link and paste it in the address window of the browser.</p>

<p>On confirmation, you will no longer be able to login using <b><?php echo $this->fromemail; ?></b>.</p>

<p>If you need any further assistance or have any question, please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a></p>

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>
            