<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>

<p>Dear Admin,</p>

<p>New <?php echo $this->appname; ?> Contact Form message has been received with the following details;</p>
<p><b>Name: </b><?php echo $this->name; ?></p>
<p><b>Email: </b><?php echo $this->email; ?></p>
<p><b>Subject: </b><?php echo $this->subject; ?></p>
<p><b>Message: </b><?php echo $this->message; ?></p>

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>