        					</td>
                        </tr>
                    </table>
                </center>
            </td>
        </tr>
    </table>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="<?php echo $this->themecolor; ?>">
		<tr>
			<td align="center">
				<center>
					<table border="0" width="600" cellpadding="0" cellspacing="0">
						<tr>
							<td style="color:#ffffff !important; font-size:20px; font-family: Arial, Verdana, sans-serif; padding-left:10px;" height="40">
								<center>
									<p style="font-size:12px; line-height:18px; color:#fff; text-decoration:none;">
									If you don't want to get system emails from <?php echo $this->appname; ?> please change your email settings.
									<br />
									<a href="<?php echo $this->settingsurl; ?>" style="color:#ffffff !important;">Click here to change email settings</a>
								</p>
								</center>
							</td>
						</tr>
					</table>
				</center>
			</td>
		</tr>
	</table>
</body>
</html>