        					</td>
                        </tr>
                    </table>
                </center>
            </td>
        </tr>
    </table>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" bgcolor="<?php echo $this->themecolor; ?>">
		<tr>
			<td align="center">
				<center>
					<table border="0" width="600" cellpadding="0" cellspacing="0">
						<tr>
							<td style="color:#ffffff !important; font-size:20px; font-family: Arial, Verdana, sans-serif; padding-left:10px;" height="40">
								<center>
									<p style="font-size:12px; line-height:18px; color:#fff; text-decoration:none;">
									This is an automated notification from <a href="<?php echo $this->loginurl; ?>" style="color:#fff;"><?php echo $this->appname; ?></a>
									and you do not need to reply to it. <br />You can <a href="<?php echo $this->contactusurl; ?>" style="color:#fff;">contact us here</a> incase if you have any concerns or are receiving this email in error.
								</p>
								</center>
							</td>
						</tr>
					</table>
				</center>
			</td>
		</tr>
	</table>
</body>
</html>