<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>

<h3 style="font-weight:normal; margin: 20px 0;"><?php echo $this->subject; ?></h3>

<p>Dear <?php echo $this->firstname; ?>,</p>

<?php echo $this->contents; ?>

<p>To activate your account, <a href="<?php echo $this->invitelink; ?>">click here</a> or alternatively copy the activation link below and paste it in the address window of the browser.<br />
<?php echo $this->invitelink; ?></p>

<p>After activating your account, you will be able to login using the your email/username and password.</p>
                        
<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>
