<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>
<p>Dear <?php echo $this->firstname; ?>,</p>

<p>A request has been made for a new password for your <?php echo $this->company_app_name; ?> Account. </p>

<p>You can set a new password by <a href="<?php echo $this->resetpasswordurl; ?>">clicking here</a> or follow the link below:<br />
<?php echo $this->resetpasswordurl."\n"; ?></p>

<p>If you need any further assistance or have any question, please feel free to <a href="<?php echo $this->serverUrl($this->baseUrl('contactus')); ?>" title="Contact us">Contact us</a></p>

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>