<?php include(APPLICATION_PATH.'/views/scripts/email/emailheader.phtml'); ?>
<h3 style="font-weight:normal; margin: 20px 0;"><?php echo $this->subject; ?></h3>

<p>Dear <?php echo $this->firstname; ?>,</p>

<?php if($this->type == 3){ ?>
	<?php echo $this->contents; ?>
    <?php if($this->requiresapproval == 0 || ($this->requiresapproval == 1 && $this->isapproved == 1)){ ?>
        <p>To activate your account, <a href="<?php echo $this->activationurl; ?>" style="display:inline;">click here</a> or alternatively copy the activation link below and paste it in the address window of the browser.<br />
        <?php echo $this->activationurl; ?></p>

        <p>After activation, you will be able to login using the your email/username and the password you provided during registration.</p>
    <?php } ?>
<?php } ?>

<?php include(APPLICATION_PATH.'/views/scripts/email/emailfooter.phtml'); ?>
