<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = "Departments";
	
	$style = '2';
	if(!isEmptyString($request->style)){
		$style = $request->style;
		$session->setVar('style', $request->style);
	}
	if(isEmptyString($request->style) && !isEmptyString($session->getVar('style'))){
		$style = $session->getVar('style');
	}
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("d.name"));
	$paginate->setDefaultSortBy("d.name");	
	$paginate->setItemCountPerPage("ALL");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE d.id <> '' ";
	$allowclear = false;
	
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	$department_query = "";
	if(!isEmptyString($request->companyid)){
		$companyid = $request->companyid;
	}
	if(!isEmptyString($companyid)){
		if($companyid == DEFAULT_COMPANYID){
			$department_query = " AND (d.companyid = '".$companyid."' OR d.companyid is null) ";
		} else {
			$department_query = " AND d.companyid = '".$companyid."' ";
		}
	}
		
	$paginate->processPost($request->getParams());
	$all_results_query = "select d.id as id, d.name, d.description, d.headid, concat(u.firstname,' ',u.lastname) as manager from department d left join useraccount u on d.headid = u.id WHERE d.name <> '' ".$department_query." ".$paginate->getSearchAndFilterSQL()." GROUP BY d.id ".$paginate->getSortSQL();
	
	// debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	$listurl = $this->baseUrl('department/list');
	$addurl = $this->baseUrl('department/index');
	$moduleitem = "Department";
	$resource = "Departments"; // $resource = "Department";
	$icon = "glyphicon glyphicon-cog";
	
	$description = 'List of Company Departments';
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
		$('.titlelabel').html('<?php echo $title; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
		
	});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div class="row">
	<div class="col-sm-8">
		<div class="box box box-color box-bordered">
			<div class="box-title noheader">
                <h3></h3>
            </div>
            <div class="box-content nopadding">
                <div class="divider5"></div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="col-sm-8">
                            <ul class="resetlist listactions">
                                <?php if ($acl->checkPermission($resource, ACTION_CREATE)) { ?>
                                    <li><a class="btn btn-primary btn-sm" href="<?php echo $this->baseUrl('department/index'); ?>"> New Department</a></li>
                                <?php } ?>
                            </ul>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                </div>
                <div class="divider5"></div>
                <table class="table table-nomargin table-bordered table-striped table-hover" id="datatable">
					<thead>
                        <tr>
                            <th>Name</th>
                            <th class="hidden-xs" style="width:200px;">Number of Employees</th>
                            <th class="hidden-xs">Manager / Supervisor</th>
                            <th style="width:125px;">Actions</th>
                        </tr>
					</thead>
					<tbody>
                    	<?php if($has_no_data){ ?>
                        	<tr><td colspan="20"><div class="alert alert-warning"><?php echo $this->translate("global_list_noentries"); ?></div></td></tr>
                        <?php } ?>
                    	<?php
							foreach($result as $line){
								$viewurl = $this->baseUrl('department/view/id/'.encode($line['id']));
								$indexurl = $this->baseUrl('department/index/id/'.encode($line['id']));
								
								$manager = '';
								if(!isEmptyString($line['headid'])){
                                    $manager = '<a href="'.$this->baseUrl('profile/view/id/'.encode($line['headid'])).'" class="blockanchor inline">'.$line['manager'].'</a>';
                                } 
								
								$sql = "select count(id) from useraccount where departmentid = '".$line['id']."' ";
								$conn = Doctrine_Manager::connection(); 
								$result = $conn->fetchOne($sql);
								$numberofemps = $result;
								
						?>
                            <tr>
                                <td><?php echo $line['name']; ?></td>
                                <td class="hidden-xs"><?php echo $numberofemps; ?></td>
                                <td class="hidden-xs"><?php echo $manager; ?></td>
                                <td>
                                	<?php if ($acl->checkPermission($resource, ACTION_EDIT)) { ?>
                                        <a class="btn" href="<?php echo $this->baseUrl('department/index/id/'.encode($line['id'])); ?>" rel="tooltip" title="Update"><i class="fa fa-edit"></i></a> &nbsp;
                                    <?php } ?>
                                    <?php if ($acl->checkPermission($resource, ACTION_DELETE)) { ?>
                                        <a class="btn deleteline" action="<?php echo $this->baseUrl('department/delete/id/'.encode($line['id'])."/entityname/Department/successurl/".encode($this->viewurl)); ?>" rel="tooltip" message="<?php echo $this->translate('global_delete_confirm_message'); ?>" title="Delete"><i class="fa fa-times"></i></a>
                                    <?php } ?>
                                </td>
                            </tr>
                       	<?php } ?>
					</tbody>
				</table>
                <?php if(!$has_no_data){ ?>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-actions">
                                <div class="col-sm-3 paddingleft5 floatleft"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                                <div class="col-sm-6 padding0"><?php echo $paginate->getPaginationLinks(); ?></div>
                                <div class="col-sm-3 padding0 rightalign"><?php echo $paginate->getListCountDropDown(); ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="divider5"></div>
                <?php } ?>
			</div>
		</div>
	</div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
