<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$ledger = new Ledger();
	if(isEmptyString($request->id)){
		if(!isEmptyString($request->userid)){
			$ledger->setUserID(decode($request->userid));
		}
		$ledger->setTrxnDate(date('Y-m-d'));
		$ledger->setStatus('0');
		$ledger->setLedgerType(1);
		$ledger->setTrxnType(1);
		$ledger->setAmount('');
		$successmessage = "Successfull Submitted for Approval";
	} else { 
		$ledger->populate(decode($request->id)); 
		$successmessage = "Update Successfull";
	}
	
	$benefittypes = getBenefitTypes();
	$trxtypes = getTrxnTypes();
	$benefits = getBenefits(); // debugMessage($benefits);
	// debugMessage($ledger->toArray());
?>
<?php require APPLICATION_PATH."/views/scripts/index/pgcjs.phtml"; ?>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/custom/jquery.form.min.js')); ?>"></script>
<script>
$(document).ready(function() {	
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			userid: "required",
			benefitid: "required",
			trxndate: "required",
			amount: {
				required: true
			},
			remarks: "required"
		}, 
		// the messages for each of the fields being validated
		messages: {				
			userid: "Please select a User",
			benefitid: "Please select Category",
			trxndate: "Please select a Date",
			amount: {
				required: "Please enter Amount"
			}, 
			remarks: "Please enter Remarks"
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					error.appendTo("#"+element.attr("name")+"_error")
					break;
			}			
		}
	});
	
	var options = { 
		target:   '#output',   // target element(s) to be updated with server response 
		beforeSubmit:  beforeSubmit,  // pre-submit callback 
		success:       afterSuccess,  // post-submit callback 
		uploadProgress: OnProgress, //upload progress callback 
		resetForm: true        // reset the form after successful submit 
	}; 
		
	$("#FileInput").change(function(){
		var filename = $(this).val(); // alert('file is '+filename);								
		$("#filenamedisplay").html(filename);
		// upload the file to the server
		$("#uploadform").ajaxSubmit(options); 
	});  
	
	$('#filenamedisplay').click(function(){
		$("#FileInput").trigger('click');
	});		
	
	$('#re-upload').click(function(){
		$("#aftersave").hide().addClass('hidden');
		$("#beforesave").show().removeClass('hidden');
		$("#filename, #FileInput, #attachment, #attachment_display").val('');
		$("#uploadresult, #output").html('');
	});
	
	//function after succesful file upload (when server response)
	function afterSuccess() {
		$('#submit-btn').show(); //hide submit button
		$('#loading-img').hide(); //hide submit button
		$('#progressbox').delay(400).fadeOut(); //hide progress bar
		$("#filenamedisplay").html('');
		// alert($("#output").html()); return false;
		var data = $.parseJSON($("#output").html());
		// alert(data.msg);
		if(data.result == 1){
			$("#output, #FileInput_error, #filename_error ").hide();	
			$('#uploadresult').html('<div class="divider5"></div><span class="font-green">Successfully uploaded!</span>').removeClass('hidden');
			$("#indexform #filename").val(data.newfilename);
			$("#attachment").val(data.oldfilename);
			$("#filesize").val(data.filesize);
			$("#attachment_display, #aftersave").show().removeClass('hidden');
			$("#attachment_display").html(data.newfilename);
			$("#beforesave").hide().addClass('hidden');
		} else {
			$("#uploadresult").html('Error in uploading file. Invalid format');	
		}
	}
	
	//function to check file size before uploading.
	function beforeSubmit(){
		//check whether browser fully supports all File API
	   if (window.File && window.FileReader && window.FileList && window.Blob){
			$('#loading-img').show(); //hide submit button
			$("#output").html("");
		} else {
			//Output error to older unsupported browsers that doesn't support HTML5 File API
			$("#output").html("Please upgrade your browser. File upload not supported at this time.");
			return false;
		}
	}
	
	//progress bar function
	function OnProgress(event, position, total, percentComplete){
		//Progress bar
		$('#progressbox').show();
		$('#progressbar').width(percentComplete + '%') //update progressbar percent complete
		$('#statustxt').html(percentComplete + '%'); //update status text
		if(percentComplete > 50) {
			$('#statustxt').css('color','#000'); //change status text to white after 50%
		}
	}
});
</script>
<div class="alert alert-info" style="margin: 0; margin-top:-15px;">Use this form to request additional benefits. Note that Approval is required!</div>
<div class="popupdiv">
    <fieldset class="fieldsetcontainer" style="margin-bottom:0;">
        <div class="panel-body well-sm" style="min-height:150px;">
            <div class="row-fluid marginleft5">
                <div class="col-sm-12 paddingleft10">
                <form id="indexform" class="form-horizontal profile" role="form" method="post">
                    <input name="entityname" id="entityname" type="hidden" value="Timesheet" />
                    <input type="hidden" name="userid" id="userid" value="<?php echo $ledger->getUserID(); ?>" />
                    <input type="hidden" name="status" id="status" value="<?php echo $ledger->getStatus(); ?>" />
                    <input type="hidden" name="ledgertype" id="ledgertype" value="<?php echo $ledger->getledgertype(); ?>" />
                    <input type="hidden" name="trxntype" id="trxntype" value="<?php echo $ledger->gettrxntype(); ?>" />
                    <input type="hidden" id="id" name="id" value="<?php echo encode($ledger->getID()); ?>" />
                    <input name="successmessage" id="successmessage" type="hidden" value="<?php echo $successmessage; ?>" />  
                    <input name="isrequest" id="isrequest" type="hidden" value="1" />  
                    <?php if(isAdmin() || $acl->checkPermission('Benefits', ACTION_APPROVE)){ ?>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('leave_user_label'); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-9">
                                <?php if(isEmptyString($ledger->getID())){ ?>
                                    <?php
                                        $allvalues = getUsers();
                                        $dropdown = new Zend_Form_Element_Select('userid',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('form-control','input-sm','width200','chosen-select')
                                                            )
                                        );  
                                        $dropdown->setValue($ledger->getUserID()); 
                                        echo $dropdown->render();
                                    ?>
                                <?php } else { ?>
                                    <?php echo $ledger->getUser()->getName(); ?>
                                    <input type="hidden" id="userid" name="userid" value="<?php echo $ledger->getUserID(); ?>" />
                                <?php } ?>
                                <div id="userid_error"></div>
                            </div>
                        </div>
                    <?php } else { ?>
                        <input type="hidden" id="userid" name="userid" value="<?php echo $ledger->getUserID(); ?>" />
                    <?php } ?>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Date: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control input-sm datefield readonly width100 ordinary" name="trxndate" id="trxndate" value="<?php echo changeMySQLDateToPageFormat($ledger->gettrxndate()); ?>" /><div id="trxndate_error"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Category: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-sm-9">
                            <?php
                                $dropdown = new Zend_Form_Element_Select('benefitid',
                                                    array(
                                                        'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $benefits),
                                                        'view' => new Zend_View(),
                                                        'decorators' => array('ViewHelper'),
                                                        'class' => array('form-control','input-sm','width200')
                                                    )
                                );  
                                $dropdown->setValue($ledger->getBenefitID()); 
                                echo $dropdown->render();
                            ?>
                            <div id="benefitid_error"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Amount: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-sm-9">
                            <input type="text" name="amount" id="amount" class="form-control input-sm isnumber centeralign width100 inline" value="<?php echo $ledger->getAmount(); ?>" />
                            &nbsp; (<?php echo $config->country->currencycode; ?> Amount)
                            <div id="amount_error"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Remarks: <?php echo $this->translate("global_required_field_marker"); ?></label>
                        <div class="col-sm-9">
                            <textarea name="remarks" id="description" class="form-control input-sm expanding"><?php echo $ledger->getRemarks(); ?></textarea>
                            <div id="remarks_error"></div>        
                            <input type="text" name="filename" id="filename" class="hidden" value=">" />
                            <input type="hidden" name="attachment" id="attachment" value="" />
                        </div>
                    </div>
                    </form>
                    <form id="uploadform" class="form-horizontal profile" role="form" action="<?php echo $this->baseUrl('ledger/upload'); ?>" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="userid" id="userid" value="<?php echo $ledger->getUserID(); ?>" />
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Attachment:</label>
                            <div class="col-sm-9">
                                <div id="profilephoto_error"></div>
                                <input type="text" name="filename" id="filename" value="" style="border:1px solid #fff; height:1px; padding:0; background:none; border-style:none; box-shadow:none;" />
                                <div id="uploadarea" style="margin-bottom:10px;">
                                    <label class="blocked" style="font-size:10px;">Upload an a file (Max size <?php echo formatBytes($config->uploads->docmaximumfilesize); ?>)</label>
                                    <div id="beforesave">
                                        <div class="fileinput-holder input-group col-sm-8" style="padding-left:0;">
                                            <div id="filenamedisplay" style="cursor: text; text-overflow: ellipsis; " class="fileinput-preview uneditable-input form-control">No file selected...</div>
                                            <div class="input-group-btn">
                                                <span style="overflow: hidden; position: relative; cursor: pointer; margin:0;" class="fileinput-btn btn btn-default">Browse...
                                                    <input type="file" name="FileInput" id="FileInput" class="form-control inline" data-style="fileinput" style="position: absolute; top: 0px; right: 0px; margin: 0px; cursor: pointer; font-size: 99px; opacity: 0;" />
                                                </span>
                                            </div>
                                        </div>
                                        <div class="col-sm-2 padding0">
                                            <img src="<?php echo $this->baseUrl('images/loader.gif'); ?>" id="loading-img" style="display:none;" />
                                        </div>                                                    	
                                    </div>
                                    <div id="aftersave" class="hidden">
                                        <div class="col-sm-12" style="padding-left:0;"><span id="attachment_display"></span></div>
                                        <button type="button" id="re-upload" class="btn btn-default btn-xs">Re-upload</button>
                                    </div>
                                    <div class="divider5"></div>
                                    <div id="progressbox"><div id="progressbar"></div><div id="statustxt">0%</div></div>
                                    <div id="output"></div><div id="uploadresult" class="hidden"></div>
                                    <div id="filename_error"></div><div id="FileInput_error"></div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </fieldset>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>