<div class="row">
    <div class="col-sm-12">
        <fieldset class="fieldsetcontainer">
            <legend>Account Setup</legend>
            <div class="panel-body well-sm">
                <div class="row-fluid">
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate("profile_type_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-8">
                                <?php
                                    $allvalues = getUserType();
									if(isCompanyAdmin()){
										unset($allvalues[1]);
										$allvalues[3] = "Administrator";
									}
                                    $dropdown = new Zend_Form_Element_Select('type',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','width200')
                                                        )
                                    );  
                                    $dropdown->setValue($user->getType()); 
                                    echo $dropdown->render();
                                ?><div id="type_error"></div>
                                <input type="hidden" name="type_old" id="type_old" value="<?php echo $user->getType(); ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">Email: <?php //echo $this->translate("global_required_field_marker"); ?>
                            <span class="pagedescription blocked nobolded">Only if user will have to Login</span>
                            </label>
                            <div class="col-sm-8">
                                <?php if($user->isUserActive()){ ?>
                                    <?php echo $user->getEmail(); ?>
                                    <input type="hidden" name="email" id="email" value="<?php echo $user->getEmail(); ?>" />
                                <?php } else { ?>
                                        <input type="hidden" name="oldemail" id="oldemail" value="<?php echo $user->getEmail(); ?>" />
                                        <input type="text" class="form-control input-sm width225 inline clearnew" id="email" name="email" value="<?php echo $user->getEmail(); ?>" />
                                        <a class="btn btn-sm btn-default gonowhere" id='check_email_availability' title="Check Availability">Check</a>
                                        <div class="divider2"></div>
                                        <div id="email_availability_result"></div>
                                        <?php if($user->isUserInActive()){ ?>
                                            <label class="checkbox-inline"><input type="checkbox" name="isinvited" id="isinvited" value="1" <?php //echo !isEmptyString($user->getID()) ? '' : 'checked="checked"'; ?> /> <?php echo isEmptyString($user->getID()) ? 'Send' : 'Resend' ?> activation email now:</label>
                                        <?php } ?>
                                        <div id="email_error"></div>
                                <?php } ?>
                            </div>
                        </div>
                        <?php if($user->isUserActive()){ ?>
                            <div class="form-group">
                                <label class="col-sm-4 control-label"><?php echo $this->translate("profile_username_label"); ?>: <?php echo isEmptyString($user->getID()) ? '' : $this->translate("global_required_field_marker"); ?>
                                    <span class="pagedescription blocked nobolded">To be used as Login</span>
                                </label>
                                <div class="col-sm-8">
                                    <input type="text" class="form-control input-sm width225 inline clearnew" id="username" name="username" value="<?php echo $user->getUserName(); ?>" /> <a class="btn btn-sm btn-default gonowhere" id='check_username_availability' style="margin-top:2px;" title="Check Availability">Check</a>
                                    
                                    <div id="username_availability_result" style="margin-top:4px"></div>
                                    <div id="username_error"></div>
                                </div>
                            </div>
                        <?php } ?>
                    </div>   
                </div>
                
            </div>
        </fieldset>
        <div class="divider10"></div>
    </div>
    <link rel="stylesheet" href="<?php echo $this->serverUrl($this->baseUrl('stylesheets/plugins/icheck/all.css')); ?>">
	<script src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/icheck/jquery.icheck.min.js')); ?>"></script>
    <style>
        .check-line  {
            display:block;
        }
        .check-line .inline {	
            width:100%; left:25px; top:-2px;
        }
        .fa.checker {
            background-color:#333;
            color:#fff;
            font-size:12px;
            padding:5px;
            margin-right:15px;
        }
        .fa.checker.unchecked {
            padding:5px 6px;
        }
    </style>
    <div class="col-sm-12">
        <fieldset class="fieldsetcontainer">
            <legend>Preferences</legend>
            <div class="panel-body well-sm">
                <div class="row-fluid">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <div class="col-sm-12">
                                <?php 
                                    $preferrances = getUserPreferrenceOptions();
                                ?>
                                <?php foreach($preferrances as $key => $preferrance){ 
                                    $currentvalue = $user->get($key, true); // debugMessage($currentvalue);
                                ?>
                                    <div class="check-line">
                                    	<input type="checkbox" id="<?php echo $key; ?>" name="<?php echo $key; ?>" value="1" class="icheck-me" data-skin="square" data-color="blue" <?php echo $currentvalue == 1 ? 'checked' : ''; ?>>
                                        <input type="hidden" id="<?php echo $key.'_old'; ?>" name="<?php echo $key.'_old'; ?>" value="<?php echo $currentvalue; ?>" />
                                        <label class='inline' for="<?php echo $key; ?>">
                                            <p class="form-control-static nullifempty view inline bolded"><?php echo $preferrance; ?></p>
                                        </label>
                                    </div>
                                    <?php if($key == 'emailon_leave_approvalcompleted' || $key == 'emailon_leave_approvalrequired'){ ?>
                                        <div class="divider30"></div>
                                    <?php } ?>
                                <?php } ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>