<div class="row">
	<div class="xmakeabsolute">
		<?php if($allowedit) { ?>
            <a class="btn btn-primary blockanchor" href="<?php echo $this->baseUrl('profile/index/id/'.encode($user->getID()).'/tab/account'); ?>">Update</a>
            <?php if($user->isUserInActive()){ ?>
            	<a class="btn btn-default confirm-dialog" message="Resend activation instructions to User's Email?" action="<?php echo $this->baseUrl('profile/inviteuser/id/'.$user->getID().'/successurl/'.encode($this->viewurl)); ?>">&nbsp; Resend Activation</a>
            <?php } ?>
        <?php } ?>
        <?php if($allowedit){ ?>
            <a class="btn btn-grey blockanchor" href="<?php echo $this->baseUrl('profile/picture/id/'.encode($user->getID())); ?>">Upload Photo</a>
        <?php } ?>
        <?php if($acl->checkPermission($resourcename, ACTION_DELETE) && $user->isDeactivated() && !$isme){ ?>
            <a class="btn btn-success confirm-dialog" action="<?php echo $this->baseUrl("profile/updatestatus/id/".encode($user->getID())."/status/1/successmessage/profile_reactivate_success/successurl/".encode($this->viewurl)); ?>" message="<?php echo $this->translate('profile_reactivate_confirmation'); ?>"> Re-Activate Account</a>
        <?php } ?>
        <?php if($acl->checkPermission($resourcename, ACTION_DELETE) && $user->isUserActive() && !$user->isDeactivated() && !$isme){ ?>
           <a class="btn btn-orange confirm-dialog" action="<?php echo $this->baseUrl("profile/updatestatus/id/".encode($user->getID())."/status/2/successmessage/profile_deactivate_success/successurl/".encode($this->viewurl)); ?>" message="<?php echo $this->translate('profile_deactivate_confirmation'); ?>">De-Activate Account</a>
        <?php } ?>
        <?php if($acl->checkPermission($resourcename, ACTION_DELETE) && !$user->isUserActive() && !$isme && false){ ?>
            <a class="btn btn-danger confirm-dialog" message="<?php echo $this->translate('global_delete_confirm_message'); ?>" action="<?php echo $this->baseUrl($controller.'/delete/id/'.encode($user->getID())."/entityname/UserAccount/successurl/".encode($listurl)); ?>">Delete Account</a>
        <?php } ?>
    </div>
    <div class="col-sm-12 paddingleft0">
        <fieldset class="fieldsetcontainer">
            <legend>Account Settings</legend>
            <div class="panel-body well-sm">
                <div class="row-fluid">
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $this->translate('profile_type_label'); ?>:</label>
                            <div class="col-sm-10">
                                <p class="form-control-static nullifempty view"><?php echo getUserType($user->getType()); ?></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $this->translate('profile_employmentstatus_label'); ?>:</label>
                            <div class="col-sm-10"><p class="form-control-static nullifempty view"><?php echo $user->getEmploymentStatus() == 1 ? 'Active' : 'Discontinued'; ?></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Account Login Status:</label>
                            <div class="col-sm-10">
                                <?php $allstatus = getUserStatus(); ?> 
                                <p class="form-control-static nullifempty view"><?php echo isArrayKeyAnEmptyString($user->getStatus(), $allstatus) ? '' : $allstatus[$user->getStatus()]; ?></p>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-2 control-label">Login <?php echo $this->translate('profile_emailonly_label'); ?>:</label>
                            <div class="col-sm-10">
                                <p class="form-control-static nullifempty view"><?php echo $user->getEmail(); ?>
                                <?php if($user->isUserActive() && $isme){ ?>
                                    <a href="<?php echo $this->baseUrl('profile/changeemail/id/'.encode($user->getID()).'/pgc/true'); ?>" class="addpopup changeemail btn btn-xs btn-default pull-right floatright" title="Change Email" rel="Change Email" id="changeemail" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl($controller."/processchangeemail"); ?>">Change Email</a>
                                <?php } ?>
                                </p>
                            </div>
                        </div>
                        <?php if($user->isUserActive()){ ?>
                        	<div class="form-group">
                            <label class="col-sm-2 control-label"><?php echo $this->translate('profile_username_label'); ?>:</label>
                                <div class="col-sm-10">
                                    <p class="form-control-static nullifempty view"><?php echo $user->getUsername(); ?>
                                    <?php if($user->isUserActive() && $isme){ ?>
                                        <a href="<?php echo $this->baseUrl('profile/changeusername/id/'.encode($user->getID()).'/pgc/true'); ?>" class="addpopup changeusername btn btn-xs btn-default pull-right floatright" title="Change Username" rel="Change Username" id="changeusername" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("profile/processchangeusername"); ?>">Change Username</a>
                                    <?php } ?>    
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-sm-2 control-label"><?php echo $this->translate('profile_password_label'); ?>:</label>
                                <div class="col-sm-10">
                                    <p class="form-control-static nullifempty view">
                                        <b style="font-size:16px;">&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;</b> &nbsp;
                                        
                                        <?php if($isme){ ?>
                                            <a class="addpopup btn btn-xs btn-default pull-right floatright" rel="Change Password" href="<?php echo $this->baseUrl('profile/changepassword/pgc/true/id/'.encode($user->getID())); ?>" formtitle="indexform" successurl="<?php echo $this->viewurl; ?>" action="<?php echo $this->baseUrl("profile/processchangepassword"); ?>" submittext="Change Password">Change Password</a>
                                        <?php } ?>
                                        <?php if($acl->checkPermission('User Account', ACTION_DELETE) && $user->isUserActive() && !$isme){ ?>
                                            <a class="btn btn-default btn-xs confirm-dialog pull-right floatright" action="<?php echo $this->baseUrl('profile/resetpassword/id/'.encode($user->getID()).'/successurl/'.encode($this->viewurl)); ?>" message="Are you sure you want to reset <?php echo $user->getName() ?>'s Password?">Reset Password</a>
                                        <?php } ?>
                                    </p>
                                </div>
                            </div>
                        <?php } ?> 
                    </div>
                </div>
            </div>
        </fieldset>
        <link rel="stylesheet" href="<?php echo $this->serverUrl($this->baseUrl('stylesheets/plugins/icheck/all.css')); ?>">
		<script src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/icheck/jquery.icheck.min.js')); ?>"></script>
        <style>
            .check-line  {
                display:block;
            }
            .check-line .inline {	
                width:100%; left:25px; top:-2px;
            }
            .fa.checker {
                background-color:#333;
                color:#fff;
                font-size:12px;
                padding:5px;
                margin-right:15px;
            }
            .fa.checker.unchecked {
                padding:5px 6px;
            }
        </style>
        <div class="col-sm-12 paddingleft0">
            <fieldset class="fieldsetcontainer">
                <legend>Preferences</legend>
            	<div class="panel-body well-sm">
                    <div class="row-fluid">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="col-sm-12">
                                	<?php 
										$preferrances = getUserPreferrenceOptions();
									?>
                                	<?php foreach($preferrances as $key => $preferrance){ 
										$currentvalue = $user->get($key, true); // debugMessage($currentvalue);
									?>
                                    	<div class="check-line">
                                            <label class='blocked' for="<?php echo $key; ?>">
                                                <i class="fa <?php echo $user->get($key, true) == 1 ? 'fa-check checked' : 'fa-remove unchecked'; ?> checker"></i> 
                                                <p class="form-control-static nullifempty view lineblocked bolded"><?php echo $preferrance; ?></p>
                                            </label>
                                        </div>
                                        <?php if($key == 'emailon_leave_approvalcompleted' || $key == 'emailon_leave_approvalrequired'){ ?>
                                        	<div class="divider30"></div>
                                        <?php } ?>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
       	</div>
	</div>
</div>            