<?php if($ispdf){ ?>
	<pagebreak />
<?php } ?>
<div class="row">
	<div class="makeabsolute" style="right:35px; top:11px; z-index:1000;">
		<?php if($allowedit && !$showfullscreen) { ?>
            <a class="btn btn-primary btn-xs blockanchor xnoround hideonprint" href="<?php echo $this->baseUrl('profile/index/id/'.encode($user->getID()).'/tab/benefits'); ?>">Update Recurring Benefits</a>
        <?php } ?>
    </div>
    <div class="col-sm-12 paddingleft0">
    	<div class="tabbable tabbable-custom tabbable-full-width">
        	<?php if(!$showfullscreen && !$ispdf) { ?>
                <ul class="nav nav-tabs hideonprint">
                    <li class="<?php echo $section == 'view' ? 'active gonowhere' : ''; ?>" ><a href="#view">Recurring Benefits</a></li>
                    <li class="<?php echo $section == 'list' ? 'active gonowhere' : 'blockanchor'; ?>"><a href="<?php echo $this->baseUrl('ledger/list/userid/'.$user->getID()); ?>">One Time Benefits</a></li>
                </ul>
            <?php } ?>
            <div class="tab-content">
				<div class="tab-pane active" id="view">
                    <fieldset class="fieldsetcontainer minheight200">
                        <legend><?php echo $ispdf ? ' &nbsp; ' : ''; ?> Monetary Benefits</legend>
                        <div class="panel-body well-sm">
                            <div class="divider10"></div>
                            	<table class="<?php echo $ispdf ? 'items isbordered' : 'table list table-bordered table-striped'; ?>" <?php echo $ispdf ? ' cellpadding="8"' : 'style="width:96%; margin-left:15px;"'; ?>>
                                <?php if($ispdf){ ?>
                                	<thead>
                                    	<tr>
                                            <td class="isbordered">Benefit Type</td>
                                            <td class="isbordered">Rate (<?php echo getCountryCurrencyCode(); ?>) / Frequency</td>
                                            <td class="isbordered">Payroll Terms</td>
                                            <td class="isbordered">Taxable</td>
                                       	</tr>
                                    </thead>
                                <?php } else { ?>
                                    <thead class="paginationheader">
                                    	<tr>
                                            <th class="isbordered">Benefit Type</th>
                                            <th class="isbordered" style="width:30%;">Rate (<?php echo getCountryCurrencyCode(); ?>) / Frequency</th>
                                            <th class="isbordered">Payment Terms</th>
                                            <th class="isbordered" style="width:20%;">Taxable</th>
                                       	</tr>
                                    </thead>
                                <?php } ?>
                                <tbody>
                                    <?php 
                                        $ratetypes = getDatavariables('EMPLOYEE_RATE_TYPES');
										$payrolltypes = getPayrollTypes();
                                        $benefits = getBenefits(2); // debugMessage($benefits);
                                        $leaves = getLeaveTypes();
                                        $usercashbenefits = getEmployeeBenefits($user->getID(), 1, " and benefitid <> 1 "); 
                                        $usertimebenefits = getEmployeeBenefits($user->getID(), 2); 
                                        $allterms = getAllBenefitTerms(); // debugMessage($allterms);
                                        $hoursdaysoptions = getHoursDaysDropdown();
                                        $yearmonthvalues = getYearMonthDropdown();
                                    ?>
                                         <tr <?php echo $ispdf ? '' : 'style="font-size:12px;"'; ?>>
                                            <td class="borderedtd"><?php echo $benefits[1]; ?></td>
                                            <td class="borderedtd">
                                                <?php echo isTimesheetEmployee() ? '' : formatMoneyOnly($user->getRate()); ?> 
                                                <?php echo isArrayKeyAnEmptyString($user->getRateType(), $ratetypes) ? '--' : $ratetypes[$user->getRateType()]; ?></td>
                                            <td class="borderedtd"><?php echo isArrayKeyAnEmptyString($user->getPayrollType(), $payrolltypes) ? '--' : $payrolltypes[$user->getPayrollType()]; ?></td>
                                            <td class="borderedtd"></td>
                                        </tr>
                                    <?php
                                        foreach($usercashbenefits as $key => $abenefit){ 
                                            // debugMessage($abenefit);
                                            $id = $abenefit['benefitid'];
                                            $amount = $abenefit['amount'];
                                            $ratetype = $abenefit['benefitfrequency'];
                                            $terms = $abenefit['benefitterms'];
											$istaxable = $abenefit['istaxable'];
											
											$amountlabel = formatMoneyOnly($amount);
											if(!isArrayKeyAnEmptyString($ratetype, $ratetypes)){
												$amountlabel .= ' '.$ratetypes[$ratetype];
											}
											if($id == NSSFID || $id == PAYEID){
												$amountlabel = 'auto';
											}
                                    ?>
                                        <tr <?php echo $ispdf ? '' : 'style="font-size:12px;"'; ?>>
                                            <td class="borderedtd"><?php echo isArrayKeyAnEmptyString($id, $benefits) ? '--' : $benefits[$id]; ?></td>
                                            <td class="borderedtd"><?php echo $amountlabel; ?></td>
                                            <td class="borderedtd"><?php echo isArrayKeyAnEmptyString($terms, $allterms) ? '--' : $allterms[$terms]; ?></td>
                                            <td class="borderedtd"><?php echo $istaxable == 1 ? 'Yes' : 'No'; ?></td>
                                        </tr>
                                    <?php } ?>
                                </tbody>
                            </table>
                        </div>
                    </fieldset>
                    <fieldset class="fieldsetcontainer minheight200">
                        <legend><?php echo $ispdf ? ' &nbsp; ' : ''; ?> Leave Benefits</legend>
                        <div class="panel-body well-sm">
                            <div class="divider10"></div>
                            <table class="<?php echo $ispdf ? 'items isbordered' : 'table list table-bordered table-striped'; ?>" <?php echo $ispdf ? ' cellpadding="8"' : 'style="width:96%; margin-left:15px;"'; ?>>
                                <?php if($ispdf){ ?>
                                	<thead>
                                    	<tr>
                                            <td class="isbordered">Leave Type</td>
                                            <td class="isbordered" style="width:75%;">Duration</td>
                                       	</tr>
                                    </thead>
                                <?php } else { ?>
                                    <thead class="paginationheader">
                                    	<tr>
                                            <th>Leave Type</th>
                                    		<th style="width:75%;">Duration Assigned</th>
                                       	</tr>
                                    </thead>
                                <?php } ?>
                                <tbody>
                                    <?php if(count($usertimebenefits) == 0){ ?>
                                        <tr>
                                            <td colspan="2" class="borderedtd"><span class="pagedescription">None available</span></td>
                                        </tr>
                                    <?php } else { ?>
                                        <?php
                                            foreach($usertimebenefits as $key => $abenefit){ 
                                                // debugMessage($abenefit);
                                                $id = $abenefit['leavetypeid'];
                                                $accrualtype = $abenefit['accrualtype'];
                                                $accrualfrequency = $abenefit['accrualfrequency'];
                                                $accrualvalue = $abenefit['accrualvalue'];
                                        ?>
                                            <tr <?php echo $ispdf ? '' : 'style="font-size:12px;"'; ?>>
                                                <td class="borderedtd"><?php echo isArrayKeyAnEmptyString($id, $leaves) ? '--' : $leaves[$id]; ?></td>
                                                <td class="borderedtd"><?php echo $accrualtype == '1' ? 'Assign 1 Day or '.getHoursInDay().' Hours for every '.$accrualvalue.' Hours Approved ' : ''; ?>
                                                    <?php echo $accrualtype == '2' ? formatNumber($accrualvalue,0).' Days '.$yearmonthvalues[$accrualfrequency] : ''; ?>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>                            
                                </tbody>
                            </table>
                        </div>
                    </fieldset>
              	</div>
         	</div>
      	</div>
    </div>
</div>