<div class="row">
    <div class="col-sm-12">
        <fieldset class="fieldsetcontainer minheight200">
            <legend>Monetary Benefits</legend>
            <div class="panel-body well-sm">
            	<div class="divider10"></div>
                <input type="hidden" name="hasbenefits" id="hasbenefits" value="1" />
               	<table class="table list table-bordered table-striped data-table" style="width:98%; margin-left:15px;">
                    <thead class="paginationheader">
                        <th style="width:25%;">Benefit Type</th>
                        <th style="width:15%;">Rate</th>
                        <th style="width:20%;">Frequency</th>
                        <th>Payroll Terms</th>
                        <th style="width:20%;">Taxable?</th>
                    </thead>
                    <tbody>
                    	<?php 
							$ratetypes = getDatavariables('EMPLOYEE_RATE_TYPES');
							$payrolltypes = getPayrollTypes();
							$benefits = getBenefits(2);
							$leaves = getLeaveTypes();
							$otherbenefits = getAllBenefitsDetails(" and id <> 1 ");
							$leaveoptions = getAllLeaveDetails();
							$usercashbenefits = getEmployeeBenefits($user->getID(), 1); $cashbenefits_data = array();
							$usertimebenefits = getEmployeeBenefits($user->getID(), 2); $leavebenefits_data = array();
							$allterms = getAllBenefitTerms();
							$yearmonthvalues = getYearMonthDropdown();
							foreach($usercashbenefits as $key => $value){ 
								$cashbenefits_data[$value['benefitid']] = $value;
							}
							foreach($usertimebenefits as $key => $value){ 
								$leavebenefits_data[$value['leavetypeid']] = $value;
							} 
						?>
                        <tr style="font-weight:bold;">
                            <td>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('_benefitid_1',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $benefits),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','disabledfield'),
															'style' => 'border:1px solid #000;'
                                                        )
                                    );  
                                    $dropdown->setValue(1); 
                                    echo $dropdown->render();
                                ?>
                                <input type="hidden" id="benefitid_1" name="benefitid_1" value="1" />
                                <input type="hidden" id="id_1" name="id_1" value="<?php echo isArrayKeyAnEmptyString(1, $cashbenefits_data) ? '' : $cashbenefits_data[1]['id']; ?>" />
                            </td>
                            <td><input type="text" id="rate" name="rate" class="form-control input-sm isdecimal centeralign" style="border:1px solid #000;" value="<?php echo $user->getRate(); ?>" /><div id="rate_error"></div></td>
                            <td>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('ratetype',
                                                        array(
                                                            'multiOptions' => $ratetypes,
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm'),
															'style' => 'border:1px solid #000;'
                                                        )
                                    );  
                                    $dropdown->setValue($user->getRateType()); 
                                    echo $dropdown->render();
                                ?>
                            </td>
                            <td>
                            	<?php
                                    $dropdown = new Zend_Form_Element_Select('payrolltype',
                                                        array(
                                                            'multiOptions' => $payrolltypes,
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm'),
															'style' => 'border:1px solid #000;'
                                                        )
                                    );  
                                    $dropdown->setValue($user->getPayrollType()); 
                                    echo $dropdown->render();
                                ?>
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                           	<td>
                           		<?php
									$i = 2;
									$id = NSSFID;
									$amount = '';
									$ratetype = '4';
									$terms = '2';
									$editid = '';
									if(!isArrayKeyAnEmptyString(NSSFID, $cashbenefits_data)){
										$amount = $cashbenefits_data[NSSFID]['amount'];
										$ratetype = $cashbenefits_data[NSSFID]['benefitfrequency'];
										$terms = isArrayKeyAnEmptyString($cashbenefits_data[NSSFID]['benefitterms'], $allterms) ? '' : $cashbenefits_data[NSSFID]['benefitterms'];
										$editid = $cashbenefits_data[NSSFID]['id'];
										$istaxable = $cashbenefits_data[NSSFID]['istaxable'];
									}
									
								?>
								<?php
                                    $dropdown = new Zend_Form_Element_Select('_benefitid_'.$i,
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $benefits),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','readonlyfield','disabledfield')
                                                        )
                                    );  
                                    $dropdown->setValue($id); 
                                    echo $dropdown->render();
                                ?>
                                <input type="hidden" id="benefitid_<?php echo $i; ?>" name="benefitid_<?php echo $i; ?>" value="<?php echo $id; ?>" />
                                <input type="hidden" id="id_<?php echo $i; ?>" name="id_<?php echo $i; ?>" value="<?php echo $editid; ?>" />
                            </td>
                            <td><label class="radio radio-inline" style="font-size:12px;"><input type="radio" name="amount_<?php echo $i; ?>" id="nssf_0" value="" style="margin-top:2px;" <?php echo isEmptyString($editid) || isEmptyString($amount) ? 'checked="checked"' : ''; ?> /> No</label> <label class="radio radio-inline" style="font-size:12px; margin-left:5px;"><input type="radio" name="amount_<?php echo $i; ?>" id="nssf_1" value="1" style="margin-top:2px;" <?php echo !isEmptyString($editid) && $amount == 1 ? 'checked="checked"' : ''; ?> /> Yes</label>
                            </td>
                            <td>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('_benefitfrequency_'.$i,
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $ratetypes),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm', 'frequency_required_'.$i, 'disabledfield')
                                                        )
                                    );  
                                    $dropdown->setValue($ratetype); 
                                    echo $dropdown->render();
                                ?>
                                <div id="benefitfrequency_<?php echo $i; ?>_error"></div>
                                <input type="hidden" id="benefitfrequency_<?php echo $i; ?>" name="benefitfrequency_<?php echo $i; ?>" value="<?php echo $ratetype; ?>" />
                            </td>
                            <td>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('_benefitterms_'.$i,
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allterms),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm', 'terms_required_'.$i, 'disabledfield')
                                                        )
                                    );  
                                    $dropdown->setValue($terms); 
                                    echo $dropdown->render();
                                ?>
                                <div id="benefitterms_<?php echo $i; ?>_error"></div>
                                <input type="hidden" id="benefitterms_<?php echo $i; ?>" name="benefitterms_<?php echo $i; ?>" value="<?php echo $terms; ?>" />
                            </td>
                            <td>
                                
                            </td>
                        </tr>
                        <tr>
                           	<td>
                           		<?php
									$i = 3;
									$id = PAYEID;
									$amount = '';
									$ratetype = '4';
									$terms = '2';
									$editid = '';
									if(!isArrayKeyAnEmptyString(PAYEID, $cashbenefits_data)){
										$amount = $cashbenefits_data[PAYEID]['amount'];
										$ratetype = $cashbenefits_data[PAYEID]['benefitfrequency'];
										$terms = isArrayKeyAnEmptyString($cashbenefits_data[PAYEID]['benefitterms'], $allterms) ? '' : $cashbenefits_data[PAYEID]['benefitterms'];
										$editid = $cashbenefits_data[PAYEID]['id'];
										$istaxable = $cashbenefits_data[PAYEID]['istaxable'];
									}
									
								?>
								<?php
                                    $dropdown = new Zend_Form_Element_Select('_benefitid_'.$i,
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $benefits),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','readonlyfield','disabledfield')
                                                        )
                                    );  
                                    $dropdown->setValue($id); 
                                    echo $dropdown->render();
                                ?>
                                <input type="hidden" id="benefitid_<?php echo $i; ?>" name="benefitid_<?php echo $i; ?>" value="<?php echo $id; ?>" />
                                <input type="hidden" id="id_<?php echo $i; ?>" name="id_<?php echo $i; ?>" value="<?php echo $editid; ?>" />
                            </td>
                            <td><label class="radio radio-inline" style="font-size:12px;"><input type="radio" name="amount_<?php echo $i; ?>" id="paye_0" value="" style="margin-top:2px;" <?php echo isEmptyString($editid) || isEmptyString($amount) ? 'checked="checked"' : ''; ?> /> No</label> <label class="radio radio-inline" style="font-size:12px; margin-left:5px;"><input type="radio" name="amount_<?php echo $i; ?>" id="paye_1" value="1" <?php echo !isEmptyString($editid) && $amount == 1 ? 'checked="checked"' : ''; ?> style="margin-top:2px;" /> Yes</label>
                            </td>
                            <td>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('_benefitfrequency_'.$i,
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $ratetypes),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm', 'frequency_required_'.$i, 'disabledfield')
                                                        )
                                    );  
                                    $dropdown->setValue($ratetype); 
                                    echo $dropdown->render();
                                ?>
                                <div id="benefitfrequency_<?php echo $i; ?>_error"></div>
                                <input type="hidden" id="benefitfrequency_<?php echo $i; ?>" name="benefitfrequency_<?php echo $i; ?>" value="<?php echo $ratetype; ?>" />
                            </td>
                            <td>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('_benefitterms_'.$i,
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allterms),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm', 'terms_required_'.$i, 'disabledfield')
                                                        )
                                    );  
                                    $dropdown->setValue($terms); 
                                    echo $dropdown->render();
                                ?>
                                <div id="benefitterms_<?php echo $i; ?>_error"></div>
                                <input type="hidden" id="benefitterms_<?php echo $i; ?>" name="benefitterms_<?php echo $i; ?>" value="<?php echo $terms; ?>" />
                            </td>
                            <td>
                                
                            </td>
                        </tr>
                    	<?php
							// debugMessage($cashbenefits_data);
							$i = 4;
							foreach($otherbenefits as $key => $abenefit){ 
								// debugMessage($abenefit);
								$id = $abenefit['id'];
								$amount = '';
								$taxamount = '';
								$istaxable = '';
								$ratetype = '';
								$terms = '';
								$editid = '';
								if(!isEmptyString($abenefit['defaultamount'])){
									// $amount = $abenefit['defaultamount'];
								}
								if(!isEmptyString($abenefit['amounttype'])){
									// $ratetype = $abenefit['amounttype'];
								}
								if(!isArrayKeyAnEmptyString($id, $cashbenefits_data)){
									$amount = $cashbenefits_data[$id]['amount'];
									$ratetype = $cashbenefits_data[$id]['benefitfrequency'];
									$terms = isArrayKeyAnEmptyString($cashbenefits_data[$id]['benefitterms'], $allterms) ? '' : $cashbenefits_data[$id]['benefitterms'];
									$editid = $cashbenefits_data[$id]['id'];
									$istaxable = $cashbenefits_data[$id]['istaxable'];
								}
						?>
                        	<script>
								$(document).ready(function(){
									// Add validation rules for maximum characters for content
									$.validator.addClassRules("frequency_required_<?php echo $i; ?>", {
										frequency_notempty_<?php echo $i; ?>: true				
									});
									
									$.validator.addMethod("frequency_notempty_<?php echo $i; ?>", function(value, element) {
										var amount = $("#amount_<?php echo $i; ?>").val();		
										if(!isEmptyString(amount) && isEmptyString(value)){
											return false;
										}
										return true;
									}, "Select Frequency");
									
									$.validator.addClassRules("terms_required_<?php echo $i; ?>", {
										terms_notempty_<?php echo $i; ?>: true				
									});
									
									$.validator.addMethod("terms_notempty_<?php echo $i; ?>", function(value, element) {
										var amount = $("#amount_<?php echo $i; ?>").val();		
										if(!isEmptyString(amount) && isEmptyString(value)){
											return false;
										}
										return true;
									}, "Select Terms");
									
								});
							</script>
                            <?php if(!in_array($id, array(NSSFID,PAYEID))){ ?>
                        	<tr>
                            	<td>
                                	<?php
										$dropdown = new Zend_Form_Element_Select('_benefitid_'.$i,
															array(
																'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $benefits),
																'view' => new Zend_View(),
																'decorators' => array('ViewHelper'),
																'class' => array('form-control','input-sm','readonlyfield','disabledfield')
															)
										);  
										$dropdown->setValue($id); 
										echo $dropdown->render();
									?>
                                    <input type="hidden" id="benefitid_<?php echo $i; ?>" name="benefitid_<?php echo $i; ?>" value="<?php echo $id; ?>" />
                                    <input type="hidden" id="id_<?php echo $i; ?>" name="id_<?php echo $i; ?>" value="<?php echo $editid; ?>" />
                                </td>
                                <td><input type="text" id="amount_<?php echo $i; ?>" name="amount_<?php echo $i; ?>" class="form-control input-sm isdecimal centeralign" value="<?php echo $amount; ?>" />
                                	<div id="amount_<?php echo $i; ?>_error"></div>
                                </td>
                                <td>
                                	<?php
                                        $dropdown = new Zend_Form_Element_Select('benefitfrequency_'.$i,
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $ratetypes),
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('form-control','input-sm', 'frequency_required_'.$i)
                                                            )
                                        );  
                                        $dropdown->setValue($ratetype); 
                                        echo $dropdown->render();
                                    ?>
                                    <div id="benefitfrequency_<?php echo $i; ?>_error"></div>
                                </td>
                                <td>
                                	<?php
                                        $dropdown = new Zend_Form_Element_Select('benefitterms_'.$i,
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allterms),
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                                'class' => array('form-control','input-sm', 'terms_required_'.$i)
                                                            )
                                        );  
                                        $dropdown->setValue($terms); 
                                        echo $dropdown->render();
                                    ?>
                                    <div id="benefitterms_<?php echo $i; ?>_error"></div>
                                </td>
                                <td>
                                	<label class="checkbox checkbox-inline floatleft" style="margin:0; padding:0; font-size:14px;"><input type="checkbox" style="padding:0; margin:0; width:auto; height:22px; margin-right:10px;" id="istaxable_<?php echo $i; ?>" name="istaxable_<?php echo $i; ?>" <?php echo $istaxable == 1 ? 'checked="checked"' : ''; ?> class="form-control inline" value="1" title="Click to enable or disable taxable benefits" /> Is Taxable</label>
                                </td>
                            </tr>
                            <?php } ?>
                        <?php $i++; } ?>
                    </tbody>
             	</table>
            </div>
        </fieldset>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <fieldset class="fieldsetcontainer minheight200" style="margin-bottom:0;">
            <legend>Leave Benefits</legend>
            <div class="panel-body well-sm">
            	<div class="divider10"></div>
                <table class="table list table-bordered table-striped data-table" style="width:98%; margin-left:15px;">
                    <thead class="paginationheader">
                        <th>Leave Type</th>
                        <th style="width:20%;">Accrue As</th>
                        <th style="width:45%;">Hours / Days Assigned</th>
                        <th style="width:30px;"></th>
                    </thead>
                    <tbody>
                        <?php
							$x = $i;
							foreach($leaveoptions as $key => $abenefit){ 
								// debugMessage($leavebenefits_data);
								$editid = '';
								$id = $abenefit['id'];
								$accrualtype = '2';
								$accrualfrequency = $abenefit['quantitytype'];
								$accrualvalue = '';
								
								if(!isArrayKeyAnEmptyString($id, $leavebenefits_data)){
									$editid = $leavebenefits_data[$id]['id'];
									$id = $leavebenefits_data[$id]['leavetypeid'];
									$accrualtype = $leavebenefits_data[$id]['accrualtype'];
									$accrualfrequency = $leavebenefits_data[$id]['accrualfrequency'];
									$accrualvalue = formatNumber($leavebenefits_data[$id]['accrualvalue'],0);
								}
						?>
                        	<script>
								$(document).ready(function() {
									$("#accrualtype_1_<?php echo $x; ?>").click(function(){
										enableContainerByID('ashours_<?php echo $x; ?>');
										disableContainerByID('asdays_<?php echo $x; ?>');
									});
									$("#accrualtype_2_<?php echo $x; ?>").click(function(){
										enableContainerByID('asdays_<?php echo $x; ?>');
										disableContainerByID('ashours_<?php echo $x; ?>');
									});
									<?php if($accrualtype == '1'){ ?>
										enableContainerByID('ashours_<?php echo $x; ?>');
										disableContainerByID('asdays_<?php echo $x; ?>');
									<?php } ?>
									<?php if($accrualtype == '2'){ ?>
										enableContainerByID('asdays_<?php echo $x; ?>');
										disableContainerByID('ashours_<?php echo $x; ?>');
									<?php } ?>
									
									$(".acrrualtrigger").click(function(){
										$("#accrualvalue_<?php echo $x; ?>").val('');
									});
								});
                            </script>
                        	<tr>
                            	<td>
                                	<?php
										$dropdown = new Zend_Form_Element_Select('_leavetypeid_'.$x,
															array(
																'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $leaves),
																'view' => new Zend_View(),
																'decorators' => array('ViewHelper'),
																'class' => array('form-control','input-sm','readonlyfield','disabledfield')
															)
										);  
										$dropdown->setValue($id); 
										echo $dropdown->render();
									?>
                                    <input type="hidden" id="leavetypeid_<?php echo $x; ?>" name="leavetypeid_<?php echo $x; ?>" value="<?php echo $id; ?>" />
                                    <input type="hidden" id="id_<?php echo $x; ?>" name="id_<?php echo $x; ?>" value="<?php echo $editid; ?>" />
                                </td>
                                <td style="font-size:12px;">
                                	<label class="radio radio-inline"><input type="radio" name="accrualtype_<?php echo $x; ?>" id="accrualtype_2_<?php echo $x; ?>" class="<?php echo $accrualtype == '2' ? 1 : 0; ?> acrrualtrigger" value="2" <?php echo $accrualtype == '2' ? 'checked="checked"' : ''; ?> /> Days</label>
                                    <label class="radio radio-inline"><input type="radio" name="accrualtype_<?php echo $x; ?>" id="accrualtype_1_<?php echo $x; ?>" class="<?php echo $accrualtype == '1' ? 1 : 0; ?> acrrualtrigger" value="1" <?php echo $accrualtype == '1' ? 'checked="checked"' : ''; ?> /> Hours &nbsp;</label>
                                <div id="leavetype_error"></div>
                                </td>
                                <td>
                                	<div class="form-group ashours" id="ashours_<?php echo $x; ?>" style="margin:0; padding:0;">
                                		<span class="notbolded" style="font-size:12px;">Assign 1 Day or <?php echo getHoursInDay(); ?> Hours for every </span> &nbsp;<input type="text" name="accrualvalue_<?php echo $x; ?>" id="accrualvalue_<?php echo $x; ?>" class="form-control width80 isdecimal centeralign input-sm" value="<?php echo $accrualvalue; ?>" style="display:inline;" /> <span class="notbolded" style="font-size:12px;">Hours</span>
                                    </div>
                                    <div class="form-group asdays" id="asdays_<?php echo $x; ?>"  style="margin:0; padding:0;">
                                    	<input type="text" name="accrualvalue_<?php echo $x; ?>" id="accrualvalue_<?php echo $x; ?>" class="form-control width80 input-sm isdecimal centeralign" value="<?php echo $accrualvalue; ?>" style="display:inline;" />
                                        <?php
											$dropdown = new Zend_Form_Element_Select('accrualfrequency_'.$x,
																array(
																	'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $yearmonthvalues),
																	'view' => new Zend_View(),
																	'decorators' => array('ViewHelper'),
																	'class' => array('form-control','input-sm','width100','inline')
																)
											);  
											$dropdown->setValue($accrualfrequency); 
											echo $dropdown->render();
										?>
                                    </div>
                                    <div id="accrualvalue_<?php echo $x; ?>_error"></div>
                                </td>
                                <td></td>
                            </tr>
                        <?php $x++; } ?>
                   	</tbody>
              	</table>
          	</div>
     	</fieldset>
  	</div>
</div>
<div class="divider15"></div>