<div class="row">	
    <div class="col-sm-12">
        <fieldset class="fieldsetcontainer">
            <legend>Employee Details</legend>
            <div class="panel-body well-sm">
                <div class="row-fluid">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate('profile_department_label'); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-8">
                                <?php
                                    $allvalues = getDepartments();
                                    $dropdown = new Zend_Form_Element_Select('departmentid',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues, array('0'=>$this->translate("global_addvariable_label"))),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','configvariable'),
															'lookupid' => 11,
															'fieldid' => 'departmentid',
															'fieldlabel' => $this->translate('profile_department_label')
                                                        )
                                    );  
                                    $dropdown->setValue($user->getDepartmentID()); 
                                    echo $dropdown->render();
                                ?><div id="departmentid_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate('profile_position_label'); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-8">
                                <?php
                                    $allvalues = getDatavariables('EMPLOYEE_POSITIONS');
                                    $dropdown = new Zend_Form_Element_Select('position',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues, array('0'=>$this->translate("global_addvariable_label"))),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','configvariable'),
															'lookupid' => 7,
															'fieldid' => 'position',
															'fieldlabel' => $this->translate('profile_position_label'),
															'hasalias' => '1',
															'parentid' => 'departmentid'
                                                        )
                                    );  
                                    $dropdown->setValue($user->getPosition()); 
                                    echo $dropdown->render();
                                ?><div id="position_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate('profile_empstatus_label'); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-8">
                                <?php
                                    $allvalues = getDatavariables('EMPLOYEE_STATUS');
                                    $dropdown = new Zend_Form_Element_Select('empstatus',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','xwidth200')
                                                        )
                                    );  
                                    $dropdown->setValue($user->getEmpStatus()); 
                                    echo $dropdown->render();
                                ?><div id="empstatus_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate('profile_employmentstatus_label'); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-8">
                                <?php
                                    $allvalues = array('1'=>'Active', '0'=>'Discontinued');
                                    $dropdown = new Zend_Form_Element_Select('empstatus',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','xwidth200')
                                                        )
                                    );  
                                    $dropdown->setValue($user->getEmploymentStatus()); 
                                    echo $dropdown->render();
                                ?><div id="empstatus_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate('profile_manager_label'); ?>:</label>
                            <div class="col-sm-8">
                                <?php
                                    $allvalues = getUsers('','','',$user->getID());
                                    $dropdown = new Zend_Form_Element_Select('managerid',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','xwidth200')
                                                        )
                                    );  
                                    $dropdown->setValue($user->getManagerID()); 
                                    echo $dropdown->render();
                                ?><div id="managerid_error"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 paddingleft10">
                        <div class="form-group">
                            <label class="col-sm-5 control-label"><?php echo $this->translate('profile_empidno_label'); ?>:</label>
                            <div class="col-sm-7">
                                <input type="text" name="idno" id="idno" class="form-control width100" value="<?php echo $user->getIDNo(); ?>" />
                                <div id="idno_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-5 control-label"><?php echo $this->translate('profile_startdate_label'); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control input-sm datefield readonly datepick width100 ordinary" name="startdate" id="startdate" value="<?php echo isEmptyString($user->getStartDate()) ? '' : date('m/d/Y', strtotime($user->getStartDate())); ?>" />
                                <div id="startdate_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-5 control-label"><?php echo $this->translate('profile_probationdate_label'); ?>:</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control input-sm datefield readonly datepick  width100 ordinary" name="probationend" id="probationend" value="<?php echo isEmptyString($user->getProbationEnd()) ? '' : date('m/d/Y', strtotime($user->getProbationEnd())); ?>" />
                                <div id="probationend_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-5 control-label"><?php echo $this->translate('profile_enddate_label'); ?>:</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control input-sm datefield readonly datepick  width100 ordinary" name="enddate" id="enddate" value="<?php echo  isEmptyString($user->getEndDate()) ? '' : date('m/d/Y', strtotime($user->getEndDate())); ?>" />
                                <div id="enddate_error"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="divider20"></div>
                <div class="row-fluid marginleft5">
                    <div class="col-sm-10 paddingleft10">
                        <div class="form-group">
                            <label class="col-sm-12 control-label"><?php echo $this->translate('profile_qualification_label'); ?>:</label>
                            <div class="col-sm-12">
                                <textarea name="qualifications" id="qualifications" class="form-control expanding"><?php echo $user->getQualifications(); ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-12 control-label"><?php echo $this->translate('profile_skills_label'); ?>:</label>
                            <div class="col-sm-12">
                                <textarea name="skills" id="skills" class="form-control expanding"><?php echo $user->getSkills(); ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-12 control-label"><?php echo $this->translate('profile_education_label'); ?>:</label>
                            <div class="col-sm-12">
                                <textarea name="education" id="education" class="form-control expanding"><?php echo $user->getEducation(); ?></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-12 control-label"><?php echo $this->translate('profile_workexperience_label'); ?>:</label>
                            <div class="col-sm-12">
                                <textarea name="experience" id="experience" class="form-control expanding"><?php echo $user->getExperience(); ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="row">	
    <div class="col-sm-12">
        <fieldset class="fieldsetcontainer">
            <legend>Attendance Configuration</legend>
            <div class="panel-body well-sm">
                <div class="row-fluid marginleft5">
                    <div class="col-sm-12 paddingleft10">
                        <div class="form-group">
                            <label class="col-sm-12 control-label"><?php echo $this->translate('profile_workingdays_label'); ?>:</label>
                            <div class="col-sm-12">
                                <?php
                                    $workshifts = getDaysOfWeek();
                                    $existing_values = $user->getDaysOfWeekArray();
                                    foreach($workshifts as $key => $value){
                                ?>
                                    <label class="checkbox-inline notbolded">
                                      <input type="checkbox" id="workingdaysids_<?php echo $key; ?>" name="workingdaysids[]" class="disableoutsidesection" value="<?php echo $key; ?>" <?php echo in_array($key, $existing_values) ? 'checked data-waschecked="true"' : 1; ?>> <?php echo $value; ?>
                                    </label>
                                <?php } ?>
                                <input type="hidden" name="workingdays_old" id="workingdays_old" value="<?php echo $user->getWorkingDays(); ?>" />
                                <div id="workingdays_error"></div>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-12 paddingleft10">
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('profile_shift_label'); ?>:</label>
                            <div class="col-sm-9">
                                <?php
                                    $allvalues = getWorkShifts();
                                    $dropdown = new Zend_Form_Element_Select('shift',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => '<Select One>'), $allvalues),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array('form-control','input-sm','width250')
                                                        )
                                    );  
                                    $dropdown->setValue($user->getShift()); 
                                    echo $dropdown->render();
                                ?><div id="shift_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('profile_maxdayhrs_label'); ?>:</label>
                            <div class="col-sm-9">
                                <input type="text" name="maxhoursperday" id="maxhoursperday" class="form-control isnumber input-sm width100" value="<?php echo $user->getMaxHoursPerDay(); ?>" />
                                <div id="maxhoursperday_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate('profile_minweekhrs_label'); ?>:</label>
                            <div class="col-sm-9">
                                <input type="text" name="maxhoursperweek" id="maxhoursperweek" class="form-control isnumber input-sm width100" value="<?php echo $user->getMaxHoursPerWeek(); ?>" />
                                <div id="maxhoursperweek_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Check In/Out Configuration:</label>
                            <div class="col-sm-9">
                                <?php 
                                    $attendancetypes = getAttendanceTypes();
                                ?>
                                <?php foreach($attendancetypes as $key => $value){ ?>
                                    <label class="radio radio-blocked notbolded"><input type="radio" name="istimesheetuser" id="istimesheetuser_<?php echo $key; ?>" <?php echo $user->getistimesheetuser() == $key ? 'checked="checked"' : ''; ?> value="<?php echo $key; ?>" /> <?php echo $value; ?></label>
                                <?php } ?>
                                <div id="maxhoursperweek_error"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<div class="row">	
    <div class="col-sm-12">
        <fieldset class="fieldsetcontainer">
            <legend>Banking Details and Taxing Information</legend>
            <div class="panel-body well-sm">
                <div class="row-fluid">
                    <div class="col-sm-8">
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate('profile_bankname_label'); ?>:</label>
                            <div class="col-sm-8">
                                <input type="text" name="bankname" id="bankname" class="form-control input-sm" value="<?php echo $user->getBankName(); ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate('profile_branch_label'); ?>:</label>
                            <div class="col-sm-8">
                                <input type="text" name="branchname" id="branchname" class="form-control input-sm" value="<?php echo $user->getBranchName(); ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate('profile_accname_label'); ?>:</label>
                            <div class="col-sm-8">
                                <input type="text" name="accname" id="accname" class="form-control input-sm" value="<?php echo $user->getAccName(); ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label"><?php echo $this->translate('profile_accno_label'); ?>:</label>
                            <div class="col-sm-8">
                                <input type="text" name="accno" id="accno" class="form-control input-sm" value="<?php echo $user->getAccNo(); ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">NSSF ID No#:</label>
                            <div class="col-sm-8">
                            	<input type="text" name="nssfid" id="nssfid" class="form-control input-sm" value="<?php echo $user->getNssfID(); ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-4 control-label">URA TIN No#:</label>
                            <div class="col-sm-8">
                                <input type="text" name="uratin" id="uratin" class="form-control input-sm" value="<?php echo $user->getUraTin(); ?>" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </fieldset>
    </div>
</div>
