<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid); 
	
	$user = new UserAccount();
	
	if (isEmptyString($request->id)) {
		$pagetitle = "New Employee";
		$posturl = $this->baseUrl("profile/create");
		$button_title = $this->translate("global_button_save");
		$successmessage = $this->translate('global_save_success');
		$user->setType(2);
	} else {
		$pagetitle = "Update Profile"; 
		$user->populate(decode($request->id));		
		$posturl = $this->baseUrl("profile/edit"); 
		$button_title = $this->translate('global_button_save_changes'); 
		$successmessage = $this->translate('global_update_success');
	}
	
	$postuserurl = $this->baseUrl("profile/inviteuser");
	$failureurl =  $this->viewurl;
	$successurl = $this->baseUrl('profile/view');
	$addnewsuccessurl = $this->baseUrl('profile/index');
	
	$tab = $request->tab;
	if(isEmptyString($tab)){
		$tab = 'overview';
	}
	
	$isme = false;
	if($user->getID() == $loggedinuser->getID()){
		$isme = true;
	}
	
	if($tab == 'picture'){
		$posturl = $this->baseUrl("profile/uploadpicture");
		$button_title = "Upload Picture";
		$successurl = $this->baseUrl("profile/index/id/".encode($user->getID())."/tab/picture/crop/1");
		$failureurl =  $this->baseUrl("profile/index/id/".encode($user->getID())."/tab/picture");
		
		if($request->crop == 1){
			$posturl = $this->baseUrl("profile/croppicture");
			$button_title = "Crop Photo";
			$successurl = $this->baseUrl('profile/view/id/'.encode($user->getID()));
			$failureurl =  $this->baseUrl('profile/index/id/'.encode($user->getID()).'/tab/picture/crop/1');
		}
	}
	
	$gotosuccess = false; 
	if(!isEmptyString($request->successurl)){
		$successurl = $request->successurl;
		$gotosuccess = true; 
	}
	
	if($tab == 'employment'){
		$successurl = $this->baseUrl('profile/view/id/'.encode($user->getID()).'/tab/employment');
		$gotosuccess = true; 
	}
	if($tab == 'benefits'){
		$successurl = $this->baseUrl('profile/view/id/'.encode($user->getID()).'/tab/benefits');
		$gotosuccess = true; 
	}
	if($tab == 'account'){
		$successurl = $this->baseUrl('profile/view/id/'.encode($user->getID()).'/tab/account');
		$gotosuccess = true; 
	}
	
	$isme = true;
	if($user->getID() != $userid){
		$isme = false;
	}
	
	#in case of errors in session, populate the fields from session
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$user->processPost($session->getVar(FORM_VALUES));
	}
	
	$resourcename = 'User Account';
	$entityname = "UserAccount";
	$listitems = "Employees";
	$listurl = $this->baseUrl('profile/list');
	$icon = 'fa fa-user';
	$description = "";
	$title = "New Employee";
	$breadcrumb = "Employees / ".$pagetitle;
	if(!isEmptyString($request->id)){
		$title = $user->getName();
		if($tab == 'picture'){
			$pagetitle = "Upload Profile Photo";
		}
		$breadcrumb = "Employees / ".$user->getName()." / ".$pagetitle;
	}
	$pageid = "profile_index";
	// $title = "Employees";
	
	$allowedit = false;
	if($acl->checkPermission($resourcename, ACTION_EDIT)){
		$allowedit = true;
	}
	
	$this->headTitle($title.$browserappend);
?>
<?php if(isEmptyString($user->getID())){ ?>
    <script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/custom/jquery.stepy.js')); ?>"></script>
<?php } ?>
<script src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/datepicker/bootstrap-datepicker.js')); ?>"></script>
<link href='<?php echo $this->baseUrl('stylesheets/plugins/datepicker/datepicker.css'); ?>' rel='stylesheet' type='text/css'>

<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.$breadcrumb; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="icon-large <?php echo $icon; ?>"></span>');
	
	<?php if(isEmptyString($user->getID())){ ?>
		$('#indexform').stepy({
			block: true,
			validate: true,
			errorImage:	false,
			titleClick:	true,
			backLabel: '<span class="fa fa-arrow-left"></span> Back',
			nextLabel: 'Next <span class="fa fa-arrow-right"></span>'
		});
		
		$(".button-back").addClass('btn btn-default btn-lg');
		$(".button-next").addClass('btn btn-primary btn-lg'); 
		$(".finish").html('').prepend('<span class="fa fa-check"></span> Finish').addClass('btn btn-success btn-lg');
		$(".step legend").hide();
	<?php } ?>
	
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			gender: "required",
			firstname: "required",
			lastname: "required",
			phone: {
				required: true,
				validnumber: true,
				minlength: "<?php echo getMinPhoneLength(); ?>"
			},
			username: {
				required: <?php echo $user->isUserActive() ? 'true' : 'false' ; ?>, 
				minlength: <?php echo $config->profile->usernameminlength; ?>,
				maxlength: <?php echo $config->profile->usernamemaxlength; ?>
			},
			email: {
				required: <?php echo $user->isUserActive() ? 'true' : 'false' ; ?>, 
				email: true
			},
			email_auto: {
				required: <?php echo $user->isUserActive() ? 'true' : 'false' ; ?>, 
				email: true
			},
			oldpassword: {
				required: function(element) {
					return !isEmptyString($("#newpassword").val());
				}
			},
			newpassword: {
				<?php if(isEmptyString($user->getID())) { ?>
					required: true,
				<?php } else { ?>
					required: function(element) {
						return !isEmptyString($("#oldpassword").val());
					},
				<?php } ?>	
				maxlength: <?php echo $config->profile->passwordmaxlength; ?>,
				minlength: <?php echo $config->profile->passwordminlength; ?>
			},			
			confirmpassword: {
				<?php if(isEmptyString($user->getID())) { ?>
					required: true,
				<?php } else { ?>
					required: function(element) {
						return !isEmptyString($("#oldpassword").val()) && !isEmptyString($("#newpassword").val());
					},
				<?php } ?>	
				equalTo: "#newpassword"
			},
			type: "required",
			profileimage: "required",
			position: "required",
			empstatus: "required",
			departmentid: "required",
			/*startdate: "required",
			rate: {
				required: true
			},
			ratetype: "required"*/			
		}, 
		// the messages for each of the fields being validated
		messages: {		
			gender: "<?php echo $this->translate("profile_gender_error"); ?>", 
			firstname: "<?php echo $this->translate("profile_firstname_error"); ?>",
			lastname: "<?php echo $this->translate("profile_lastname_error"); ?>",
			username: {
				required: "<?php echo $this->translate("useraccount_username_error"); ?>",
				minlength: "<?php echo sprintf($this->translate("profile_username_error_minlength"), $config->profile->usernameminlength); ?>",
				maxlength: "<?php echo sprintf($this->translate("profile_username_error_maxlength"), $config->profile->usernamemaxlength); ?>"
			},
			email: {
				"required": "<?php echo $this->translate("profile_email_error"); ?>", 
				"email": "<?php echo $this->translate("profile_email_invalid_error"); ?>"
			},
			email_auto: {
				"required": "<?php echo $this->translate("profile_email_error"); ?>", 
				"email": "<?php echo $this->translate("profile_email_invalid_error"); ?>"
			},
			phone: {
				required: "<?php echo $this->translate("profile_phonenumber_error"); ?>",
				minlength: "<?php echo sprintf($this->translate("profile_phone_maxlength_error"), getMinPhoneLength()); ?>"
			},
			oldpassword: {
				required: "<?php echo $this->translate("profile_oldpassword_error"); ?>"
			},
			newpassword: {
				required: "<?php echo $this->translate("useraccount_password_error"); ?>",
				maxlength: "<?php echo sprintf($this->translate("useraccount_password_error_maxlength"), $config->profile->passwordmaxlength); ?>",
				minlength: "<?php echo sprintf($this->translate("useraccount_password_error_minlength"), $config->profile->passwordminlength); ?>"
			},
			confirmpassword: {
				required: "<?php echo $this->translate("profile_confirmpassword_error"); ?>",
				equalTo: "<?php echo $this->translate("profile_confirmpassword_error_equalto"); ?>"
			},
			type: "<?php echo $this->translate("profile_role_error"); ?>",
			profileimage: "Please browse for image on computer",
			position: "Please select a Position",
			empstatus: "Please select current Employment Status",
			departmentid: "Please select a Department"
			/*startdate: "Please select a Start Date",
			rate: {
				required: "Please enter Employee Rate"
			},
			ratetype: "Please select a Type"*/
		},
		// custom error positions
		errorPlacement: function(error, element) {
			switch(element.attr("name")){					
				default:
					if(element.hasClass("useid_error")){
						error.appendTo("#"+element.attr("id")+"_error");
					} else {
						error.appendTo("#"+element.attr("name")+"_error");
					}
					break;
			}			
		}
	});
	
	//when button is clicked  
	$('#check_username_availability').click(function(){ 
		check_user_availability();  
	});
	$('#username').change(function(){ 
		check_user_availability();  
	});  
	$('#username').keyup(function(){
		this.value = this.value.toLowerCase();
	});
	
	//function to check username availability  
	function check_user_availability(){  
		//get the username
		var checking_html = 'Checking availability...';   
		var username = $('#username').val();  
		if(!isEmptyString(username) && username.length >= 4 && username.length <= 15 && isAlpha(username)){
			// alert('passed');
			$('#username_availability_result').html(checking_html); 
			var userid = '<?php echo $user->getID(); ?>';
			//use ajax to run the check  
			$.post("<?php echo $this->baseUrl('signup/checkusername'); ?>", { username: username, userid: userid },  
				function(result){  
					//if the result is 1  
					// alert(result); // return false;
					if(result == 1){  
						//show that the username is available
						$('#username_availability_result').html(username + ' already exists!').addClass('alert').addClass('alert-danger').removeClass('alert-success'); 
					} else {  
						//show that the username already exists  
						$('#username_availability_result').html(username + ' is available').addClass('alert').addClass('alert-success').removeClass('alert-danger');
					}  
			});   
		}
	}
	
	//when button is clicked  
	$('#check_email_availability').click(function(){ 
		check_email_availability();  
	});
	$('#email').change(function(){ 
		check_email_availability();  
	});  
	
	//function to check email availability  
	function check_email_availability(){  
		//get the username
		var checking_html = 'Checking availability...';   
		var email = $('#email').val();  
		if(!isEmptyString(email) && validateEmail(email)){
			$('#email_availability_result').html(checking_html);  
			var userid = '<?php echo $user->getID(); ?>';
			//use ajax to run the check  
			$.post("<?php echo $this->baseUrl('signup/checkemail'); ?>", { email: email, userid: userid},  
				function(result){  
					//if the result is 1  
					// alert(result); // return false;
					if(result == 1){  
						//show that the email is available
						$('#email_availability_result').html(email + ' already exists!').addClass('alert').addClass('alert-danger').removeClass('alert-success fade in'); 
					} else {  
						//show that the email already exists  
						$('#email_availability_result').html(email + ' is available').addClass('alert').addClass('alert-success').removeClass('alert-danger fade in');
					}  
			});  
		}
	}
	
	// auto fill out email field if entering new user and member at same time
	$('#email').keyup(function() {
		var email = $(this).val();
		$("#email_auto").val(email);
	});
	$('#email').change(function() {
		var email = $(this).val();
		$("#email_auto").val(email);
	});
	
	$(".triggerprofile").click(function(){
		var current = $(this).val();
		triggerUserAddition(current);
	});
	
	$("#email_auto").keyup(function(){
		$("#email").val($(this).val());
	});
	$("#email_auto").change(function(){
		$("#email").val($(this).val());
	});
	
	$.datepicker.setDefaults({
		dateFormat: "dd/mm/yy"
	});	
});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div id="<?php echo $pageid; ?>">
    <div class="row">
        <div class="col-sm-12">
            <div class="box box-color box-bordered">
                <div class="box-title condensed">
                    <h3><i class="fa fa-user"></i> <?php echo $pagetitle; ?></h3>
                </div>
                <div class="box-content <?php echo !isEmptyString($request->id) ? ' nopadding': ''; ?> clearfix" style="min-height:500px; height:auto;">
                    <form id="indexform" class="form-horizontal profile" action="<?php echo $posturl; ?>" method="post" enctype="multipart/form-data">
                        <input name="entityname" id="entityname" type="hidden" value="UserAccount" />
                        <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
                        <input name="successmessage" id="successmessage" type="hidden" value="<?php echo $successmessage; ?>" />  
                        <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" /> 
                        <input type="hidden" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($successurl); ?>" /> 
                        <input type="hidden" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($failureurl); ?>" /> 
                        <input type="hidden" id="status" name="status" value="<?php echo $user->getStatus(); ?>" />
                        <input type="hidden" id="companyid" name="companyid" value="<?php echo $companyid; ?>" />
                        <?php if($gotosuccess){ ?>
                            <input type="hidden" id="nosuccessid" name="nosuccessid" value="1" />
                        <?php } ?>
                    	<?php if(isEmptyString($request->id)){ ?>
                            <fieldset title="Profile Summary" id="step1summary">
                                <legend>Step 1</legend>
                                <?php require APPLICATION_PATH."/views/scripts/profile/overview_index.phtml"; ?>
                            </fieldset>
                            <fieldset title="Employment Details" id="step2employeement">
                                <legend>Step 2</legend>
                                <?php require APPLICATION_PATH."/views/scripts/profile/employment_index.phtml"; ?>
                            </fieldset>
                            <fieldset title="Employee Benefits" id="step3benefits">
                                <legend>Step 3</legend>
                                <?php require APPLICATION_PATH."/views/scripts/profile/benefits_index.phtml"; ?>
                            </fieldset>
                            <fieldset title="Account Setup" id="step4account">
                                <legend>Step 4</legend>
                                 <?php require APPLICATION_PATH."/views/scripts/profile/account_index.phtml"; ?>
                            </fieldset>
                            <button type="submit" class="btn btn-primary finish btn-lg" id="finish">Complete</button> 
                        <?php } ?>
                        <?php if(!isEmptyString($user->getID())){ ?>
                            <div class="tabs-container col-sm-3 col-xs-12 padding0">
                                <ul class="tabs tabs-inline tabs-left">
                                    <li class="<?php echo $tab == 'overview' ? 'active' : ''; ?>"><a data-toggle="tab" href="#overview"><i class="fa fa-file"></i>About</a></li>
                                    <li class="<?php echo $tab == 'employment' ? 'active' : ''; ?>"><a data-toggle="tab" href="#employment"><i class="fa fa-briefcase"></i>Employment Details</a></li>
                                    <li class="<?php echo $tab == 'benefits' ? 'active' : ''; ?>"><a data-toggle="tab" href="#benefits"><i class="fa fa-gift"></i>Employee Benefits</a></li>
                                    <li class="<?php echo $tab == 'account' ? 'active' : ''; ?>"><a data-toggle="tab" href="#account"><i class="fa fa-cog"></i>Account</a></li>
                                    <li class="list-group-item padding0 centeralign noround nobg" style="padding:1px;">
                                        
                                    </li>
                                </ul>
                            </div>
                            <div class="tab-content padding col-sm-9 col-xs-12">
                            	<div class="form-actions testborder" style="margin-top: -10px;">
                                    <a class="btn cancel gonowhere" type="button"><?php echo $this->translate('global_button_cancel'); ?></a>
                                    <button class="btn btn-primary btn-green changesuccessurl savebutton" type="submit" successurl="<?php echo encode($successurl); ?>"><?php echo $button_title; ?></button>
                                </div>
                            	<div id="overview" class="tab-pane <?php echo $tab == 'overview' ? 'active' : ''; ?>">
                                	<?php require APPLICATION_PATH."/views/scripts/profile/overview_index.phtml"; ?>
                                </div>
                                <div id="employment" class="tab-pane <?php echo $tab == 'employment' ? 'active' : ''; ?>">
                                	<?php require APPLICATION_PATH."/views/scripts/profile/employment_index.phtml"; ?>
                                </div>
                                <div id="benefits" class="tab-pane <?php echo $tab == 'benefits' ? 'active' : ''; ?>">
									<?php require APPLICATION_PATH."/views/scripts/profile/benefits_index.phtml"; ?>
                                </div>
                                <div id="account" class="tab-pane <?php echo $tab == 'account' ? 'active' : ''; ?>">
                                    <?php require APPLICATION_PATH."/views/scripts/profile/account_index.phtml"; ?>
                                </div>
                                <div class="form-actions testborder">
                                    <a class="btn cancel gonowhere" type="button"><?php echo $this->translate('global_button_cancel'); ?></a>
                                    <button class="btn btn-primary btn-green changesuccessurl savebutton" type="submit" successurl="<?php echo encode($successurl); ?>"><?php echo $button_title; ?></button>
                                </div>
                            </div>
                        <?php } ?>	
                        <div class="divider15"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>            
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
