<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$loggedinuser = new UserAccount();
	$loggedinuser->populate($userid);
	$customlabel = "";
	
	$style = '1';
	if(!isEmptyString($request->style)){
		$style = $request->style;
		$session->setVar('style', $request->style);
	}
	if(isEmptyString($request->style) && !isEmptyString($session->getVar('style'))){
		$style = $session->getVar('style');
	}
	
	$startdate = $request->startdate;
	$enddate = $request->enddate;
	if(!isEmptyString($startdate)){
		$startdate = changeDateFromPageToMySQLFormat($startdate);
		$allowclear = true;
	}
	$enddate = $request->getParam('enddate');
	if(!isEmptyString($enddate)){
		$enddate = changeDateFromPageToMySQLFormat($enddate);
		$allowclear = true;
	}
	
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("u.firstname","u.lastname","u.othername","u.displayname","u.email","u.phone","u.phone2"));
	$paginate->setFilterColumns(array());
	$paginate->setItemCountPerPage("ALL");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE u.id <> '' ";
	$allowclear = false;
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	$departmentid = trim($request->departmentid);
	if(!isEmptyString($departmentid)){
		$where_query .= " AND u.`departmentid` = '".$departmentid."' ";
		$allowclear = true;
	}
	$position = trim($request->position);
	if(!isEmptyString($position)){
		$where_query .= " AND u.`position` = '".$position."' ";
		$allowclear = true;
	}
	$empstatus = trim($request->empstatus);
	if(!isEmptyString($empstatus)){
		$where_query .= " AND u.`empstatus` = '".$empstatus."' ";
		$allowclear = true;
	}
	$status = trim($request->status);
	if(!isEmptyString($status)){
		$where_query .= " AND u.`status` = '".$status."' ";
		$allowclear = true;
	}
	$gender = trim($request->gender);
	if(!isEmptyString($gender)){
		$where_query .= " AND u.`gender` = '".$gender."' ";
		$allowclear = true;
	}
	
	$type = trim($request->type);
	$role = '';
	$allroles = getUserType();
	if(!isEmptyString($type)){
		$where_query .= " AND (u.type = ".$type." || g.groupid = ".$type.") ";
		$allowclear = true;
	}
	
	if(!isEmptyString($startdate)){
		$where_query .= " AND (TO_DAYS(u.datecreated) >= TO_DAYS('".$startdate."')) ";
		$allowclear = true;
	}
	if(!isEmptyString($enddate)){
		$where_query .= " AND (TO_DAYS(u.datecreated) <= TO_DAYS('".$enddate."')) ";
		$allowclear = true;
	}
		
	if(!isEmptyString($request->letter)){
		$where_query .= " AND (u.`firstname` LIKE '".$request->letter."%' OR u.`lastname` LIKE '".$request->letter."%') ";
		$allowclear = true;
	}
	
	$profilerid = $request->profilerid;
	if(!isEmptyString($profilerid)){
		$where_query .= " AND u.createdby = '".$profilerid."' ";
		$allowclear = true;
	}
	$company_query = "";
	if(!isEmptyString($request->companyid)){
		$companyid = $request->companyid;
	}
	if(!isEmptyString($companyid)){
		if($companyid == DEFAULT_COMPANYID){
			$where_query .= " AND (u.companyid = '".$companyid."' OR u.companyid is null) ";
		} else {
			$where_query .= " AND u.companyid = '".$companyid."' ";
		}
	}
	
	$order = trim($request->order);
	$order_query = " ORDER BY u.datecreated DESC, u.id desc ";
	
	$sortcolumn = $request->sortby;
	$sortorder = $request->sortorder;
	if(!isEmptyString($sortcolumn) && !isEmptyString($sortorder)){
		$order_query = " ORDER BY " . $sortcolumn. " " .$sortorder. " ";
	}
	// f.orgname as fundername, concat(u.firstname,' ',u.lastname) as supervisorname
	$paginate->processPost($request->getParams());
	$all_results_query = "SELECT 
		u.id as uid, 
		IF(isnull(u.othername), concat(u.firstname,' ',u.lastname), concat(u.firstname,' ',u.lastname,' ',u.othername)) as `name`, u.username, concat(mc.firstname, ' ', mc.lastname, ' ', mc.othername) as addedby, 
		u.phone, u.phone2, u.email, 
		u.profilephoto, u.gender, u.dateofbirth, u.bio, 
		u.datecreated as mdatecreated, u.createdby as mcreatedby, u.activationdate, u.startdate, u.enddate, u.probationend,
		u.country, u.address1 as address1, u.town,
		u.status as `status`, u.salutation, u.position, u.isinvited,
		u.dateofbirth, u.dateofbirth, u.position, u.empstatus, u.departmentid, u.managerid,
		g.groupid as groupid, acg.name as `Group`
		 FROM useraccount u
		 left join useraccount mc on (u.createdby = mc.id)
		 left join aclusergroup as g ON (u.id = g.userid) 
		 inner join aclgroup as acg ON (u.type = acg.id)
	 ".$where_query." ".$paginate->getSearchAndFilterSQL()." GROUP BY u.id ".$order_query;
	// debugMessage($all_results_query); // exit;
	
	$paginate->setItemCountFromSQLQuery($all_results_query);
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	
	$listurl = $this->baseUrl('profile/list');
	$addurl = $this->baseUrl($controller);
	$title = "Employees";
	$listitems = "Employees";
	$moduleitem = "Employee";
	$description = '';
	$icon = 'glyphicon glyphicon-user';
	$resource = 'User Account';
	$salutations =  getDatavariables('SALUTATION'); 
	$employeesstatuses = getDatavariables('EMPLOYEE_STATUS');
	$departments = getDepartments();
	$positions = getDatavariables('EMPLOYEE_POSITIONS');
	// $rate = getNssfCompanyRate();
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
		$('.titlelabel').html('<?php echo $title.$customlabel; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
		
	});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div class="row">
	<div class="col-sm-12">
    	<form class="form-horizontal" action="<?php echo $this->baseUrl($controller."/listsearch"); ?>" method="get" id="listform">
		<div class="box box box-color xbox-bordered">
			<div class="box-title noheader">
                <h3></h3>
            </div>
            <div class="box-content" style="padding: 5px 0px;">
                <div class="row">
                    <div class="col-sm-9">
                        <ul class="resetlist listactions">
                            <?php if ($acl->checkPermission($resource, ACTION_CREATE)) { ?>
                                <li><a title="New <?php echo $moduleitem; ?>" class="btn btn-primary xbtn-sm blockanchor" href="<?php echo $addurl; ?>">New <?php echo $moduleitem; ?></a></li>
                            <?php } ?>
                            <li>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('departmentid',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Departments'), $departments),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array("xautofilter", "form-control", 'width150', 'input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($request->getParam('departmentid')); 
                                    echo $dropdown->render();
                                ?>                    
                            </li>
                             <li>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('position',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Positions'), $positions),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array("xautofilter", "form-control",'width150', 'input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($request->getParam('position')); 
                                    echo $dropdown->render();
                                ?>                    
                            </li>
                            <li>
                                <?php
                                    $dropdown = new Zend_Form_Element_Select('empstatus',
                                                        array(
                                                            'multiOptions' => array_merge_maintain_keys(array('' => 'All Contract Types'), $employeesstatuses),
                                                            'view' => new Zend_View(),
                                                            'decorators' => array('ViewHelper'),
                                                            'class' => array("xautofilter", "form-control", 'width150', 'input-sm')
                                                        )
                                    );  
                                    $dropdown->setValue($request->getParam('empstatus')); 
                                    echo $dropdown->render();
                                ?>                    
                            </li>
                            <?php if(isAdmin()){ ?>
                                <li>
                                    <?php
                                        $dropdown = new Zend_Form_Element_Select('type',
                                                            array(
                                                                'multiOptions' => array_merge_maintain_keys(array('' => 'All User Types'), $allroles),
                                                                'view' => new Zend_View(),
                                                                'decorators' => array('ViewHelper'),
                                                               'class' => array("autofilter", "form-control", 'width150', 'input-sm')
                                                            )
                                        );  
                                        $dropdown->setValue($request->getParam('type')); 
                                        echo $dropdown->render();
                                    ?>                    
                                </li>
                            <?php } ?>
                            <li>
                                <button type="submit" class="btn btn-default btn-sm blockanchor" id="filter"><i class="fa fa-filter"></i></button>
                            </li>
                        </ul>
                    </div>
                    <div class="col-sm-3">
                        <div class="divider5"></div>
                        <div class="col-sm-12 padding0">
                            <div class="input-group">
                                <input name="searchterm" id="searchterm" class="form-control form-search" value="<?php echo $request->searchterm; ?>" type="text" placeholder="Search..." />
                                <span class="input-group-addon"><i class="fa fa-search"></i></span>
                            </div>
                        </div>	
                        <input type="hidden" name="letter" id="letter" value="<?php echo $request->getParam('letter'); ?>" />
                        <input type="hidden" name="style" id="style" value="<?php echo $style; ?>" />
                        <input type="hidden" name="exporttrigger" id="exporttrigger" value="<?php echo $request->exporttrigger; ?>" />
                    </div>
                </div>
                <div class="row">
					<div class="col-sm-12">
						<div class="box box-color box-bordered">
							<div class="box-title condensed">
								<h3><i class="glyphicon-group"></i> List of Employees</h3>
                                <div class="actions">
                                	<a class="btn bluelinks" href="<?php echo $this->baseUrl('report/employeedetails'); ?>">View Detailed Employee Report</a> &nbsp;
                                	<a href="<?php echo $listurl; ?>" title="Reset List and Clear all Filters" rel="tooltip"><i class="fa fa-refresh"></i></a> &nbsp;
                                </div>
							</div>
							<div class="box-content nopadding">
								<div class="row-fluid peoplelist clearfix <?php echo $style == '2' ? 'whitebg' : ''; ?>">
                                    <?php if($has_no_data){ ?>
                                        <div class="alert alert-warning"><?php echo $this->translate("global_list_noentries"); ?></div>
                                    <?php } else { ?>
                                        <div class="divider10"></div>
                                            <?php
                                                foreach($result as $line){
                                                    $viewurl = stripUrl($this->baseUrl('profile/view/id/'.encode($line['uid'])));
                                                    $indexurl = stripUrl($this->baseUrl('profile/index/id/'.encode($line['uid'])));
                                                    
                                                    $isme = false;
                                                    if($line['uid'] == $userid){
                                                        $isme = true;
                                                    }
                                                    $allowedit = false;
                                                    if($acl->checkPermission("User Account", ACTION_EDIT)){
                                                        $allowedit = true;
                                                    }
													// debugMessage($line);
                                            ?>
                                                 <div class="col-xs-12 col-sm-6">
                                                    <div class="peoplewrapper makerelative">
                                                        <div class="btn-group gridactions" style="z-index:10;">
                                                            <button type="button" class="btn btn-default btn-xs dropdown-toggle noround" data-toggle="dropdown">Action <span class="caret"></span></button>
                                                            <ul class="dropdown-menu" role="menu" style="left:-160px; top:0;">
                                                                <?php if ($acl->checkPermission("User Account", ACTION_VIEW)) { ?>
                                                                    <li><a class="blockanchor" href="<?php echo $viewurl; ?>">View Profile</a></li>
                                                                <?php } ?>
                                                                <?php if ($allowedit) { ?>
                                                                    <li><a class="blockanchor" href="<?php echo $indexurl; ?>">Update</a></li>
                                                                <?php } ?>
                                                                <?php if(!isEmptyString($line['email']) && $acl->checkPermission('Message', ACTION_CREATE)){ ?>
                                                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('notifications/index/userid/'.encode($line['uid']).'/type/1'); ?>">Send Mail</a></li>
                                                                <?php }?>
                                                                <?php if(!isEmptyString($line['phone']) && $acl->checkPermission('SMS', ACTION_CREATE)){ ?>
                                                                    <li><a class="blockanchor" href="<?php echo $this->baseUrl('notifications/index/userid/'.encode($line['uid']).'/type/2'); ?>">Send SMS</a></li>
                                                                <?php } ?>
                                                                <?php if ($allowedit && $line['status'] == 0 ) { ?>
                                                                    <li><a class="blockanchor confirm-dialog gonowhere" action="<?php echo $this->baseUrl('profile/inviteuser/id/'.$line['uid'].'/successurl/'.encode($this->viewurl)); ?>" message="Resend activation instructions to User's Email?"><?php echo $line['isinvited'] == 1 ? 'Resend' : 'Send'; ?> Activation</a></li>
                                                                <?php } ?>
                                                                <?php if($acl->checkPermission('User Account', ACTION_DELETE) && $line['status'] == 1){ ?>
                                                                    <li><a class="blockanchor confirm-dialog gonowhere" action="<?php echo $this->baseUrl('profile/resetpassword/id/'.encode($line['uid']).'/successurl/'.encode($this->viewurl)); ?>" message="Are you sure you want to reset <?php echo $line['name']; ?>'s Password?">Reset Password</a></li>
                                                                <?php } ?>
                                                            </ul>
                                                        </div>
                                                        <div class="col-sm-3 padding0 centeralign">
                                                            <a href="<?php echo $viewurl; ?>" class="blockanchor centeralign"><img class="imagecontainer imagecontainer thumb img-thumbnail" src="<?php echo getImagePath($line['uid'], $line['profilephoto'], $line['gender']); ?>" style="width:80%; text-align:center;" /></a>
                                                        </div>
                                                        <div class="peopleinfo col-sm-9">
                                                            <h4><a href="<?php echo $viewurl; ?>" class="blockanchor"><?php echo $line['name']; ?></a></h4>
                                                            <div class="row-fluid margin0">
                                                                <div class="col-sm-7 padding0">
                                                                    <ul class="resetlist">
                                                                        <li><span class="bolded">Position:</span> <span class="nullifempty"><?php echo isArrayKeyAnEmptyString($line['position'], $positions) ? '' : $positions[$line['position']]; ?></span></li>
                                                                        <li><span class="bolded">Department: </span> <span class="nullifempty"><?php echo isArrayKeyAnEmptyString($line['departmentid'], $departments) ? '' : $departments[$line['departmentid']]; ?></span></li>
                                                                        <li><span class="bolded">Contract Status: </span><span class="nullifempty"><?php echo isArrayKeyAnEmptyString($line['empstatus'], $employeesstatuses) ? '':$employeesstatuses[$line['empstatus']]; ?></span></li>
                                                                        <li><span class="bolded">Account Status: </span> <span class="nullifempty"><?php echo getUserStatus($line['status']); ?></span></li>
                                                                    </ul>
                                                                </div>
                                                                <div class="col-sm-5 padding0">
                                                                    <ul class="resetlist">
                                                                        <li><span class="bolded">Contacts</span></li>
                                                                        <li><span class="nullifempty"><?php echo snippet($line['email'], '23','...'); ?></span></li>
                                                                        <li><span class="nullifempty"><?php echo $line['phone']; ?></span></li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                           <?php } ?> 
                                    <?php } ?>
                                    <?php if(!$has_no_data){ ?> 
                                        <div class="row">
                                            <div class="col-sm-12">
                                                <div class="form-actions">
                                                    <div class="col-sm-3 paddingleft5 floatleft"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                                                    <div class="col-sm-6 padding0"><?php echo $paginate->getPaginationLinks(); ?></div>
                                                    <div class="col-sm-3 padding0 rightalign"><?php echo $paginate->getListCountDropDown(); ?></div>
                                                </div>
                                            </div>
                                        </div>
                                    <?php } ?>
								</div>
							</div>
						</div>
					</div>
          		</div>
			</div>
        </div>
        </form>          
	</div>            
</div>        
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
