<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$id = decode($request->id);
	if(isEmptyString($id)){
		$id = $userid;
	}
	
	$user = new UserAccount();
	$user->populate($id);
	
	$title = $user->getName(); $subtitle = "Upload Profile Photo";
	if(!isEmptyString($request->crop)){
		$subtitle = "Crop Profile Photo"; 
	}
	// debugMessage($user->getMediumPicturePath());
	$posturl = $this->baseUrl("profile/processpicture");
	$pageid = "profile_picture";
	$this->headTitle($title.$browserappend);
	$description = 'Upload a profile Image';
	
?>
<script type="text/javascript" src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/custom/jquery.imgareaselect.dev.js')); ?>"></script>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.' Employees / '.$user->getName()." / Upload Photo"; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="glyphicon glyphicon-user"></span>');
	
	$("#profileimage").change(function(){
		if(!isEmptyString($(this).val())){
			$(".fileinput-preview").html($(this).val());
		}
	});
	$("#filenamedisplay").click(function(e){
		$("#profileimage").trigger('click');
	});
	
	<?php if(isEmptyString($request->crop)){ ?>
		// form validation
		$("#indexform").validate({		
			// define the validation rules one field at a time
			rules: {
				profileimage: "required"
			}, 
			// the messages for each of the fields being validated
			messages: {		
				profileimage: "Please browse for image on computer"
			},
			// custom error positions
			errorPlacement: function(error, element) {
				switch(element.attr("name")){					
					default:
						if(element.hasClass("useid_error")){
							error.appendTo("#"+element.attr("id")+"_error");
						} else {
							error.appendTo("#"+element.attr("name")+"_error");
						}
						break;
				}			
			}
		});
	<?php } else { ?>
		$('#photo').imgAreaSelect({ 
			aspectRatio: '1:1', 
			handles: true,
			fadeSpeed: 200, 
			minWidth: 100,
			maxWidth: 350,
			x1: 0, y1: 0, x2: 200, y2: 200,
			/*onSelectChange: preview,*/
			onSelectEnd: function (img, selection) {
				$('#x1').val(selection.x1);
				$('#y1').val(selection.y1);
				$('#x2').val(selection.x2);
				$('#y2').val(selection.y2);
				$('#w').val(selection.width);
				$('#h').val(selection.height);            
			}
		});
	<?php } ?>
}); 
</script>
<div class="row-fluid margin0">
    <div class="col-sm-12" style="margin-top:10px;">
        <fieldset class="fieldsetcontainer">
            <legend><?php echo $subtitle; ?></legend>
            <div class="panel-body xwell-sm">
                <div class="col-sm-3">
                    <h6 class="well-legend">Current Photo</h6>
                    <div id="profileinfo" style="margin-top:15px;">
                        <img id="xprofileimage" src="<?php echo $user->getMediumPicturePath(); ?>" />
                    </div>
                </div>
                <div class="col-sm-9">
                    <?php if(isEmptyString($request->crop)){ ?>
                        <form id="indexform" class="form-horizontal" role="form" action="<?php echo $posturl; ?>" method="post" enctype="multipart/form-data">
                            <div class="divider30"></div>
                            <label class="blocked small">Upload new Photo. (Max size <?php echo formatBytes($config->uploads->photomaximumfilesize); ?>)</label>
                            <div class="width200">
                                <div class="fileinput-holder input-group col-sm-12 padding0" id="theresume">
                                    <div id="filenamedisplay" class="fileinput-preview uneditable-input form-control">No file selected..</div>
                                    <div class="input-group-btn">
                                        <span class="fileinput-btn btn btn-default">Browse
                                            <input type="file" name="profileimage" id="profileimage" class="form-control file input-sm inline" data-style="fileinput" />
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
                            <input type="hidden" class="successurl" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo $this->baseUrl('profile/view/id/'.encode($user->getID())); ?>" />
                            <input type="hidden" class="failureurl" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo $this->baseUrl('profile/picture/id/'.encode($user->getID())); ?>" />
                            <div id="profileimage_error"></div>
                            <div class="divider30"></div>
                            <button style="" type="submit" class="btn btn-success" id="upload" name="submit">Upload</button> or <a href="<?php echo $this->baseUrl("profile/view/id/".encode($user->getID())); ?>"><?php echo $this->translate('global_button_cancel'); ?></a>&nbsp;
                        </form>  
                    <?php } else { ?>
                        <form action="<?php echo $this->baseUrl("profile/croppicture"); ?>" id="indexform" method="post" role="form">
                            <div class="divider30"></div>
                            <h4>Resize/Crop Photo</h4>
                            <div class="divider10"></div>
                            <img src="<?php echo $user->getLargePicturePath(); ?>" id="photo" />
                            <input type="hidden" name="x1" id="x1" value="0" />
                            <input type="hidden" name="y1" id="y1" value="0" />
                            <input type="hidden" name="x2" id="x2" value="200" />
                            <input type="hidden" name="y2" id="y2" value="200" />
                            <input type='hidden' name='w' id="w" value='200' />
                            <input type='hidden' name='h' id="h" value='200' />
                            <input type="hidden" id="id" name="id" value="<?php echo encode($user->getID()); ?>" />
                            <div class="divider30"></div>
                            <button type="submit" class="cancel btn btn-default">Cancel and Re-upload</button> &nbsp; 
                            <button type="submit" id="startcrop" class="btn btn-success">Crop Photo</button>
                        </form>
                    <?php } ?>
                </div>
            </div>
        </fieldset>
    </div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
