<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$useraccount = new UserAccount();
	if ($sessionhaserror) {
	    $useraccount->processPost($session->getVar(FORM_VALUES)); 
	}
	
	$pageid = "user_login";
	$title = "LOGIN";
	$this->headTitle($title.$browserappend);
?>
<link rel="stylesheet" href="<?php echo $this->baseUrl('stylesheets/plugins/icheck/all.css'); ?>">
<script src="<?php echo $this->baseUrl('javascript/plugins/icheck/jquery.icheck.min.js'); ?>"></script>
<script>
$(document).ready(function() {
	$("#email").focus();
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			email: {
				"required": true
			},
			password: "required"
		}, 
		messages: {
			email: {
				"required": "<?php echo $this->translate("profile_credential_error"); ?>"
			},
			password: "<?php echo $this->translate("profile_password_error"); ?>"
		}
	});
	
}); 
</script>

<div id="<?php echo $pageid; ?>">
	<div class="wrapper" style="margin-top:-250px;">
		<h1>
			<a href="<?php echo $this->baseUrl('index'); ?>"><img src="<?php echo $this->baseUrl('images/logo-big.png'); ?>" class='retina-ready' width="59" height="49"><?php echo getAppName(); ?></a>
		</h1>
		<div class="login-body">
			<h2>SIGN IN</h2>
            <div class="row">
                <div class="col-sm-12">
                    <?php if (!isEmptyString($session->getVar(SUCCESS_MESSAGE))) { ?>
                        <div class="alert alert-success alert-dismissable"><button data-dismiss="alert" class="close" type="button">×</button><?php echo $session->getVar(SUCCESS_MESSAGE); ?>
                        </div>
                    <?php } ?>
                    <?php if($sessionhaserror) { ?>
                        <div class="alert alert-danger alert-dismissable"><button data-dismiss="alert" class="close" type="button">×</button><?php echo $session->getVar(ERROR_MESSAGE); ?></div>
                    <?php } ?>
                    <?php if(!isEmptyString($request->redirecturl)){ ?>
                        <div class="alert alert-info">Session timeout. Please login to continue</div>
                    <?php } ?>
                </div>
            </div>
			<form action="<?php echo $this->baseUrl('user/checklogin'); ?>" method="post" id="indexform">
				<div class="form-group">
					<div class="email controls">
						<input type="text" name='email' placeholder="Username or Email address" class='form-control' />
					</div>
				</div>
				<div class="form-group">
					<div class="pw controls">
						<input type="password" name="password" placeholder="Password" class='form-control' />
					</div>
				</div>
				<div class="submit">
					<div class="remember">
						<input type="checkbox" name="remember" class='icheck-me' data-skin="square" data-color="blue" id="remember">
						<label for="remember">Remember me</label>
					</div>
					<input type="submit" value="Sign me in" class='btn btn-primary'>
                    <input name="redirecturl" type="hidden" value="<?php echo $request->redirecturl;  ?>" />
                    <input name="<?php echo URL_FAILURE; ?>" type="hidden" value="<?php echo encode($this->viewurl);  ?>" />
				</div>
			</form><!---->
			<div class="forget">
				<a href="<?php echo $this->baseUrl("user/recoverpassword")?>" class="blockanchor"><span>Forgot password?</span></a>
			</div>
		</div>
	</div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>