<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	$listurl = $this->baseUrl('config/globalconfig');
	$listitems = "Variables";
	$description = 'Application settings';
	$title = $columnheading = "Settings";
	
	$showsearch = true;
	$section = $request->getParam('section'); // debugMessage('>> '.$section);
	$columnheading = "Settings";
	if(!isEmptyString($section)){
		$currentlookup = new AppConfig();
		$current = $currentlookup->getCurrentSection($section);
		// debugMessage($current->toArray());
		
		$appconfig = new AppConfig();
		$variables = $appconfig->getLookupOptions($current->getSection());
		// debugMessage($variables->toArray());
		$columnheading = $current->getSectionDisplay();
	}
	
	$this->headTitle($title.$browserappend);
?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.'Global Config / '.$columnheading; ?>');
	$('.titlelabel').html("<?php echo $title; ?>");
	$('.desclabel').html("<?php echo $description; ?>");
	$('.pageicon').html('<span class="glyphicon glyphicon-list-alt"></span>');
	
	
});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div class="row">
    <div class="col-sm-9">
        <div class="box">
            <div class="box-title">
                <h3><i class="fa fa-table"></i><?php echo $columnheading; ?></h3>
            </div>
            <div class="box-content nopadding">
            	<form id="indexform" name="indexform" class="form-horizontal" action="<?php echo $this->baseUrl('config/processglobalconfig'); ?>" method="post">
                    <div class="divider5"></div>
                    <div class="row">
                        <div class="col-sm-12">
                            <?php if(in_array($current->getSection(), array('api','system','sms'))){ ?>
                                <div class="alert alert-warning">These are very sensitive settings. Be sure you know the implication of commiting any updates.</div>
                             <?php } ?>
                        </div>
                    </div>
                    <div class="divider5"></div>
                    <table class="table margin0 table-bordered table-striped table-colored-header">
                        <thead>
                            <td style="width:25px;" class="centeralign">#</td>
                            <td>Description</td>
                            <td style="width:50%;">Actual Value</td>
                        </thead>
                        <tbody>
                            <?php
                                $t = 1;
                                foreach($variables as $option){
                                    $id = $option->getID();
                                    
                            ?>
                                <tr id="lookup_<?php echo $t; ?>" class="editable">
                                    <td class="centeralign"><?php echo $t; ?>
                                        <input type="hidden" name="t_<?php echo $t; ?>" id="t_<?php echo $t; ?>" value="<?php echo $t; ?>" />
                                    </td>
                                    <td>
                                        <?php if($option->isEditable()){ ?>		
                                            <input type="text" name="displayname_<?php echo $t; ?>" id="displayname_<?php echo $t; ?>" class="form-control readonlyfield readonly" style="width:95%; padding:4px;" value="<?php echo $option->getDisplayName(); ?>" />
                                        <?php } else { ?>    
                                            <?php echo $option->getDisplayName(); ?>
                                            <div class="alert alert-info" style="margin:10px;">Updates to this option are currently disabled.</div>
                                        <?php } ?>
                                        <input type="hidden" name="id_<?php echo $t; ?>" id="id_<?php echo $t; ?>" value="<?php echo $option->getID(); ?>" />
                                        <div id="displayname_<?php echo $t; ?>_error"></div>
                                    </td>
                                    <td>
                                        <?php if($option->isEditable()){ ?>		
                                            <input type="text" name="optionvalue_<?php echo $t; ?>" id="optionvalue_<?php echo $t; ?>" class="form-control"  style="width:95%; padding:4px;" value="<?php echo $option->getOptionValue(); ?>" />
                                        <?php } else { ?>    
                                            <?php echo $option->getOptionValue(); ?>
                                            <div class="alert alert-info" style="margin:10px;">Updates to this option are currently disabled.</div>
                                        <?php } ?>
                                        <div id="optionvalue_<?php echo $t; ?>_error"></div>
                                    </td>
                                    <td class="hidden"><?php echo $option->getOptionName(); ?></td>
                                </tr>
                            <?php $t++; } ?>
                            <input type="hidden" name="t" value="<?php echo $variables->count(); ?>" />
                            <input type="hidden" name="entityname" value="AppConfig" />
                            <input type="hidden" id="section" name="section" value="<?php echo $current->getSection(); ?>" />
                            <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="Successfully updated" /> 
                            <input type="hidden" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($this->baseUrl('config/globalconfig/section/'.$current->getSection())); ?>" /> 
                        </tbody>
                    </table>
                    <div class="divider10"></div>
                    <div class="form-actions testborder clearfix">
                        <button type="submit" class="btn btn-green btn-large pull-right savebutton">Save Changes</button>
                    </div>
               	</form>
            </div>
        </div>
    </div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>