<?php
	include APPLICATION_PATH.'/includes/header.php';
	
	$shift = new Shift();
	$id = decode($request->id);
	
	if(isEmptyString($request->id)){
		$pagetitle = 'New Work Shift';
		$button_title = $this->translate('global_button_save'); 
		$successmessage = $this->translate('global_save_success'); 
		$posturl = $this->baseUrl("config/shiftscreate");
		$shift->setcompanyid($companyid);
	} else {
		$shift->populate(decode($request->id)); 
		$pagetitle = 'Update Shift';
		$button_title = $this->translate('global_button_save_changes'); 
		$successmessage = $this->translate('global_update_success'); 
		$posturl = $this->baseUrl("config/shiftscreate");
	}
	
	$successurl = $this->baseUrl('config/shifts');
	$addnewsuccessurl = $this->baseUrl("config/shiftsindex");
	$failureurl = $this->viewurl;
	
	if(!isEmptyString($session->getVar(ERROR_MESSAGE))){ 
		$shift->processPost($session->getVar(FORM_VALUES));	
	}
	
	$icon = "";
	$description = "";
	$pageid = "config_shift";
	$title = "Work Shifts";
	$this->headTitle($title.$browserappend);
?>
<?php if(false){ ?>
<script src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/datepicker/bootstrap-datepicker.js')); ?>"></script>
<script src="<?php echo $this->serverUrl($this->baseUrl('javascript/plugins/timepicker/bootstrap-timepicker.min.js')); ?>"></script>
<link href='<?php echo $this->baseUrl('stylesheets/plugins/datepicker/datepicker.css'); ?>' rel='stylesheet' type='text/css'>
<link href='<?php echo $this->baseUrl('stylesheets/plugins/timepicker/bootstrap-timepicker.min.css'); ?>' rel='stylesheet' type='text/css'>
<?php } ?>
<script>
$(document).ready(function() {
	$('.titlebreadcrumb').html('<?php echo $homedir.$title.' / '.$pagetitle; ?>');
	$('.titlelabel').html('<?php echo $title; ?>');
	$('.desclabel').html('<?php echo $description; ?>');
	$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
	
	$("#indexform").validate({		
		// define the validation rules one field at a time
		rules: {
			name: "required",
			starttime: "required",
			endtime: "required",
			hours: {
				required: true
			}
		}, 
		// the messages for each of the fields being validated
		messages: {		
			name: "<?php echo $this->translate("global_name_error"); ?>",
			starttime: "Please select Start Time",
			endtime: "Please select End Time",
			hours: {
				required: "Please specify Hours"
			}
		}
	});
	
	/*$('.timepicker').pickatime({
	   interval: 15
	});	*/
	<?php if(isEmptyString($shift->getStartTime())){ ?>
		$('#starttime').val('');
	<?php } ?>
	<?php if(isEmptyString($shift->getEndTime())){ ?>
		$('#endtime').val('');
	<?php } ?>
	<?php if(isEmptyString($shift->getoverduestarttime())){ ?>
		$('#overduestarttime').val('');
	<?php } ?>
	
});
</script>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div id="<?php echo $pageid; ?>">
	<div class="row">
		<div class="col-sm-8">
        	<div class="box box-color box-bordered">
                <div class="box-title">
                    <h3><i class="fa fa-th-list"></i> <?php echo $pagetitle; ?></h3>
                </div>
                <div class="box-content nopadding">
                    <form class="form-horizontal xform-validate form-bordered" action="<?php echo $posturl; ?>" method="post" id="indexform">
                        <input name="entityname" id="entityname" type="hidden" value="Shift" />
                        <input type="hidden" id="id" name="id" value="<?php echo encode($shift->getID()); ?>" />
                        <input type="hidden" id="companyid" name="companyid" value="<?php echo $shift->getCompanyID(); ?>" />
                        <input name="successmessage" id="successmessage" type="hidden" value="<?php echo $successmessage; ?>" />  
                        <input type="hidden" id="<?php echo SUCCESS_MESSAGE; ?>" name="<?php echo SUCCESS_MESSAGE; ?>" value="<?php echo $successmessage; ?>" /> 
                        <input type="hidden" id="<?php echo URL_SUCCESS; ?>" name="<?php echo URL_SUCCESS; ?>" value="<?php echo encode($successurl); ?>" /> 
                        <input type="hidden" id="nosuccessid" name="nosuccessid" value="1" /> 
                        <input type="hidden" id="<?php echo URL_FAILURE; ?>" name="<?php echo URL_FAILURE; ?>" value="<?php echo encode($failureurl); ?>" /> 
                        <div class="form-group">
                            <label class="col-sm-3 control-label"><?php echo $this->translate("global_name_label"); ?>: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control input-sm width300" id="name" name="name" value="<?php echo $shift->getName(); ?>" /><div id="name_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Shift Start Time: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-9">
                                <input type="text" name="starttime" id="starttime" class="form-control input-sm timepicker timepick inline width100" value="<?php echo date("h:i A", strtotime($shift->getStartTime())); ?>" /><div id="starttime_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Shift End Time: <?php echo $this->translate("global_required_field_marker"); ?></label>
                            <div class="col-sm-9">
                                <input type="text" name="endtime" id="endtime" class="form-control input-sm timepicker timepick inline width100" value="<?php echo date("h:i A", strtotime($shift->getEndTime())); ?>" /><div id="endtime_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Overdue Checkout <span class="blocked">Start Time <?php echo $this->translate("global_required_field_marker"); ?>:</span></label>
                            <div class="col-sm-9">
                                <input type="text" name="overduestarttime" id="overduestarttime" class="form-control input-sm timepicker timepick inline width100" value="<?php echo date("h:i A", strtotime($shift->getoverduestarttime())); ?>" /><div id="overduestarttime_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Break Duration: <span class="blocked notbolded">(Hrs)</span></label>
                            <div class="col-sm-9">
                                <input type="text" name="breakhours" id="breakhours" class="form-control input-sm width100 isdecimal centeralign" value="<?php echo $shift->getbreakhours(); ?>" /><div id="breakhours_error"></div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Actual Shift Duration: <?php echo $this->translate("global_required_field_marker"); ?><span class="blocked notbolded">(Hrs)</span></label>
                            <div class="col-sm-9">
                                <input type="text" name="hours" id="hours" class="form-control input-sm width100 isdecimal centeralign" value="<?php echo $shift->getHours(); ?>" /><div id="hours_error"></div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <a class="btn cancel gonowhere" type="button"><?php echo $this->translate('global_button_cancel'); ?></a>
                            <?php if(isEmptyString($request->id)){ ?>
                                <button class="btn btn-primary btn-green changesuccessurl savebutton" successurl="<?php echo encode($addnewsuccessurl); ?>" type="submit">Save and Add New</button>
                            <?php } ?>
                            <button class="btn btn-primary btn-green changesuccessurl savebutton" type="submit" successurl="<?php echo encode($successurl); ?>"><?php echo $button_title; ?></button>
                        </div>
                    </form>
                </div>
            </div>
      	</div>
   	</div>
</div>
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
