<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = "Work Shifts";
	
	$style = '2';
	if(!isEmptyString($request->style)){
		$style = $request->style;
		$session->setVar('style', $request->style);
	}
	if(isEmptyString($request->style) && !isEmptyString($session->getVar('style'))){
		$style = $session->getVar('style');
	}
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("s.name"));
	$paginate->setDefaultSortBy("s.name");	
	$paginate->setItemCountPerPage("ALL");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE s.id <> '' ";
	$allowclear = false;
	
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	$paginate->processPost($request->getParams());
	$all_results_query = "select s.id as id, s.name, s.starttime, s.endtime, s.overduestarttime, s.breakhours, s.hours from shift s WHERE s.name <> '' ".$paginate->getSearchAndFilterSQL()." GROUP BY s.id ".$paginate->getSortSQL();
	
	# debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	$isdatatable = false;
	
	$listurl = $this->baseUrl('config/shifts');
	$addurl = $this->baseUrl('config/shiftsindex');
	$moduleitem = "Work Shift";
	$resource = "System Config"; // $resource = "Department";
	$icon = "glyphicon glyphicon-cog";
	
	$description = '';
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
		$('.titlelabel').html('<?php echo $title; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
		
	});
</script>
<style>
</style>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div class="row">
	<div class="col-sm-12">
		<div class="box box box-color box-bordered">
			<div class="box-title noheader">
                <h3></h3>
            </div>
            <div class="box-content nopadding">
            	<?php if(!$isdatatable){ ?>
                	<div class="divider5"></div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="col-sm-8">
                            	<ul class="resetlist listactions">
                            		<?php if ($acl->checkPermission($resource, ACTION_CREATE)) { ?>
                                    	<li><a class="btn btn-primary btn-sm" href="<?php echo $this->baseUrl('config/shiftsindex'); ?>"> New <?php echo $moduleitem; ?></a></li>
                                 	<?php } ?>
                               	</ul>
                            </div>
                            <div class="col-sm-3"></div>
                        </div>
                    </div>
                    <div class="divider5"></div>
                <?php } ?>
                <table class="table table-nomargin table-bordered table-striped table-hover <?php echo $isdatatable == true ? 'dataTable' : ''; ?>" id="">
					<thead>
                        <tr>
                            <th style="vertical-align:top;">Session Name</th>
                            <th style="width:15%; vertical-align:top;">Start Time</th>
                            <th style="width:15%; vertical-align:top;">End Time</th>
                            <th style="width:15%; vertical-align:top;">Overdue Time</th>
                            <th style="width:15%; vertical-align:top;">Break Duration (Hrs)</th>
                            <th style="width:15%; vertical-align:top;">Actual Duration (Hrs)</th>
                            <th style="width:100px; vertical-align:top;"></th>
                        </tr>
					</thead>
                    <tbody>
                    	<?php if($has_no_data){ ?>
                        	<tr><td colspan="20"><div class="alert alert-warning"><?php echo $this->translate("global_list_noentries"); ?></div></td></tr>
                        <?php } ?>
						<?php
                            foreach($result as $line){
                                $indexurl = $this->baseUrl('config/shiftsindex/id/'.encode($line['id']));
                        ?>
                            <tr>
                                <td class="nullifempty"><?php echo $line['name']; ?></td>
                                <td class="nullifempty centeralign"><?php echo formatTimeCustom($line['starttime']); ?></td>
                                <td class="nullifempty centeralign"><?php echo formatTimeCustom($line['endtime']); ?></td>
                                <td class="nullifempty centeralign"><?php echo formatTimeCustom($line['overduestarttime']); ?></td>
                                <td class="nullifempty centeralign"><?php echo formatNumber($line['breakhours']); ?></td>
                                <td class="nullifempty centeralign"><?php echo formatNumber($line['hours']); ?></td>
                                <td>
                                    <?php if ($acl->checkPermission($resource, ACTION_EDIT)) { ?>
                                        <a class="btn inline blockanchor" href="<?php echo $indexurl; ?>" title="Update" rel="tooltip"><i class="fa fa-edit"></i></a> &nbsp;
                                    <?php } ?>
                                    <?php if ($acl->checkPermission($resource, ACTION_DELETE)) { ?>
                                        <a class="btn deleteline" action="<?php echo $this->baseUrl('config/delete/id/'.encode($line['id'])."/entityname/Shift/successurl/".encode($this->viewurl)); ?>" message="<?php echo $this->translate('global_delete_confirm_message'); ?>" title="Delete" rel="tooltip"><i class="fa fa-times"></i></a>
                                    <?php } ?>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
               	</table>
                <?php if(!$isdatatable){ ?>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-actions">
                                <div class="col-sm-3 paddingleft5 floatleft"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                                <div class="col-sm-6 padding0"><?php echo $paginate->getPaginationLinks(); ?></div>
                                <div class="col-sm-3 padding0 rightalign"><?php echo $paginate->getListCountDropDown(); ?></div>
                            </div>
                        </div>
                    </div>
                    <div class="divider5"></div>
                <?php } ?>
        	</div>
       	</div>
   	</div>
</div>    
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>

