<?php
	require_once APPLICATION_PATH.'/includes/header.php';
	
	# Page title
	$title = "Leave Categories";
	
	$style = '2';
	if(!isEmptyString($request->style)){
		$style = $request->style;
		$session->setVar('style', $request->style);
	}
	if(isEmptyString($request->style) && !isEmptyString($session->getVar('style'))){
		$style = $session->getVar('style');
	}
	
	# Create an instance of the class to handle the pagination
	$paginate = new Pagination();	
	$paginate->setView($this);
	# set the search columns to be used on this list
	$paginate->setSearchColumns(array("t.name"));
	$paginate->setDefaultSortBy("t.name");	
	$paginate->setItemCountPerPage("25");
	
	# define the letter to be clicked to ease navigation 
	$where_query = " WHERE t.id <> '' ";
	$allowclear = false;
	
	if(!isEmptyString($request->searchterm)){
		$allowclear = true;
	}
	
	$paginate->processPost($request->getParams());
	$all_results_query = "select t.id as id, t.name, t.description, t.defaultquantity, t.quantitytype, t.calendarcolor, t.deductfromallowance, t.paid, t.bookable, t.authorised, t.viewoncalendar from leavetype t WHERE t.name <> '' ".$paginate->getSearchAndFilterSQL()." GROUP BY t.id ".$paginate->getSortSQL();
	
	# debugMessage($all_results_query);
	$paginate->setItemCountFromSQLQuery($all_results_query);
	
	$current_results_query = $all_results_query." ".$paginate->getSQLLimit();
	//echo $current_results_query;
	$session->setVar(ALL_RESULTS_QUERY, $all_results_query);
	$session->setVar(CURRENT_RESULTS_QUERY, $current_results_query);
	
	$conn = Doctrine_Manager::connection(); 
	$result = $conn->fetchAll($current_results_query);
	$has_no_data = (count($result) == 0) ? true : false; 
	$isdatatable = false;
	
	$listurl = $this->baseUrl('config/leave');
	$addurl = $this->baseUrl('config/leaveindex');
	$moduleitem = "Leave Type";
	$resource = "System Config"; // $resource = "Department";
	$icon = "glyphicon glyphicon-cog";
	
	$description = '';
	$this->headTitle($title.$browserappend);
?>
<script>
	$(document).ready(function() {
		$('.titlebreadcrumb').html('<?php echo $homedir.$title; ?>');
		$('.titlelabel').html('<?php echo $title; ?>');
		$('.desclabel').html('<?php echo $description; ?>');
		$('.pageicon').html('<span class="<?php echo $icon; ?>"></span>');
		
	});
</script>
<style>

</style>
<?php require_once APPLICATION_PATH.'/views/scripts/index/messages.phtml'; ?>
<div class="row">
	<div class="col-sm-12">
		<div class="box box box-color box-bordered">
			<div class="box-title noheader">
                <h3></h3>
            </div>
            <div class="box-content nopadding">
                <div class="divider5"></div>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="col-sm-8">
                            <ul class="resetlist listactions">
                                <?php //if ($acl->checkPermission($resource, ACTION_CREATE)) { ?>
                                    <li><a class="btn btn-primary btn-sm" href="<?php echo $this->baseUrl('config/leaveindex'); ?>"> New <?php echo $moduleitem; ?></a></li>
                                <?php //} ?>
                            </ul>
                        </div>
                        <div class="col-sm-3"></div>
                    </div>
                </div>
                <div class="divider5"></div>
                <table class="table table-nomargin table-bordered table-striped table-hover <?php echo $isdatatable == true ? 'dataTable' : ''; ?>" id="">
					<thead>
                        <tr>
                            <th style="vertical-align:top;">Name</th>
                            <th style="width:12%;vertical-align:top;">Default <span class="blocked">Value</span></th>
                            <th style="width:10%;vertical-align:top;">Bookable</th>
                            <th style="width:10%;vertical-align:top;">Paid</th>
                            <th style="width:12%;vertical-align:top;">Authorised</th>
                            <th style="width:12%;vertical-align:top;">Deduct From <span class="blocked">Balance</span></th>
                            <th style="width:12%;vertical-align:top;">Calendar <span class="blocked">Color</span></th>
                            <th style="width:100px; vertical-align:top;"></th>
                        </tr>
					</thead>
					<tbody>
                    	<?php if($has_no_data){ ?>
                        	<tr><td colspan="20"><div class="alert alert-warning"><?php echo $this->translate("global_list_noentries"); ?></div></td></tr>
                        <?php } ?>
             			<?php
							foreach($result as $line){
								$indexurl = $this->baseUrl('config/leaveindex/id/'.encode($line['id']));
						?>
							<tr>
								<td class="nullifempty"><?php echo $line['name']; ?></td>
								<td class="nullifempty">
									<?php 
										$qtype = '';
										if($line['quantitytype'] == 1){
											$qtype = ' (Hours)';
										}
										if($line['quantitytype'] == 2){
											$qtype = ' (Days)';
										}
										
									echo isEmptyString($line['defaultquantity']) ? '--' : formatNumber($line['defaultquantity']).$qtype; ?>
								</td>
								<td class="nullifempty centeralign"><?php echo $line['bookable'] == 1 ? '<span><button type="button" class="btn btn-xs btn-default"><i class="fa fa-check"</button</span>' : '<span><button type="button" class="btn btn-xs btn-default"><i class="fa fa-remove"</button</span>'; ?></td>
								<td class="nullifempty centeralign"><?php echo $line['paid'] == 1 ? '<span><button type="button" class="btn btn-xs btn-default"><i class="fa fa-check"</button</span>' : '<span><button type="button" class="btn btn-xs btn-default"><i class="fa fa-remove"</button</span>'; ?></td>
								<td class="nullifempty centeralign"><?php echo $line['authorised'] == 1 ? '<span><button type="button" class="btn btn-xs btn-default"><i class="fa fa-check"</button</span>' : '<span><button type="button" class="btn btn-xs btn-default"><i class="fa fa-remove"</button</span>'; ?></td>
								<td class="nullifempty centeralign"><?php echo $line['deductfromallowance'] == 1 ? '<span><button type="button" class="btn btn-xs btn-default"><i class="fa fa-check"</button</span>' : '<span><button type="button" class="btn btn-xs btn-default"><i class="fa fa-remove"</button</span>'; ?></td>
								<td class="nullifempty centeralign"><?php echo $line['calendarcolor']; ?></td>
								<td>
									<?php //if ($acl->checkPermission($resource, ACTION_EDIT)) { ?>
										<a class="btn inline blockanchor" href="<?php echo $indexurl; ?>" title="Update" rel="tooltip"><i class="fa fa-edit"></i></a> &nbsp;
									<?php //} ?>
									<?php //if ($acl->checkPermission($resource, ACTION_DELETE)) { ?>
										<a class="btn deleteline" action="<?php echo $this->baseUrl('config/delete/id/'.encode($line['id'])."/entityname/LeaveType/successurl/".encode($this->viewurl)); ?>" message="<?php echo $this->translate('global_delete_confirm_message'); ?>" title="Delete" rel="tooltip"><i class="fa fa-times"></i></a>
									<?php //} ?>
								</td>
							</tr>
						<?php } ?>
                    </tbody>
             	</table>
                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-actions">
                            <div class="col-sm-3 paddingleft5 floatleft"><?php echo sprintf($this->translate("global_list_counter"), $paginate->getItemCounterText()); ?></div>
                            <div class="col-sm-6 padding0"><?php echo $paginate->getPaginationLinks(); ?></div>
                            <div class="col-sm-3 padding0 rightalign"><?php echo $paginate->getListCountDropDown(); ?></div>
                        </div>
                    </div>
                </div>
                <div class="divider5"></div>
           	</div>
     	</div>
	</div>
</div>          
<?php
	require_once APPLICATION_PATH.'/includes/footer.php';
?>
